### ISSUE TITLE
Afrileaks 002 - notification in the receiver landing page

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1072]
As part as previous issues #1047 and #1021 this issue is to keep track of GLClient and GLBackend modifications in order to get this subdeliverable.

The goal is: a new receiver landing page, containing the latest notification for the receiver. 

Admin side/Node table: will exists a new boolean flag, changing the current "disable notification" with "disable email" (and probably instead of keep them in memory only, can be removed in the DB)

change the current working model of "disable notification": every notification will be collected, because is an unique data saying for the user "which event are happen meanwhile you were not here".

every notification is copied in a JSON data and stored in the database, to be displayed on the landing page. when the user accesses to the tip,  information about new comment|file associated to the tip is removed.

The display order will privilege tip with traffic instead of new tip (I was thinking on two separate table), and the feelings will be similar to github notification list.

There are a limit of 20 or such. (This is important because at the moment we have not protection against presence of 100+ tips, that will cause heavy rendering)

**Comment by evilaliv3** [comment]
this makes sense. 
in addition to what we discussed yesterday i think that this data may be stored on a MailBox currently not existing. the table may be the same with the following fields:

1) event title (the mail title / logline title
2) event description (the mail content / the line content to be in a popup message when the elem is clicked)
3) the date it happened
4) mail_status (sent or not sent, to be used for spoling)e 
5) view_status of the log (view or not view)
6) owner the userid of the owner

@vecna any other idea of things of interest to be shown?

**Comment by vecna** [comment]
@evilaliv3 good idea, just to remind to us, we are creating this entry (Table ReceiverEvent, in order to do not mistake with globaleaks.plugin.base.Event ) based on:

    Event = namedtuple('Event',
                   ['type', 'trigger', 'notification_settings',
                    'trigger_info', 'node_info', 'receiver_info',
                    'context_info', 'steps_info', 'plugin', 'trigger_parent'])

you are mentioning:

  * event title: this is, we can assume, the same title of the email ? 
  * event description: we are going to collect trigger_info I guess
  * date: is part of trigger_info
  * mail_status: is that important ? 
  * view_status: is that important ? I guess that, is the thing get visualized, we just remove it from the list.and exists an API method DELETE equivalent to "mark all as read"
  * owner: is part of receiver_info

I feel we can assume:

  * in the future this can be the base for the digest mode: disable email sending, having a schedule that send a resume once a while
  * in the future, new feature or message from the admin can be event itself

**Comment by evilaliv3** [comment]
agreed.

i would not give a name Receiver* as i think this would be useful in general also for admins (this is why i added a owner field that will host the user_id

what about calling it EventLog?

and great that we are now implementing the support for the digest with this :) this is why i added the mail status in here :) 
i was thinking this table to host mails after tip handling so that in case of mail falirures we don't have to reschedule all things as we do now.

for other questions :

  * event title: this is, we can assume, the same title of the email ?  YES exactly it the title of the prepared mail (or the title to be added in the list when creating the digest)
  * event description: we are going to collect trigger_info I guess; is the content of the prepared email (or the content to be atted in the list when creating the digest)
  * date: is part of trigger_info (the Event is what is handled by the Tip notification scheudler that serialize the info in this table (for what i remember the Event still do not have the support table, this will be the serialized table of the important things of Event)
  * mail_status: is that important ?  (yep, to be used for markers related to failures, digest and bla bla)
  * view_status: is that important ? I guess that, is the thing get visualized, we just remove it from the list.and exists an API method DELETE equivalent to "mark all as read". (i think having the marker is better as we can safely keep the log of this infos, the only problem i see is for sensitive information but i will explain this to you directly
  * owner: is part of receiver_info (also for this, there is no serialization of the info in the db currently)

**Comment by vecna** [comment]
refactor of notification_sched.py implemented here: https://github.com/globaleaks/GlobaLeaks/commit/f221fa8807ae937c2209a4cb6f904d135cee3ebd

**Comment by evilaliv3** [comment]
great, i'm going to finish to implement the login change and then i will pass it to you for the review

**Comment by vecna** [comment]
deserve to be mentioned, that I've implicitly reverted the feature of #444 (now a submission of tip+2 files, receive three notification at once. before just was being sent the tip notification, for the above mentioned issue)

**Comment by evilaliv3** [comment]
Little preview.

![screenshot from 2015-01-08 17 51 34](https://cloud.githubusercontent.com/assets/217034/5666324/1932d354-975f-11e4-8f4b-f878624fab79.png)

@vecna any suggestion?

**Comment by vecna** [comment]
nop, simply good, I'll try it

**Comment by evilaliv3** [comment]
completed by commit: https://github.com/globaleaks/GlobaLeaks/commit/4682e0ec6e648414ed7f1f09f0afd4abaa674d90
