### ISSUE TITLE
Clientside session management is not properly working

### ISSUE THREAD

**Issue by 2langnic** [globaleaks/GlobaLeaks#1083]
Hello! 
I think i have found some bugs in the implementation of the session timeout on the client side.
1) client/app/scripts/services.js function setExpiration (line 24): 
if (expiration_date >= current_date) (line 35) is inverted.
- expirationDate is the value overgiven from the backend resolved with getTime() which returns "The number of seconds after the epoch at which this call is scheduled to be made" (see http://twistedmatrix.com/documents/14.0.0/api/twisted.internet.base.DelayedCall.html#getTime)
So the expiration Date is already in the future (in the current implementation 60 Minutes)

I would suggest to fix it to if (current_date >= expiration_date).

If you fix it it will still not work due to the second bug :)

2) client/app/scripts/services.js function setExpiration (line 24): 
The $timeout is set with $timeout(checkExpiration, expirationDate - current_date). 
The problem is that the timeout calculated from  (expirationDate - current_date) is always negative because:
- expirationDate is the value overgiven from the backend resolved with getTime() which returns "The number of SECONDS after the epoch at which this call is scheduled to be made"
- current_date is a newly created javascript Date (new Date()) which is a number of MILLISECONDS  ("JavaScript dates are calculated in milliseconds from 01 January, 1970 00:00:00 Universal Time (UTC)" Source: http://www.w3schools.com/js/js_dates.asp))

So the current_date is always factor 1000 bigger than the expirationDate.
The negative value cause $timeout to directly call the function checkExpiration which causes a high load.
I would suggest to change the two occurences of current_date to (current_date / 1000) and add a comment :)

I have already fixed it at my branch with commit https://github.com/2langnic/GlobaLeaks/commit/1cce00b853c039154cba519f6e0907556a488e91

You can test with setting the self.defaults.lifetimes in settings.py to a lower value and if you are not using the patch the page will not be forwarded to the login page when the session expires.
This will only happen when you click on a link which then forces the backend to check if the session is still active and then you will be forwared to the login page.

This bug also masked another problem: The timeout on the client is never reset by doing some actions (like changing the tab). 
In the Backend the timeout reset is done on every @authenticated call (touch on the TempObj)
I would suggest to choose one implementation (Idle Timeout or Absolute Timeout).

**Comment by evilaliv3** [comment]
@2langnic it seems that you are right. thanks for reporting it.

by the way given that the session is enforced and well implemented on the backend no security impact exists. i will test your solution by tomorrow and we will integrate it.

**Comment by evilaliv3** [comment]
thank you @2langnic. i confirm that no security impact existed thanks to the correct glbackend implementation. by the way now also the performance issue that was lieing in this error is fixed.

**Comment by evilaliv3** [comment]
hans corre

**Comment by evilaliv3** [comment]
@2langnic correctly reported a doubt: now that we have a working clientside handling of the session we have a new different client of problem . we have a clientside handling of the session that is based on the timeout, while the backend handling of the session is based on idling (for every request the session i resetted); so that what now is happening is that the client will use only the first timeout provided by the backend and it will close the session also if due to the user activity the timeout should be resetted.

he is proposing  to align the two making use of a simple timeout based expiry time, but we can't have this due to the need to keep the session alive. so what i would implement by now is the removal of the clientside logic that disconnects and we will simply rely on the backend. anyway this would work, to be sure of this think that for example since ever we didn't have any proper client reset of the session and regardless of this all was working.

**Comment by evilaliv3** [comment]
with commit https://github.com/globaleaks/GlobaLeaks/commit/d57b9310ed57312fc16e53c6c0814231991b33d7 i've removed the code; this issue and that commit will keep track of the code. bai bai!

 no issue exist as you have to remember that this code was not working at all since ever and has been changed only yesterday. by the way now that it was corrected it was causing problems to the #537

**Comment by fpietrosanti** [comment]
ng-idle is interesting module https://hackedbychinese.github.io/ng-idle/
