### ISSUE TITLE
Optimize loading time of GlobaLeaks client by compressing it with bzip2

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1088]
This ticket is to optimize loading time of GlobaLeaks client by compressing it with bzip2 .

When globaleaks load, the bootstrap in the index.html file load GLClient that's contained in /scripts.js .
GLClient (compressed by using JS compression method),  currently (12 Jan 2015) is 968Kbyte and it take a while to download over a slow connection.

This ticket is to introduce bzip2 compression for the loading of scripts.js that reduce the size as follow:
root@demo:~# du -s scripts.js
968	scripts.js
root@demo:~# bzip2 -9 scripts.js
root@demo:~# du -s scripts.js.bz2
232	scripts.js.bz2

The bzip2 compression/decompression support could be used by several libraries such as:
* compressjs (https://github.com/cscott/compressjs)
* bzip2.js (https://www.openhub.net/p/bzip2_js)

To be further discussed/evaluated, as there could/should be complementary strategies/approach o reduce loading time such as reducing the amount of overall HTTP requests since the first "GET /"

**Comment by evilaliv3** [comment]
ok, with previous commit i've successifully enabled GZIP compressions cyclone webserver.
@fpietrosanti / @hellais / @vecna / @mmaker : strangely we forgotten to enable it since time.

this is the result: the simple script.js i now transmitted in 277kb instead than 1055kb and the same apply to all files provided by the backend! given that there is no reason to implement something not standard based on bzip2.

![screenshot from 2015-01-21 14 53 48](https://cloud.githubusercontent.com/assets/217034/5837350/c5dbc6c8-a17e-11e4-93e8-a0735dd05398.png)
