### ISSUE TITLE
Handle permission issues with /dev/shm

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1093]
This ticket is to preserve the Integrity of all globaleaks related files And directories by checking on startup for proper ownership/permissions And by resetting it in startup.

The software should not startup if The permission/ownership check/Reset didn't worked properly
##

**Comment by evilaliv3** [comment]
this is already performed by the application and there is only a problem with /dev/shm that i should probably fix.

by the way there are conditions that should be fixed like the following:
- if globaleaks is started as a different unpriviledged user from the owner of directories surely we will fail. so we need to at least a try except mechanism where we try to perform actions and eventually we print an error for the end-user.

**Comment by NSkelsey** [comment]
I am hijacking this ticket to propose a solution to the issues that we have seen with /dev/shm.

Instead of using `/dev/shm` and expecting temp files to persist across restarts, we can drop that requirement by using tempfiles. Designating a tempdir in `/tmp` and relying on tempfiles following the same structure we use currently in `/dev/shm` could save us from two things. 1) Unnecessarily preserving file data 2) encountering permission issues on the modified file.

Some code to follow.

**Comment by fpietrosanti** [comment]
The reason to uses /dev/shm/ i remember was to keep in-memory volatile all the operations of receiving AES encrypted uploaded files, storing their keys in a volatile environment, and maybe to keep all gpg operations files to never touch the filesystem

**Comment by fpietrosanti** [comment]
@evilaliv3 is this fixed/closed?

**Comment by evilaliv3** [comment]
sir, yes sir!

we are not using /dev/shm anymore!
