### ISSUE TITLE
Disabling private message does not work properly

### ISSUE THREAD

**Issue by 2langnic** [globaleaks/GlobaLeaks#1114]
Hello,
i think i have found another bug :)

When disabling the "Private Message" Option on a context the current effect is that the "Additional Information" (comments) Box disappears but the "Private Message" Box is still there.

I have found the problems and fixed them with my commit : https://github.com/2langnic/GlobaLeaks/commit/b7e3bba7d2cde4ccd5e577635f8de9ee37680877

**Comment by evilaliv3** [comment]
@2langnic  i see the issue but it's not a matter of a bug but simply a matter of wrong naming and the patch you are proposing contains some bugs.

let me explain: in past we had "Private Message" and "Public Messages". t hen we add a simplification in order to alway call them Private messages in the case only one receiver is involved.

i will solve your issue making a patch so that the following situations will be possible:
1) both public and private messages are enabled: they will be called "Additional Data", "Private Message"
2) if there is only one receiver involved 1) wil be simplified by using a different name depending on the "Enable private messages  setting; in case the setting is enabled we will call il Private Messages (as now), in the case the setting is disabled we will call it Additional Data (patch i'm going to implement)

**Comment by evilaliv3** [comment]
done!
