### ISSUE TITLE
GlobaLeaks iptables/sandboxing support accumulate rules at each restart

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1129]
GlobaLeaks iptables/sandboxing support accumulate rules at each restart.

This lead to unexpected behaviours. 

To reproduce just restart globaleaks few times and look for iptables -L -n -v

**Comment by evilaliv3** [comment]
cannot reproduce anymore.
on the proxmox machine we were playing on there was a strange bug happening with --owner --uid-owner globaleaks that caused iptaables to go in error with: iptables: No chain/target/match by that name.

due to this those rules where not applied apart from some and on stop/restart the code was failing to find rules with "globaleaks" owner so we skipped to remove the rules.

any hint or suggestion in order to detect / solve such a situation?

@fpietrosanti / @vecna

**Comment by vecna** [comment]
if that is the error, is because is missing the match extension on iptables, (match user id require a netfilter module for kernel and userspace)

**Comment by evilaliv3** [comment]
fixed in commit: https://github.com/globaleaks/GlobaLeaks/commit/ec0d273e122a68f4c139c936619df059802a9a34

delivered in release 2.60.64
