### ISSUE TITLE
Missing Password Recovery Procedure

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#113]
Currently the password recovery procedure is missing as per https://docs.google.com/a/apps.globaleaks.org/document/d/1SMSiAry7x5XY9nY8GAejJD75NWg7bp7M1PwXSiwy62U/edit#heading=h.8wjyz0tbvnl0

**Comment by vodkina** [comment]
is this issue solved? Can we close it?
If not, please estimate it.

**Comment by evilaliv3** [comment]
It is not a bug to be fixed. Its a nice desiderata.

Its not estimated because it is still to be analyzed.

**Comment by fpietrosanti** [comment]
Requested on #2005

**Comment by NSkelsey** [comment]
We are reactivating this super ticket, to finish it up for v2.80. Some of the first things we need to anticipate are the password reset texts that describe how to recover access. Like all other settings this will be a configurable switch (@Evilaliv3 wants set to default on (I disagree)) in the config table.

Github talks about it in the following way:

![setup](https://user-images.githubusercontent.com/1095794/29023156-c808b6f2-7b6c-11e7-85b4-f0e163816506.png)
(if you provide an invalid email they tell you the mail does not exist. This we will not do)

After providing a real email:
![return-to-sign-in](https://user-images.githubusercontent.com/1095794/29023181-e61557b8-7b6c-11e7-9a3d-3fd2e5b14349.png)

The email looks like this:


> We heard that you lost your GitHub password. Sorry about that!
> 
> But don’t worry! You can use the following link within the next day to reset your password:
> 
> https://github.com/password_reset/1234590457912374712390471293471928374981273123749081237973249712398754745754678938970134278945789657893412093241092347
> 
> If you don’t use this link within 3 hours, it will expire. To get a new password reset link, visit https://github.com/password_reset
> 
> Thanks,
> Your friends at GitHub
```

**Comment by NSkelsey** [comment]
For Gmail it is a bit more complicated, but the wording is roughly the same:

![google-forgot](https://user-images.githubusercontent.com/1095794/29023949-2cfb5724-7b70-11e7-9f8f-a4bd2a75377e.png)

One time coded!

![one-time-code](https://user-images.githubusercontent.com/1095794/29024044-8812881c-7b70-11e7-9f3e-41dca07c10c0.png)

Recovery Email:

![verification-code](https://user-images.githubusercontent.com/1095794/29024061-984615d2-7b70-11e7-9ac1-bd9b7fed8535.png)

**Comment by NSkelsey** [comment]
After doing a bit a research, Troy Hunt produced a [reasonable summary](https://www.troyhunt.com/everything-you-ever-wanted-to-know/) of handling password recovery in 2012, which serves as the basis for my current thinking on this issue. 

GlobaLeaks should only support password recovery only when support for a hardware based second factor is added. The solution proposed by @vecna above is a victim a to two issues if we implement the feature naively.

1) An attacker that can read a users email's means the GlobaLeaks account is compromised
2) An attacker that can read the database or just the plaintext token stored within it, can takeover these accounts, edit and remove content from the platform.

To resolve 1) we must have a way to identify that the user is genuinely who they say they are before allowing the password reset. This can be done with 'secret questions' to the tune of PayPal era solutions like "What was the name of your high school" which will be hard to internationalize or with physical or cellphone based 2-Factor Authentication. I think it will be a lot of work formulating good questions and would prefer that a physical solution be adopted for those who want to have password reset.

To resolve 2) we simply must store the hash of the token in the database instead of the token itself. While the token is in memory and sent via email it is still reachable, but a SQL injection or a mistake by an administrator will not immediately result in writable access to a running Globaleaks node.

We need to define under what conditions and which users can reset their passwords in the first place. It is clear that `receipts` and `custodians` need to have this functionality. `administrators` have a route to reset their password via command line access which serves when that administrator also has shell access to the machine.

A good flow chart protocol to follow is outlined in Troy's article. This should serve roughly as the basis for the eventual implementation we go for and it can certainly be categorized under OTF-4.2.

![shrug-2fa-needed](https://user-images.githubusercontent.com/1095794/29027426-f31ac1e6-7b80-11e7-82ba-6bb6d73b6811.png)

/cc @fpietrosanti @evilaliv3 @IuliiSe

**Comment by fpietrosanti** [comment]
@NSkelsey as we move more and more to cloud setup, administrators are normal non-technical users and shall have the very same capabilities of "normal users". 

Anyhow i would really avoid implementing this feature until there are thousands of users and the self-password-reset became a necessity because the human overhead to do the job become too high. 

When we will reach that point (imho 24-36 months), i think we would have landed to some kind of federated authentication systems and/or have on-boarded client-side encryption and/or SRP based authentication.

**Comment by evilaliv3** [comment]
Feature implemented here follows images of current implementation:

![screenshot-127 0 0 1 8082-2018-06-07-11-22-14](https://user-images.githubusercontent.com/217034/41094366-5eedc834-6a4e-11e8-8c63-c0658ffb14e2.png)

![screenshot-127 0 0 1 8082-2018-06-07-11-22-48](https://user-images.githubusercontent.com/217034/41094380-6a96e328-6a4e-11e8-8bc3-928d13ba9ef2.png)

![screenshot-127 0 0 1 8082-2018-06-07-11-15-55](https://user-images.githubusercontent.com/217034/41094374-64266068-6a4e-11e8-8db8-fa207b55936f.png)

![screenshot-127 0 0 1 8082-2018-06-07-11-18-38](https://user-images.githubusercontent.com/217034/41094390-711a8d3a-6a4e-11e8-9209-362a2945b5d3.png)

![screenshot-127 0 0 1 8082-2018-06-07-11-19-17](https://user-images.githubusercontent.com/217034/41094396-74d1526a-6a4e-11e8-8455-e643a14c69b5.png)

![screenshot-127 0 0 1 8082-2018-06-07-11-30-18](https://user-images.githubusercontent.com/217034/41094405-788a628e-6a4e-11e8-9c92-08094a982ea8.png)

**Comment by evilaliv3** [comment]
Closing the ticket, the feature will be released with release version 3.2.0
