### ISSUE TITLE
Discuss about eventual security issues related to assignment of a sequence number to Tips tracked by the node and shown to users.

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1158]
This ticket aim is to discuss eventual security issues related to assignment of a sequence number to Tips tracked by the node and shown to users.

Also if the feature is good and we as hermes thought to it during last TI-it workshop, the feature is not still needed by any adopter nor by TI-it that is more interested in assigning a label related to external tracking numbers so i'm assigning the backlog milestone to this ticket

My concern in implementing a sequence number would be:
1) is useful to show this info to the user and to who? probably in realtime not as one could track user activities. i'm the attacker an i make a submission once a minute just to know the exact timing of submission happening on the node. (the same can be done by a spy receiver by sending a submission to himself that wont't be noted by other users.
2) the amount of leaks received is leaked to all receiver? can this represent a problem? probably not but it surely a thing to know.
3) just a mind thought in order to brainstorm on the impact of such a feature, also if all tips are expired in case of seizure the attacker would know exactly how many submissions are sent and this would be interesting for various reasons. e.g. the attacker know that that a precise number of cyphertexts that can be present on the filesystem. this can be useful to crypto analysts and would be probably solved with the presence of srm.
4) a solution to 1 and 2 can be to have not a global sequence number but a per-receiver sequence number so that this sequence is shown only to each receiver and relative only to himself? it wont be userful when working in a team but would solve 1) and 2). anyhouw it does not solve 3) (remember that 3 is not a description of an attack but a mind excercise to think about possible threats in implementing such a feature)

for this and other reasons also if implemented this feature will need to implemeented as optional
 
yesterday i thought to some more but now i can't remember.

**Comment by fpietrosanti** [comment]
I do not foresee any of the problem described, would suggest to make it default as a simple usability improvement without security risks

**Comment by evilaliv3** [comment]
I agree that we can insert it without going so much in detail but I do not
found stupid nor difficult the idea of introducing an enable/disable
boolean

**Comment by fpietrosanti** [comment]
Having a single, unique identifier across all users and the system, that's communicated to the users across all the available communication channel sounds like a basic feature, we're just moving from a single integer (132) to something a bit more meaningful (14022014-01). 

What's the reason/benefit, to be explained to a user, for "enabling/disabling" having an identifier of a Tip?

**Comment by evilaliv3** [comment]
Cause this way we are adding tracking possibilities for the timing of
submissions. I've already explained it.
Scenario:
Im an attacker and i make a single request every minute, I will be able to
know the exact timing of other submissions by simply analyzing the global
counter and removing the number of submissions I've done.

**Comment by fpietrosanti** [comment]
@evilaliv3 no, you are not adding any additional tracking possibilities. 
Those specific meta-data are already, in a much precise format, due to SMTP "Date:" standard header, regardless our modification.

**Comment by vecna** [comment]
**idea**: at the moment we've a random number between 1 and 999 identify every Tip. was intended exactly to do not leak the amount of Tip of a node. We can put a boolean node level, to assign this number random or incremental (based on the DATE+NUMBER pattern, or just based on the incremental NUMBER), by default remain the random one (and has to be display also in the Tip list, instead of just on the notification subject)

**Comment by fpietrosanti** [comment]
I'm still missing/not understanding which is the problem we're trying to solve, as i do not see any added vulnerability or security issue between DATE+NUMBER compared to NUMBER.

**Comment by evilaliv3** [comment]
no fabio you are continuing to miss the point. the date is not related at all to what i'm explaining.
i make you the explicit example example; next time reread all the topic before continue to comment:
i'm the attacker i make a submission every minute.
for every request i see i read the counter i get. i expect that submission increment one by one:
1,
2,
3,
4,
5
...

everty time the counter is not the one expected e.g. the progression is 1, 2 3 5, i know that a submission is happened exactly in that minute.

@vecna i don't think a solution really exists wanting to have a sequence progressive number that identify exactly how many submissions happened; the solution i see is only to make possible to enable it only by who has important need for it (and i repeat that no initiative want it right now).

**Comment by fpietrosanti** [comment]
@evilaliv3 I see definitively no security issue compared to the current situation following your explanation, really, there's no security problem. 

Let's look what the attacker see *today* on the wire by following your example:
Subject: [New Submission 473]
Subject: [New Submission 823]
Subject: [New Submission 333]
Subject: [New Submission 666]
Subject: [New Submission 999]
Subject: [New Submission 283]

Ok?

So, today the attacker you described sending a new submission every minute know that he sent 5 submissions, but he read 6 notifications with subject "[New Submission]".
So he know that a "new submission" has been and he know in which minutes (because you are assuming that the attacker can make a new submission and can read all SMTP traffic, so he know when a new notification has been sent due to HIS submission and when NOT due to his submissions).

Given that example, changing the $NUMBER to $DATE+NUMBER does not change anything, because the timing is already recorded "on the network" by the attacker (in your assumed threat scenario).

**Comment by evilaliv3** [comment]
sorry i don't get your point. maybe we have to talk.
my attacker has no intercept capabilities and do not need special tools nor
instruments. he is a whistleblower with a browser an making a submission
and reading the tip number on tip page) or a receiver reading submission he
do or from the notification page or from the tip page.

instead from your descripion i think you are talking to an attacker able to
sniff the mails. for sure this attacker will know how many mails pass by
without the need to do fake submissions.

**Comment by fpietrosanti** [comment]
We agreed by phone that's fine to have $DATE+$PROGRESSIVENUMBER where $PROGRESSIVENUMBER is only related to the $LAST_DAY

**Comment by fpietrosanti** [comment]
Is this implemented then?

**Comment by evilaliv3** [comment]
still not

**Comment by evilaliv3** [comment]
Feature implementation completed!

The traditional mail subject prefixed by [Tip NUM] is now replaced by [YYYYMMDD-SEQ]

e.g.: [20151105-1]

Rembember, Remember, the fifth of November
