### ISSUE TITLE
Receipt codes with valid credit card numbers

### ISSUE THREAD

**Issue by origliante** [globaleaks/GlobaLeaks#1169]
>>> pow(10, 12) / 1000 / 60 / 60 / 24
11574

try every possible receipt combination with a somewhat fixed prefix at a 1000req/s to download a full DB takes 11,574 days with a perfect randomness. What about giving the receipt codes a valid credit card format? Which implications on the randomness of the code would it cause?

Credit card numbers not only have prefixes, but also are constructed based on a format that passes the "Luhn test":

http://bradconte.com/cc_generator

@fpietrosanti @vecna @evilaliv3

**Comment by fpietrosanti** [comment]
What's the problem we're trying to address?

**Comment by origliante** [comment]
"Working" deniability as a credit card number

**Comment by fpietrosanti** [comment]
To achieve better "deniability" we would need also to re-work the image in a "realistic format" due to upcoming https://github.com/globaleaks/GlobaLeaks/issues/1141 .

Btw the issues in modifying the current receipt is in the amount of bits of entropy that would be reduced below the minimum acceptable identified by the penetration test https://drive.google.com/a/apps.globaleaks.org/file/d/0B6tQ4kKC2rLzWU93ck5WTUFDSmc that lead to fixing the issue https://github.com/globaleaks/GlobaLeaks/issues/823 .

I don't have a solution on how to keep, or increase, the entropy while providing deniability, let's brainstorm

**Comment by vecna** [comment]
@origliante funny idea, just think that we've a anti bruteforce delay function that can slowdown that, and Tor hidden service has some intrinsic latency trouble in establishing new sessions.

@fpietrosanti  well, we've also the security code of the pseudo-CC (three digit) and an expiration time, both can provide (few bits, but) more entropy.

**Comment by evilaliv3** [comment]
closing this ticket as not really doable; it would reduce a lot the entropy that is already limited.

also adding an expiration XX/YY and CVV ZZZ would offer too few entropy for the complexity it would add.
