### ISSUE TITLE
Make clear that globaleaks is not accessible on Internet

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1175]
After the install script need to be added:

  * address to the hidden service generated, asking the admin to copy/paste in some place
  * explanation that cannot be reach via internet (+ link to advanced config to do such)
  * tor browser bundle as requirement + link to TBB

**Comment by evilaliv3** [comment]
ok for the feature or enhancement, or documentation, but a bug is a bug and this is not a bug. :)

**Comment by vecna** [comment]
it is good enough ?

**Comment by evilaliv3** [comment]
good in the aim but i'm not perfectly sure that that a cat excecuted after a service tor restart will found the hostname already present. tomorrow i will check it and we need to be sure of this before releasing this.

**Comment by evilaliv3** [comment]
i see that @fpietrosanti already addressed this here without updating this ticket.

https://github.com/globaleaks/GlobaLeaks/commit/8f6f3113aebf4220e7c47a162a47f5c2f8de8110

i would probably go on reveting this patch added inside the package and integrate your text with the one of @fpietrosanti . it's better to keep this output out from the package and put it inside the init script due to strong compatibility with debian packaging guidelines

**Comment by vecna** [comment]
I totally miss @fpietrosanti patch :( 
put a sleep before the file check ? 
put some address to get support in the text message ?

**Comment by evilaliv3** [comment]
@vecna apart from the sleep correction that we should see if it is really needed of if tor has already created the hidden service keys when returning from a "service tor restart", i've opened the ticket above to discuss the other things that i find important let's say as all the teaching information we have in globaleaks like the privacy badge, the security awareness badge etc.
