### ISSUE TITLE
Make the credit card hint on the Receipt page configurable

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1187]
This ticket is to make the credit card hint box on the Receipt page configurable as follow:

- Display the credit card hint (default)

- Don't display (it shall be taken care to align all the text in the interface properly)

- Configure custom text (enable admin to write it's own custom hint)

**Comment by evilaliv3** [comment]
as short term fix i'm going to make possible to to disable it simply by CSS and to add the variable in order to disable it this will be released in few days releasing a new stable version (current master) with only the translations by the localization lab)

then  i will integrate the long term fix with possibility for configuration thjat will pushed out in some weeks after various integration activities.

**Comment by evilaliv3** [comment]
@fpietrosanti with this commit i've implemented the following:
1) the hint can now be disabled by the advanced settings with a setting "Disable key code hint panel"
2) the hint css is now customizable (hideable) by using css propery: KeyCodeHintBox

what is missing is the possibility to configure the tooltip entirely, thing that wont be addressed in the short term. so up to you if close this ticket as done in this milestone or move it to whishlist.

**Comment by evilaliv3** [comment]
without hint:
![screenshot from 2015-03-18 02 21 14](https://cloud.githubusercontent.com/assets/217034/6701139/e2ee8c1c-cd18-11e4-93fd-1b0f07a951f7.png)

with hint:
![screenshot from 2015-03-18 02 21 33](https://cloud.githubusercontent.com/assets/217034/6701141/e77a8128-cd18-11e4-9075-954001c2b6fc.png)

**Comment by evilaliv3** [comment]
i suggest that we close this issue and eventually postpone the full customization to a separated ticket that will be finally addressed while dealing of better customization possibilities after markdown/wysiwyg implementation.
