### ISSUE TITLE
More useful stats

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1206]
So far the stats system has developed a lot, but far from the ideally useful. A practical feature that could  be improved/implemented:
- Information in numbers (so far info on tips, users, files, activity are shown on a list or in a color graphic only, what makes impossible to get real useful stats to build studies and use statistics)

It raises the issue regarding the power of surveillance an admin may have regarding the node activity. A suggestion is to choose it on node installation and that this info should be later available to all receivers.
##

**Comment by evilaliv3** [comment]
thanks @infosquatter. 

can you describe better your idea of god stats and what exact info you would like to have?
as you know currently stats are simply an instument for the admin to see that the node is working, but providing a non good anonymized stats make him in possibility to understand what happens, wen, to who, on each contexts.

all this things should be kept in mind so from our point of view is important that you personally elaborate a full description of your ideal stats.

**Comment by infosquatter** [comment]
thanks @evilaliv3 . some examples:

number of tips - total/per-receiver/per-context/per-date/time
number of files uploaded - total/per-receiver/per-context/per-file-type/per-size/per-date/time

will add more, let me give a think.

**Comment by vecna** [comment]
Assigned to myself.

**Comment by vecna** [comment]
Assigned to myself.

**Comment by fpietrosanti** [comment]
I suggest to first make all the data-requested a set of "data sets" that can be configured (the different view requested), to exported as CSV data, so that would be possible to analize data independently from other software, visualize in very different/way independent.

Please before implementing create a "Statistics" Documentation page in the Wiki at http://github.com/globaleaks/globaleaks/wiki with the description of all the statistics being implemented and which information/questions do they answer.

**Comment by vecna** [comment]
This ticket has two different outcome then:

1) export as CSV based on selection of something. I'll start implementing with no filtering capability (also because, if you are going to paint your own graph, you'll strip what you want)
2) some aggregate information like the one asked by @infosquatter 
3) update of Statistics ? I'm ok with that but Statistics are considered for the external observer.

I mean, statistics have two big kind "the stats that make you raises questions" and "the stats that give to you answers".

**Admin require the first** = detailed, maybe not nice, constant in the time
**Anonymous observer the second** = less detailed, with the only goal of display transparency and node activites without compromising WB security.

In this ticket we are speaking about the first.

**Comment by infosquatter** [comment]
There is a very important parameter for the statistics which I missed
before and I think is highly ipmo: Tor-or-Tor2web submissions. Thanks a
lot @vecna. Best, Pedro.


Claudio A.:

**Comment by vecna** [comment]
Thank you for remembering. That is a new issue #1260, this issue about stats improvement for Admin (I guess anyway your requests can be easily accomplished, considering that we have the number, we just need visualize them)

**Comment by infosquatter** [comment]
It also came to my mind that 'uploading time' (per session and per file)
could also be a very "useful stat". Thanks!
Claudio A.:

**Comment by evilaliv3** [comment]
in general for each handler we can track the start and the stop of the handling just to know stats of the tor network in general.

for what concerns the uploading time given  the flow.js thing where the request is splitted among multiple requests i will take the lead on the implementation.

**Comment by evilaliv3** [comment]
Closing in favour of https://github.com/globaleaks/GlobaLeaks/issues/1959
