### ISSUE TITLE
Introduce access restrictions based on IP address

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1211]
Currently the only access control restriction for users in GlobaLeaks is based on access by:
- Tor
- Tor2web

While in the Philippines it has been identified that Access Restrictions for users should be improved introducing access based on IP Address/Netblocks.

In that use scenario the Receivers are lawyers of an anticorruption agency that work within an Intranet LAN. They can access the LAN with their PC or via VPN. 

GlobaLeaks is deployed in a DMZ, also with Tor2web for internet-exposure.

The requested feature is to enable access to the Receivers ONLY from the internal LAN's and VPN's IP address netblocks.

It has been considered particularly harmful/dangerous the public disclosure of all the Receiver's username that, instead, shall be protected and not visible from outside.

For the use-case previously described, this ticket is to introduce support for access restrictions based on multiple IP address/netblocks for the Receivers. 

The list of Receivers should not even be accessible, if not from the list of authorized IP addresses.
##

**Comment by evilaliv3** [comment]
i've various security concerns in doing this on the Tor2web side as i do not want any user to end in publishing automagically its IP address to the GlobaLeaks node on each request.

But there is a but; while i'm saying you this criticism i'm viewing a great solution an capability:
1) tor2web should offer an API that will say the user it's ip (we already have it it's /checktor!)
2) based on 1) it's the GLClient that only on specific requests (let's say the one done for getting data used for login) will provide its IP address. this way only users that will try to act as receivers or admins will send their IP upstream.

do you get the point? this way it will be a capability of globaleaks to provide such a service and not a capability of tor2web disclosing and fucking all the whistleblowers due to the need to protect receiver login.

\cc @vecna \@hellais

**Comment by fpietrosanti** [comment]
@evilaliv3 The Tor2web machine that forward the IP address to the GlobaLeaks machine, IF and only IF, is part of a statically configured set of IP address is the simpler way to go. 
Otherwise remove Tor2web and implement GlobaLeaks with HTTPS, so GlobaLeaks will know directly the IP address, choose what's better, but a piece of server-side software must know the IP address of the authorized Receivers/Admin.

**Comment by evilaliv3** [comment]
damn my solution solve an issue but obviously makes possible the user to forge the ip.

**Comment by evilaliv3** [comment]
i would like not all the ip to reach the GlobaLeaks platform so yep the solution of allowing some ip to pass in tor2web is fine for me.

**Comment by fpietrosanti** [comment]
@evilaliv3 It would be best if we can configure it on GlobaLeaks admin interface, with some static configuration on Tor2web that do fetch that information from the GlobaLeaks server.

**Comment by mttstt** [comment]
Meantime, not having installed tor2web, we applied the following rules on apache2:
-RewriteEngine on
-RewriteCond %{REQUEST_URI} ^(.*)authentication(.*)$
-RewriteCond %{REMOTE_ADDR} !192\.168\.140\.[0-9]+
-RewriteRule ^(.*)$ - [F,L]

**Comment by AbbraKaJazza** [comment]
I know I'm probably going to sound like an idiot, but why do you want to use IP addresses to confirm accounts? Doesn't that make you vulnerable? IP Blocking is stupid too. Too easy a work around, VPN's and Proxy sites make child's play of IP Bans. If you use 4chan method of VPN block then you scare off leakers. Trust needed not to leak a leaker's IP. 

Competence relying on ability to outsmart Intel groups waivers due to lazy security measures. Best free accessible tools are encryption with extra variables added to intensify power of encryption like processes used by Vera Crypt. Mouse movements/Data keys like images/ multi layered encryption to add variance to Encryption Algorithm

Why not use some sort of digital key that can be assigned to a thumb-drive/data storage/image/data block that combines with a time-stamp for a key to encryption. Advise on thumbdrive storage method. If an image the the passcode, then store it in a folder with hundreds of images  with a similar theme and have the name be renamed to become the correct data block adding an extra layer with log details of stored in some sort of repository or SQL Database. This should be encrypted and use the same technique for access. 

Use image and cipher to place signature on the work as verification of admin activities which will have time-stamp and timezone stored without full doxxing. This also give the ability to be able to isolate if there is a hack to isolate through anomaly to find injected/removed code for rectification. Insurance policy that would safeguard users against admin hack, also grant many admins to fish out the potential corrupted accounts.

If the Local time-stamp is out of sync to normal location then have a secondary security access setup with pre-ordained questions/secondary image or data block to pass the secondary security protocol.

I like to think not to be limited by my machine, but have access to other machines and use thumb-drives with OS's loaded on them to keep mobile. "Just a suggestion from a globe trotter".

**Comment by evilaliv3** [comment]
@fpietrosanti @NCommander: i've collected this requirement also for AntifrauCV.

Following what inmplemented in the BustiaEtica of Barcelona, they would like to block the authentication API and make it reachable only by a IPv4/IPv6 range of addresses.

**Comment by NCommander** [comment]
This is likely easiest to just handle in the Twisted layer and just return 403, possibly with something that tells GLClient why the user was blocked (since it normally redirects to the login screen)

**Comment by evilaliv3** [comment]
@NCommander: with previous commit i added a String entry for each role where to configure accepted IP/IP Ranges (for each role) in the format:
SPECIFIC IP,RANGE,RANGE like: ```192.168.1.4, 192.168.2.0/24, 192.168.3.0/24```
As for typical IPTABLES configuration we support ```!``` as operator to invert the sense of the match

As you move this implementation forward try to see if you consider this database support enough.

\cc @fpietrosanti

**Comment by evilaliv3** [comment]
@fpietrosanti @NCommander: i've revised my initial implementation in order to implement, at this stage only ip filtering for authenticated users via the authentication handler.

**Comment by NCommander** [comment]
Implemented when #2268 was merged.
