### ISSUE TITLE
Setup Wizard: backend e-mail regexp validation is different from client-side

### ISSUE THREAD

**Issue by origliante** [globaleaks/GlobaLeaks#1215]
Inserting a@b.c in the admin e-mail field validates correctly, but the Submit button gives a REST error. Tested on current devel .63

**Comment by evilaliv3** [comment]
@origliante please try to tag the issue when submitting it.

**Comment by evilaliv3** [comment]
this is due to the fact that we use different regexps both on GLClient and on GLBackend side.
this will anyhow happen in the future also for other clients implementations / validations.

do you have any suggestion @fpietrosanti ?

**Comment by fpietrosanti** [comment]
@evilaliv3 I think we will likely not have other clients implementations, other than GLClient used as a library, due to the increase complexity for the encryption. 
The only could be an "unencrypted" frontend for dumb clients, but we may argue that we could do that based on GLClient ;P

**Comment by evilaliv3** [comment]
okay so for the moment let's simply keep track of this issue and of the need of aligning the regexps used in the two languages (python/javascript)

**Comment by NSkelsey** [comment]
The current python regexp lives here:
https://github.com/globaleaks/GlobaLeaks/blob/83b6700cd87b1a16212574749e29a7aac6ab4e09/backend/globaleaks/rest/requests.py#L13-L14

The current javascript regexp lives here:
https://github.com/globaleaks/GlobaLeaks/blob/045649d5eebd5972596378919b910d88e65f41f6/client/app/scripts/services.js#L908

There is a problem here in that the client side regexp is more restrictive than the server side regexp. This is a vulnerability

**Comment by NSkelsey** [comment]
I suggest just enforcing a size limitation on email addresses. Nobody other than an attacker will have a 500+ character address.

**Comment by evilaliv3** [comment]
I won't find it critical as vulnerability given the fact that the receiver is internal to the globaleaks based initiative and in the general it would couse simply a minor malfunction but the argumentation is right @NSkelsey 

To close this ticket i would suggest to:
- align the regexp to the best one following email format RFC
- cap the size to 100characters (best would be to be able to do all simply with a regexp so to be able to us it here: https://github.com/globaleaks/GlobaLeaks/blob/devel/backend/globaleaks/rest/requests.py#L18-L19

as desiderata it would be valuable to have a validator here https://github.com/globaleaks/GlobaLeaks/blob/devel/backend/globaleaks/models/__init__.py#L180 to be used for all the models attributes that need to host an email variable

**Comment by NSkelsey** [comment]
[RFC 5322](http://tools.ietf.org/html/rfc5322#section-3.4.1) is the latest standard that defines email address formats. The full grammar for accepting **valid** email addresses is too complicated to express with a regular expression. The grammar defines a context free language grammar while a regular expression can only capture regular languages (See [chomsky hierarchy](https://en.wikipedia.org/wiki/Chomsky_hierarchy#The_hierarchy)).

Since this is security software, we can shrink the set of valid emails addresses to ones that can be defined by a simple regular expression. 

With the current python regex, only domain name based email addresses are possible. I would like to support email addresses of the form `nick@51.35.79.40`. I will update the regex shortly.

**Comment by evilaliv3** [comment]
right analysis

feel free to proceed in this direction.

**Comment by NSkelsey** [comment]
This is the regular expression I am using:

`^(([\w-]\.){0,100}[\w-]{1,100}@([\w-]+\.){0,100}[\w-]{1,100})$`

Debuggex produces this state diagram of the regex:
<img width="883" alt="screen shot 2015-11-05 at 6 14 35 pm" src="https://cloud.githubusercontent.com/assets/1095794/10985908/46270dcc-83f3-11e5-8df6-6d293bdb60d6.png">

I have not tested against many inputs.

**Comment by evilaliv3** [comment]
The patch seem ok and the improval is correct as now the regexps are not complex (as the previous), more secure (due to the size limit) and aligned between glclient and glbackend!

i'm going to integrate it!

**Comment by evilaliv3** [comment]
well done @NSkelsey !

**Comment by ianribas** [comment]
Since this is being changed, I wish to make a small comment and request.

For testing, I was using [Gmail + Suffixes](http://gmailblog.blogspot.com/2008/03/2-hidden-ways-to-get-more-from-your.html) to have multiple email addresses for the users but actually only one mail box, something like `ian.ribas+gladmin@gmail.com`, `ian.ribas+glreceiver@gmail.com`, etc.

The client accepts this but the server doesn't. I had adapted the client regexes for this, it's just a small change, and maybe it could be added here. I think the only change needed is to add `+` as a valid character before the `@`.

Like this:

`^(([\w-]\.){0,100}[\w+-]{1,100}@([\w-]+\.){0,100}[\w-]{1,100})$`

The position of the plus sign inside the brackets is important as the minus (`-`) sign must be the last.

**Comment by evilaliv3** [comment]
great @ianribas ! nice improval.

going to add it.

for what relates to the tests it would be nice to continue using https://mailinator.com/ as i'm already doing for the browsertesting ;)

**Comment by evilaliv3** [comment]
allright, thank you both for the contribution. i would condider this ticket closed now!
