### ISSUE TITLE
Loading the Tip list require a lot of time when there are many Tip

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1224]
It has been verified an important usability bug in GlobaLeaks, that force the Receiver to wait for 60-90 seconds to view the Tip List.

Each single interaction with the Tip list, including back and forward, do require the end-user (receiver) to wait for 60-90s for all the tips to be loaded.

The bug trigger on a system with a lot of Tips (maybe 50-60).

This ticket is to:
- Evaluate a quick workaround (maybe with caching?)
- Specify and implement a long-term fix (support a system having 1500 tips, what we shall do?)

**Comment by evilaliv3** [comment]
i was investigating this before releasing 2.60.64 but with no success.

all seems related simply to sqlite performances, while simply retriving data from the database (in readonly).

two are the possible solutions to be investigated:
1) https://www.sqlite.org/wal.html
2) https://www.sqlite.org/lang_createindex.html

i've for now studied a little the 2) as SQLITE declares to not automatically generate optimization indexes for FOREIGN KEYS so that for each foreign key it would be interesting to do:

    CREATE INDEX indexname_idx1 ON tablename(attributename_of_the_foreignkey);

by the way from teory 2) is good only for big tables and right now with simply ~40 entries we can't consider this a big table and also in my test no speadups are noticed.

\cc @hellais @mmaker @vecna

**Comment by fpietrosanti** [comment]
@evilaliv3 is it possible that's a GLClient bug elaborating the data rather than sqlite?

**Comment by evilaliv3** [comment]
no, the delay is on the backend and it's related to sqlite data fetching.

**Comment by hellais** [comment]
I am not sure why I am mentioned in this ticket.

**Comment by fpietrosanti** [comment]
Is this problem reproducible ? 
A required workaround (anyway) is to introduce paging for visualization/fetching of Tips.

**Comment by evilaliv3** [comment]
with commit https://github.com/globaleaks/GlobaLeaks/commit/5aff170e47de79f126574c54cc80622aaaccb445 i've fixed the issue.

the issue lies in the fact that loading the tip list we where parsing each json data only for creating the preview.
i've now moved preview data extraction ad tip creation so that it is rightly done one time and the load is distributed on each tip instead of being performed every time and for all the tips alltogether.

this fix anticipates also what will need to be done after end2end implementation in order to manage with preview/statical data that would require to be encrypted indipedently (preview) or to not be encrypted(statistical data)

**Comment by evilaliv3** [comment]
in addition now that i've bumped angular to 1.3.16 it would be possible to use the one way binding that would really speed up things on the client and i will experiment it in the next days.

**Comment by evilaliv3** [comment]
ok all that relates to this ticket is released and working on various production setups and i've implemented one-time binding on all the most critical interfaces. time to close this ticket.
