### ISSUE TITLE
Evaluate what material is still valid from old wikis, export it and than disable the old wikis

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1231]
While working with @origliante trying to define some good practices and workflows to be followed by developing and with which betterly organize ourself and the code i've found out that current wiki is missing some good information that was present in old wiki pages of globaleaks-0.1 or other repositories.

what is for sure missing is to integrat code style and guidelines that i'm currently not able to find on present wiki.

**Comment by evilaliv3** [comment]
Ok i've reviewd the various old wiki and i've extracted the code style guidelines we written, i will manage to review and update them in the following days: 

https://github.com/globaleaks/GlobaLeaks/wiki#software-development-guidelines

the following are the interesting but outdated sections that it would be interesting to restore with some priorities:
- technology selection: where to write about the libraries used (short term)
- code structure: where do describe the directory tree of the codel (short term)
- code patterns: where to describe the main code patterns followed both for the backend and for the client (long term)

**Comment by hellais** [comment]
I would suggest also defining some git related guidelines:

* What should be the base branch when submitting pull requests

* Naming for feature/bug/hotfix branches

* What it takes for a branch to land in devel

* What it takes for devel to land in master

Moreover the client dev guidelines should be copy and pasted into the document

**Comment by hellais** [comment]
I also don't agree with the proposed workflow with respect to packaging.

I would suggest to use instead semantically named tags that follow this sort of convention:

debian/$DEBIAN_RELEASE/$GL_VERSION

this is especially important since we are pushing to a git repository that supports overwriting history (you can do force push to a branch) and therefore it is possible for anybody with git commit access to rewrite history, so it's important to have cryptographic proof of what was the code at the point in time when a release was made.

**Comment by evilaliv3** [comment]
I see, now packaging scripts are out signing that is bad. Chanhinh would
cause some code duplication and more difficulties to analyze and maintain
changes that Is what @maker wanted to address with this design.

But I would agree with you and it simply the release project.

I've to evaluate if debuild command allow to specify where the debian
directory is
