### ISSUE TITLE
Clean + clarify meaning in Admin - Advanced settings - main configuration booleans

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1258]
As you see "Disable the security awareness panel" is duplicated.
Plus, I'll open a gdocs with some text hint that can be used to make clearer, for the admin, what are the effects of these booleans.

![image](https://cloud.githubusercontent.com/assets/89555/7469420/a3cbf6ca-f313-11e4-9c1e-962e5ea008be.png)

**Comment by evilaliv3** [comment]
you are right @vecna that code was simply duplicated.

feel free to start a document were annotating the other changes you would like to propose for the new texts / UI.

**Comment by vecna** [comment]
Text proposal https://docs.google.com/document/d/1X9ndoUnzJSJgVImd56UOz0sDqA0UCyZz6-Zpm_1UkpY/edit#

**Comment by evilaliv3** [comment]
i've replaced the document with a new copy editable by us all and i'm going to comment it: https://docs.google.com/document/d/10zRQ2VeaBzo5w1UWyq7Eka910NxFtq3hgyPqQWs8xBA/edit

**Comment by fpietrosanti** [comment]
I love what you are doing, ideally (but not necessarily) this work could be:
- extended to *each and all* section of the admin
- extended to *each and all* settings of each section
- results could be delivered somehow to the wiki in order to update a not-updated-documentation

**Comment by evilaliv3** [comment]
i find it really relevant also.

@vecna what about starting doing it also for all the text, mails and new interface we plan to have for D8 and D2?

**Comment by evilaliv3** [comment]
All the texts related to advanced settings have been reviewed and integrated in devel in https://github.com/globaleaks/GlobaLeaks/commit/fd9c2696b81686b55afdfe576ebe1aa3761313bd

Few are missing and are related to PGP. i do not find useful to make them in translation as in few time we would have to switch to end2end encryption so that it would be a waste of effer; the review of those texts will be part of the end2end encryption text review.
