### ISSUE TITLE
Make it easier delete multiple Tips for a receiver

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1267]
In case of congestion, tips need to be deleted without clicking on every button from the outside, and without having a warning every time is clicked on it, and without having a DELETE command for every Tip. Still, thinking to the open data feed + end2end encryption change seriously this issue. so before think to the steps proposed, is better if we analyze the doubts below.

### Steps

  * delete button has to be moved in another point of the page
  * Receiver "select" the tip in order to apply the command later, like gmail with the delete
  * REST API taking a list of Tip ID

### Doubts 
 
I don't think this procedure can solve a flood in the end2end model. The preview will not be usable anymore, the user will require the possibility to tag/name a Tip like #1156 and for sure an user will access to **all** the tip before delete them. 

In addition, the delete concept maybe should be forget. the "action" that a receiver express is "this tip is meaningful to be analyzed" or "this tip is not meaningful", the effect for the receiver will be the same, but for the open data feed this will correspond more truthfully to "10 submission received, 90% shit" and not to "10 submission received, 20% shit" (with 70% deleted, not disclosed).

**Comment by evilaliv3** [comment]
i'm ok with what specified here!

i suggest to implemente the DELET in the TipsCollection handler that already exists and has only a get().
the delete would take an array of the tips id were an empty array can be used to mean "all tips".
an like in gmail/wordpress/whatever we can have the classical select box on the top of the table were to have: checkall/uncheck all: bulkaction:postpone/delete

**Comment by vecna** [comment]
And the Delete event has to be recorded in the stats then, just I don't know where yet....

**Comment by fpietrosanti** [comment]
It may have relationship with #1224 ?

**Comment by vecna** [comment]
@fpietrosanti yes, but only because I'm thinking to split the tip lists (new, tagged, "new-name-for-deleted-tips") and eventually we can implement paging (that will address completely the issue you are speaking of)

**Comment by fpietrosanti** [comment]
Regarding paging there's a tons of libraries and approaches to do that with AngularJS, don't know the right approach client-side and the impact/requirements for search/selectors server-side:
http://ngmodules.org/modules/Angular-Paging
https://github.com/mizrael/AngularJs-Pagination

**Comment by vecna** [comment]
## Sequence of the operations: 

  * handlers review, paging at handler level, unit test in that side
  * tip interface (buttons, numbers, minor enhancement and #1156 #1260)
  * landing page receiver (number of tip per category) 
  
After, can be addressed the issue about the workflow status of the issues (or directly now ?) because in fact require to change the update of the ReceiverTip... which is the associated issue @evilaliv3 ? I'm keeping an analysis with an adopters on the subject, too.

## TI-analysis
These are the workflow steps, right ?
  * new submission
  * taken in charge ( + assign label ?)
  * something external we've to wait
  * archived (or, deleted for the system)

**Comment by evilaliv3** [comment]
@vecna please keep out all things related to the workflow now.
all the relate to workflow has been simply discussed with TI and with @fpietrosanti we have some generalization ideas; mainly we think that it would be interesting  to make possible for the admin (and in the future eventually by reveivver themeselves) to define post submissjion fields.
by using this post submission fields the admin would be able to:
 - configure fields to be completed by the receivers (e.g. the general status (new, taken in charge, et cetera)
 - configure additional fields to be completed by whistleblowers after the first submission (in order to ask for more info)

**Comment by vecna** [comment]
I've still a bug on the UT (something related helpers), and a bug in the UI (clicking two times on the same button, iterate the activity again, also without selected tip).

**Comment by evilaliv3** [comment]
let me know whenever the patch is ready for review

**Comment by vecna** [comment]
Now is ready. 

as reported, the UT are failing where the GLBackend code is running correctly. I left the pprint just to display the inconsistency.

Client and backend, beside that, are ready.

**Comment by vecna** [comment]
Rebased in devel, opened PR

**Comment by evilaliv3** [comment]
Before integrating the patch i would like to finalize a restyling of the page and retest it more.

Attached are the screenshots of the current implementation:

GlobaLeaks is now full width to use all available space, menu on the left are removed for the receiver for this reason also.
Incons are used instead of full text in order to minimize table width. Popover messages show the table name.
new tips are in bold.

![screenshot from 2015-06-27 10 55 54](https://cloud.githubusercontent.com/assets/217034/8391276/38ead892-1cbe-11e5-91a9-c6ac60f519cd.png)

The table autoremove not useful columns (e.g. here the setup is single context and the context column is missing);
The table implement selectall, deselect all, search
![screenshot from 2015-06-27 10 56 21](https://cloud.githubusercontent.com/assets/217034/8391282/861e77d6-1cbe-11e5-90b9-e81f107fbac4.png)

the table implement ordering in a more compact an one should simply click on items to sort them:
![screenshot from 2015-06-27 11 12 30](https://cloud.githubusercontent.com/assets/217034/8391291/d0ffd984-1cbe-11e5-9133-f2f293db1f81.png)

tip page offers top control so that the top interface result the same as for tip list page
![screenshot from 2015-06-27 11 11 17](https://cloud.githubusercontent.com/assets/217034/8391316/2b118d50-1cbf-11e5-80e4-24653316ea97.png)

receiver preferences page also lacks of vertical menu:
![screenshot from 2015-06-27 11 11 23](https://cloud.githubusercontent.com/assets/217034/8391313/10072560-1cbf-11e5-9c02-d31f40102de1.png)

**Comment by fpietrosanti** [comment]
Some random ordered comments:
* Is it possible for the list of Tip to make it as a "grid" within a delimited area on all it's border (es: http://squirrelmail.org/images/shots/nodeco/messagelist.jpg 

* Make the tip list table/grid to show them in alternate line with colour frame white/greyed

* Increase size of the icons

* Add a small text title above the icon explaining the meaning of the column/action

* Make clicking of the icons a "sort by" actions (sort by day to expiry, sort by date, sorty by read/unread, sort by file-numbers, etc)

* Make each preview fields to be in it's own "column" with title:FieldName and content:FieldChoice

**Comment by evilaliv3** [comment]
@fpietrosanti:

1. can you explain better the idea?
2. i'm working on it; it's no simply possible to apply the bootatrap striped class as it seems to be in conflict with the selected lines css.
3. already done
4. we can't. the space need to be limited as much as possible and for stupid columns like "Files", "Comments" "Messages" we need to save space simply using a clear icon. so i consider icon + popover the best solution here; what do you think?
5. already done; was already writtend and the screenshots show that. read with care before commenting :)
6. not possible at all for a lot of reasons at this stage; @fpietrosanti. each context is expected to have different fields so we need a context selector to implement what you are saying and this would complicate a lot the interface

**Comment by vecna** [comment]
is also true, that context are few, and context can be display as different section.

context 1
tip about context 1

context 2
tip about context 2

and some property can be present or not based on the context .

**Comment by evilaliv3** [comment]
right anyway let's postpone this for now and let's consider this ticket only for its topic. i will close this by today when finished fixing the backend implementation (that was not working at all) and the unit tests.

then we will open some ticket for the enrighment that you proposed but that are related to enrighment of tip list / tip page in general.

**Comment by fpietrosanti** [comment]
Lovely, left column could be used, like a webmail show a list of Folder, to display a list of "context" that once clicked, do provide a visualization of the TipList only for that context (Useful for multi-context scenarios we're moving on).

**Comment by evilaliv3** [comment]
i agree but i i do not find that we should waste a column for this right now. as you suggested we should allow user to define short names for context/receivers/fields to  be used in such this visualizations.

anyway stop using this ticket takinking about whatever comes to your mind and eventually open new one.
next out of topic comments will be from now on deleted silently :)

**Comment by evilaliv3** [comment]
i've enrighed the table by adding the striped layout.

all unittests are now in place and the feature can be considered complete.

let's open eventually specific tickets for specific enhancements.
