### ISSUE TITLE
GlobaLeaks must block incoming connection from Tor2web gateways using http in clear

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1289]
This ticket is to block incoming connection from Tor2web gateways using http in clear.

Currently for example onion.city is using http in clear text and globaleaks must refuse connections coming from such nodes in clear text.

With the new change to the X-Tor2web header content, making it possible to match if it's HTTP or HTTPS, it should be doable to block those access automatically.
##

**Comment by evilaliv3** [comment]
@fpietrosanti i agree on the feature but as rightly suggested by virgil this information should not be driven by the X-Tor2web header but from the x-forward-proto header that is the "de facto" standard for this thing.

i've already implemented it in Tor2web and that header is passing "http" or "https" depending on the protocol used by the user when accessing Tor2web server.

**Comment by evilaliv3** [comment]
what do you think is the best to do? simply truncate the connection or simply negate accepting submissions? 

i'm not confident that the second option would be ok because if we do not truncate the connection and we simply  bass in http the information to the client to not perform the submission, anyhow a malicious attacker would be able to impersonate a mitm and make the user continue to do actions on the node eventually performing a submission intercepted by the attacker. so i think that on such a condition the only viable solution is to totally avoid interacting with the user, eventually redirecting to the https.

obviously iif the proxy allows only http redirectin to https would result in a failure but i do not think any other solution would be ok.

**Comment by fpietrosanti** [comment]
I'd just block and provide an error message being an uncommon and unusual situation to run tor2web in "http" in clear tet

**Comment by vecna** [comment]
ok so X-Tor2web has to be extended with the security level ? maybe, also some details about the security level of the SSL connection can be part of the header (version protocol, algorithm used), so if something is considered not strong enough, can be considered like unprotected connection ? 

I will consider, as "remediation", that only passive operation can be permitted and not submission (like nodes where confidential submission are not permitted, but with a different error message)

**Comment by evilaliv3** [comment]
i think nothing should allowed and i francly do not see any contromeasure aside of truncating the connecion.

let me clarify and then discuss my two point:
1) if the user is arriving via http the attacked is completely in chance to fuck him; if we provide something  like simply the the public API we would make completely simple for an attacker to mangle the variable that the client use to prevent submissions and will make the user do it aside of the fact that we wont accept it. so not providing nothing at all would at least force the attacker only in possibility to create a complete rogue instance but not abusing of our.
2) seriously tor2web should detect this, log it and report to the admin of such a condition.

**Comment by vecna** [comment]
@evilaliv3 about point 2, we are speaking of a "rogue"-like T2W, that permit http. if they had modify Hermes's software... we can't do anything.

and the same as point 1, if the mitm is active, the mitm will answer in behalf of us, with an, API when we close the connection.

**Comment by evilaliv3** [comment]
related to: https://github.com/globaleaks/GlobaLeaks/issues/1140

**Comment by evilaliv3** [comment]
Closing as Tor2web is no longer used within the project.
