### ISSUE TITLE
Evaluate how to implement tip preview in end2end encryption workflow

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1296]
We should valuate how to implement tip preview in end2end encryption workflow.

currently preview data is extracted from the submission by the backend at submission time.

in order to be able to offer such a feature inside the end2end workdflow probably this operation should be moved to the glclient that should compose the preview data and encrypt it independently from the complete submissions (that will contain that data anyhow).

the same will be probably to be done to stats data so that we will have a little duplication but this appear to me the only possibility.

\cc @fpietrosanti @vecna @hellais 
##

**Comment by fpietrosanti** [comment]
@evilaliv3 While advanced statistics related to the answers of submission fields do require the fields of structured answers to be saved unencrypted, we should approach preview in a different, more complex way.
It make sense to save them in a separate object at submission time from whislteblowers.

But from receivers side we may have a serious performance issue having a list of 50 Tips and have 50 PGP decrypt operations to show them with the preview, introducing a high delay.

That's something that must be measured (how much time does it take to visualize a tip list with with 50 preview objects to be decrypted on-the-fly) to understand if it's "a viable way" or if we need to implement specific data/crypto/procedural optimization.

**Comment by vecna** [comment]
practically speaking, every fields in the submission has to be marked as "reserved" or not. 
if something is NOT marked as reserved, can be part of the preview, statistics, open data. 

Based on that, the user decision became "say here if the answer will be something that can lead to whistleblower identification or not".

lucky for us, the statistics/open data cannot be done over open text fields. only in multiselect, checkbox, menù. This kind of closed selection data, are also the less sensitive by definition (for example: you don't report the exact import of a wire-transfer, but some threshold) 

Based on this selection, submission will contain two fields: receiver encrypted (the sensitive) and node encrypted (not sensitive).

we've to encrypt to node because we don't want that a network observer can, anyway, get some knowledge about the submission *. When Tip is stored, Node extract stats, and act as a MITM for the receivers, encrypting for their keys. 


* also the "fake traffic generation" has to be kept in account. soon or later

**Comment by evilaliv3** [comment]
exactly also with @fpietrosanti we ended with the same decision of using a
single boolean per field to mark if the field is critical or not.

but for what related to the submission we have a different thinking:
1) sumission will be archived as a whole like now context copy +
keys-values (and will be all encrypted or plaintext depending if e2e is in
place or not)
2) preview will be a copy of the key-values inside the submission (and will
be all encrypted or plaintext depending if e2e is in place or not)
3) only closed questions answers, whose confidentiality is not critical and
stored in a table internaltip, field_id, value_id so that this data would
be available to other modules

**Comment by evilaliv3** [comment]
Closing as deprecated by current encryption screma.
