### ISSUE TITLE
The GlobaLeaks loading confort loader does not seems centered on Tor Browser

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1298]
The GlobaLeaks loading confort loader does not seems centered on Tor Browser

![screen shot 2015-06-14 at 5 16 17 pm](https://cloud.githubusercontent.com/assets/770363/8149118/c7d93f6c-12b9-11e5-9d7f-950a809c10c2.png)

**Comment by evilaliv3** [comment]
i see, let me dig into it as i'm interested to fix few things of the loader.

it appears to me that it has few regressions:
- font is changing multiple times while loading
- and on your case it's not centered.

**Comment by evilaliv3** [comment]
Okay with previous commit i've applied a different css that would behave well;

in addition the inline css now explicit the font-style, the fontsize, and the color of the text is now a gray like the one of the loader so that all should be more smooth.

![screenshot from 2015-06-14 19 15 13](https://cloud.githubusercontent.com/assets/217034/8149615/10810884-12ca-11e5-82e9-a88125cf3ad5.png)
