### ISSUE TITLE
If a file being upload have a too big file-size the error messages should be given immediately

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1306]
If a file being upload have a too big file-size the error messages should be given immediately.

Currently the user is displayed a File Upload box on the right of the interface, with the indication of failure as shown:
![screen shot 2015-06-21 at 11 55 32 pm](https://cloud.githubusercontent.com/assets/770363/8273508/3a49f3fe-1871-11e5-956c-74f6725eb6f9.png)

This ticket is to prevent the "file upload" to appear with an error (that cannot be dismissed), but giving the user an error in the same visual focus of the "Add File" button.
##

**Comment by evilaliv3** [comment]
@fpietrosanti: the button (when configured with multi) would allow the user to load multiple file at once, so if we put a space for a single file upload button it would result not clear to which file the error refers.

**Comment by evilaliv3** [comment]
there are various improvals to be evaluated but what you are suggesting move the problem to one point to an other. there are a lot of global (per button) features that we could implement but they all will create chaos in the user given the fact that when the form would host multiple button, the user will have multiple global variables (one for each button).

e.g. i'm evaluating the usage of various capabilities of the library in order to improve the file uploader:

1. sizeUploaded() Returns the total size uploaded of all files in bytes.
2. timeRemaining() Returns remaining time to upload all files in seconds. Accuracy is based on average speed. If speed is zero, time remaining will be equal to positive infinity
3 .progress() Returns a float between 0 and 1 indicating the current upload progress of all files.

1, 2, 3 it's a signele per button variable.

so for now i'm concentrating my attention on improving the per file status in order to make it more clear.
e.g. the first feature to be implemented is the per file loader with a slide bar.

**Comment by fpietrosanti** [comment]
@evilaliv3 Given that the "upload action" from the end-user is a single action (even if he's trying to upload multiple files), i'd suggest to have the "Add file" action to fail immediately (that means failing for all files that the user is trying to upload), informing the user with a pop-up or foreground div, informing him that he's trying to upload more data than what he's allowed to, displaying the limit in file size and total amount allowed, asking to try again. 

That way we'll get the advantage that:
- There will never be "multiple file upload actions" where "some file get uploaded but some file doesn't get uploaded because of size limit" 
- The size limit error is properly displayed with an informative box

**Comment by evilaliv3** [comment]
can you sketch it out with paint? cause i've a lot of questions that i'm not able to solve. maybe you can.

1) if i load only one file ok
2) if i load multiple files (e.g. 5) and some (e.g. 3) fails should i show 3 repeated errors under the button specifyinh for each line the issue, the filename? cause these would be the relevat information to be shown in such a case. we cant' prevent all the 5 cause 3 are failing for example (i'm techniocally not able to do that)

**Comment by fpietrosanti** [comment]
@evilaliv3 Given that the "upload action" from the end-user is a single action (even if he's trying to upload multiple files), i'd suggest to have the "Add file" action to fail immediately (that means failing for all files that the user is trying to upload), informing the user with a pop-up or foreground div, informing him that he's trying to upload more data than what he's allowed to, displaying the limit in file size and total amount allowed, asking to try again. 

That way we'll get the advantage that:
- The size limit error is properly displayed with an informative box
- There will never be "multiple file upload actions" where "some file get uploaded but some file doesn't get uploaded because of size limit"

**Comment by evilaliv3** [comment]
By the current implementation the indicators of the file upload are near to the file upload so that the user see the error next to the action that triggered the error.

so it does exactly what this ticket was opened for!

**Comment by fpietrosanti** [comment]
Is the check entirely done client-side with client-side detection and failure?

**Comment by evilaliv3** [comment]
yes Sir!
