### ISSUE TITLE
Tor HS directory changed permission/owner during upgrade

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1328]
I don't know what happened, but after upgrade my HS was not working and:

Jul 14 01:41:19.674 [notice] Read configuration file "/etc/tor/torrc".
Jul 14 01:41:19.678 [warn] Directory /var/globaleaks/torhs/ cannot be read: Permission denied

I tried making debian-tor owner of the directory but still a problem since "Too permissive". Solution:

I let Tor create /var/lib/tor/hidden_service and update private_key and hostname file contents with the ones I had previously at /var/globaleaks/torhs and stated in /etc/tor/torrc to read Globaleaks port in /var/lib/tor/hidden_service

It happened before when I was updating the software with @vecna some months ago - I think we never reported.
##

**Comment by fpietrosanti** [comment]
@infosquatter 
a) did it happened again? 
b) did it happened when upgrading globaleaks or when upgrading the operating system at all?

**Comment by evilaliv3** [comment]
excatly @infosquatter this happened also to @drwhax while updating an ubuntu 12.04 to a 13.10 or something.

i'm still missing what the issue is and current gl-fix-permissions script runned at each reboot should always fix it. @vecna / @fpietrosanti are you able to understand why it wouldnt fix permissions over permissions changed by a distro upgrade?

current gl-fix-permissions script is:

```
#!/bin/sh

# user permission check
if [ ! $(id -u) = 0 ]; then
    echo "Error: gl-fix-permissions script must be runned by root"
    exit 1
fi

[ -d /var/globaleaks ] ||  mkdir -p /var/globaleaks
chown globaleaks:debian-tor /var/globaleaks
chmod 750 /var/globaleaks

[ -d /var/globaleaks/torhs ] || mkdir -p /var/globaleaks/torhs/
chown debian-tor:debian-tor /var/globaleaks/torhs/
chmod 700 /var/globaleaks/torhs

[ -d /var/run/globaleaks ] || mkdir -p /var/run/globaleaks
chown globaleaks:globaleaks /var/run/globaleaks
chmod 750 /var/run/globaleaks

[ -d /dev/shm/globaleaks ] || mkdir -p /dev/shm/globaleaks
chown globaleaks:globaleaks /dev/shm/globaleaks
chmod 750 /dev/shm/globaleaks
```

to this:

**Comment by fpietrosanti** [comment]
@evilaliv3 I'd suggest to:
- switch to /bin/bash
- manually set PATH
- modularize the scripts with functions in blocks that fix each directory
- include error checking for each function
- include an output while executing each function

Then we would have a robust script and we could detect when  / in which condition it's not running properly

**Comment by evilaliv3** [comment]
i agree quite for all but i always not understand why would you need bash.

in relation to PATH what do you mean?

**Comment by fpietrosanti** [comment]
@evilaliv3 
* bash'ism is more complete an resilient than sh'ism
* i mean setting PATH=/usr/bin;/bin;/sbin/usr/sbin to ensure that once executed the script will be 100% sure to find in the path the command that's going to call (chmod/mkdir/etc)

**Comment by evilaliv3** [comment]
1. make ma an example and would be ok with that.
2. find me and example of program or guidelines that suggest that raw thing and i will try to test it.

**Comment by fpietrosanti** [comment]
1. On unix /bin/sh can be a different shell depending on the unix system, so /bin/bash gives better compatibility because you are sure of what you are executing. On Low-end system /bin/sh is busybox, on some system is Dash, on some system is pdksh. 

2. If you don't set statically the PATH like any init script does, you cannot be *sure* that PATH is set

**Comment by evilaliv3** [comment]
1. finally a good and enxaustive argumentation man! how long! ok.
2. so what script whould have written what and where? can you be precise and not cryptic as for 1. ?

**Comment by fpietrosanti** [comment]
2. PATH=/sbin:/usr/sbin:/bin:/usr/bin

**Comment by evilaliv3** [comment]
WHERE DIOBONO? :P

**Comment by fpietrosanti** [comment]
In the script that does the check. Diobono? :P 
<img width="677" alt="screen shot 2015-07-14 at 8 13 29 pm" src="https://cloud.githubusercontent.com/assets/770363/8680901/b0c56090-2a64-11e5-97c3-b683f24c3792.png">

**Comment by evilaliv3** [comment]
should all bash scriptof globaleaks have such a header?
what should it do in your opinion apart of PATH=?

**Comment by infosquatter** [comment]
@fpietrosanti 
a. Yes, it happened again (yesterday, see log details)
b.  Both. "apt-get upgrade".

**Comment by evilaliv3** [comment]
@infosquatter / @drwhax as you both if im not wrong got this issue i kindly ask you to report what was the Ubuntu version and what kind of upgrade you did (12.04 to 13.04 or something?).
i'm requiring this cause i'm really not able to not reproduce the issue on any of the adopter setups the we manage.

**Comment by DrWhax** [comment]
I had this issue but it turned out to be an AppArmor profile problem rather then a permission error. But AppArmor *did* create the permission error.

@infosquatter try to enable debug in /var/default/globaleaks. Try to start Globaleaks and read logs from /var/globaleaks/logs/globaleaks.log and see if there is any error and paste the full output in @evilaliv3's e-mail box. 

This will help debugging this issue a great deal easier. Don't forget to turn off debugging when going to production mode again ;-)

**Comment by evilaliv3** [comment]
right, i was forgetting that on the case of @DrWhax the problem was simply for apparmor.

**Comment by fpietrosanti** [comment]
@DrWhax With the upcoming Release of Tor 0.2.7 on 30th September, we'll be able to integrate the Loading of Tor Hidden Service descriptor/key trough the Tor Control Port, by keeping everything into the GlobaLeaks Database, without touching the Tor Apparmor profile anymore

**Comment by infosquatter** [comment]
I did not upgrade de OS. I just did a general upgrade of the packages.
The machine is still running Ubuntu 12.04.

Giovanni Pellerano:

**Comment by evilaliv3** [comment]
no reproducible, moving the ticket out of milestone for now.

**Comment by evilaliv3** [comment]
The issue as described in ticket #1847 is that recently (since one year) Tor started changing permissions of the tor_key file and of the hostname file.

There is currently not any solution;

@fpietrosanti: i will experiment resetting the permissions (chown/chmod) after the restart of Tor but this could eventually cause failures to the tor deamon.

the only good solution would be to implement the Tor hidden service configuration via the the control port and by means of the Tor Control Port.

I've already worked on this topic and we can implement this in the next database migration saving the Tor key and the hidden service name inside the database.

**Comment by fpietrosanti** [comment]
old, fixed, not-reproducible
