### ISSUE TITLE
Tor HS changed after system reboot

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1329]
After having issues adding a PGP public key to a receiver ( https://github.com/globaleaks/GlobaLeaks/issues/1327 ), it was suggested by @evilaliv3 to reboot the system.

Rebooting the system caused /var/globaleaks/torhs/privatekey and /var/globaleaks/torhs/hostname to be replaced with brand new ones. Old content was lost, thus permanently changing the Tor HS url of the Globaleaks node.

**Comment by evilaliv3** [comment]
@infosquatter: all this things that you are reporting are so strange.

we still miss from you the important details that would help investigating: have you upgraded the ubuntuversion? (e.g. passing from a 12.04 to a 13.04?). there is no code in globaleaks or tor that would have changed such permissions so i really can't understand how this could be happened tyo you.

this issue is related to https://github.com/globaleaks/GlobaLeaks/issues/1328

**Comment by infosquatter** [comment]
This happened a different machine than
https://github.com/globaleaks/GlobaLeaks/issues/1328 , but it is the
same thing: no OS upgrade, just general packages upgrade, still running
Ubuntu 12.04.

Giovanni Pellerano:

**Comment by evilaliv3** [comment]
not reproducible.

it appear more to an admin error, closing the ticket for now.
