### ISSUE TITLE
update globaleaks can trigger a bash error 

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1344]
upgrading **Greenwald in a box**:

apt-get upgrade globaleaks

     * Starting GlobaLeaks daemon globaleaks                                                                       
     /etc/init.d/globaleaks: line 248: [: : integer expression expected
    Serving GLClient from /usr/share/globaleaks/glclient
    Database version detected: 20

**Comment by evilaliv3** [comment]
i know this issue.

 this is due to the fact that you have updated the globaleaks but you have kept the old /etc/default/globaleaks, so the issue is more a human error than a software one.

by the way the solution is the following.
the software should keep a copy of the current /etc/default/globaleaks in /usr/share/globaleks/something
this way the init script should load first /usr/shar/globaleaks/something and then /etc/default/globaleaks over it in override.

**Comment by vecna** [comment]
and, can you please tell me (if is not documented) why in the same box, one of the old bug is comeback (receiver are not selected by URL) ? I guess is because of the apt sources mistake. you can check it out at https://experiment.globaleaks.org/#/submission?lang=it&receivers=%5B%221684c79e-fb9a-4d8f-b2c0-d36cb393d248%22%5D (Claudio - TEST is selected but you can't complete the submission with only the URL selection).

**Comment by evilaliv3** [comment]
it seems a regression bug. i will dig into it and it will be released by  tomorrow night.

working here in rome we few mixed conditions that causes a similar bug.

**Comment by evilaliv3** [comment]
@vecna: the regression bug described by you above should be fixed by :https://github.com/globaleaks/GlobaLeaks/commit/e7a1bacf8831544cc36eb5e02e9f3990cb64c301

by tomorrow morning i will push out a package. we are finalizing few other things.

**Comment by evilaliv3** [comment]
@vecna: fixed and updated greenwald in a box

**Comment by vecna** [comment]
Thanks, so is not a lacking of update of /etc/apt.d/globaleaks.d ?

**Comment by evilaliv3** [comment]
the two are different, unrelated and with a totally different problem context but i like the approach of unifying all the tickets in one :)
