### ISSUE TITLE
Make list of receivers on the Tip interface of the Whistleblower visibile only if Receivers selection is visible

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1347]
This ticket is to make the list of receivers on the Tip interface of the Whistleblower visibile only if Receivers selection is enabled/visibile visible.

The Whistleblower, if didn't selected a receiver, shall not require to view the list of Receivers and their access data.

**Comment by vecna** [comment]
I see the point, but is troublesome for one reason and bad for another.

**troublesome**: if "comments" are optional based on the number of receiver, and "receiver list" became optional based on the selection feature, we start to get a messy interface, much more than now. or at least, has to be redesigned because otherwise the testing and the look will be really random.

**bad**: is intended as transparency communication for whistleblower (number of time they have accessed). this is the value of such interface, if we are going to remove the list, this communication has to remain.

**Comment by evilaliv3** [comment]
@vecna if receivers are hidden maybe we can implement an additional interface to show cumulative counters of the accesses by the receivers and so on.

the issue is in general that there are some adopters that would like to have that info disabled. while i'm with you i can understand some of the reasons; my idea is anyway support transparency also via other methods, e.g. making clear to the whistleblower if the other side has seen is message, what is the status of the analysis, etc. with this and other indicators even if the receivers and their accesses are not verbosely shown as now, the transparency features you and i support will remain part of the platform.
