### ISSUE TITLE
Improve UX while writing text fields with highlighting of boundaries

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1351]
This ticket is to improve UX while writing text fields with highlighting of boundaries of the text field.

Example below from autoscout24.it contact form http://ww3.autoscout24.it/classified/273828704?pr=0&fromparkdeck=1:
Unselected:
<img width="385" alt="screen shot 2015-08-07 at 11 56 55 am" src="https://cloud.githubusercontent.com/assets/770363/9133375/743c65ac-3cfb-11e5-9d93-f542e6c1ad16.png">

Selected:
<img width="403" alt="screen shot 2015-08-07 at 11 54 32 am" src="https://cloud.githubusercontent.com/assets/770363/9133346/471c9e52-3cfb-11e5-88ea-aef3886db235.png">

**Comment by evilaliv3** [comment]
DB support added in commit: https://github.com/globaleaks/GlobaLeaks/commit/614ae061d0d3a29f2d2e2dda9a1760011c5e6dbe

**Comment by evilaliv3** [comment]
Done!

![screenshot from 2015-08-31 16 13 54](https://cloud.githubusercontent.com/assets/217034/9580793/d504d528-4ffb-11e5-944f-6c690c058fb9.png)
![screenshot from 2015-08-31 16 14 10](https://cloud.githubusercontent.com/assets/217034/9580795/d9c2aeb4-4ffb-11e5-8a6e-0cee25c555f3.png)
![screenshot from 2015-08-31 16 14 30](https://cloud.githubusercontent.com/assets/217034/9580801/de3d5368-4ffb-11e5-9b51-31bded2b2a93.png)
![screenshot from 2015-08-31 16 14 51](https://cloud.githubusercontent.com/assets/217034/9580804/e1597d38-4ffb-11e5-8b0f-e01a15be5f49.png)
![screenshot from 2015-08-31 16 15 09](https://cloud.githubusercontent.com/assets/217034/9580805/e55405c0-4ffb-11e5-9a91-8983f8c9ec16.png)

**Comment by evilaliv3** [comment]
done!

here i describe what implement and the UX decision i've taken:
1) the minimum chars len error is handled only  if I) the field is required in this case it is shown immediatly II) also if it is not required but the user has started typing; before the user starts typing it is hidden.
2) the maximum characters limit is shown only if the user has at least exceded the minimum amount of characters so that there is always only a message shown to the user; i.e. he will have an indicator that act has an error if he has to write less and as an indicator if he will have reached the minimum amount of characters requeted.

given 1) and 2) the interface should be now clean with not so much errors but different indicators show and always only one indicator shown to not bother the user.
