### ISSUE TITLE
Update mail notification template

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1353]
Due to the fact that languages need to be updated, the email template still contains this information (that now is not true anymore):

    Please do not forward or share this email; each tip-off allows a limited number of accesses and        
    downloads before being permanently destroyed and nobody (not even the server administrator) can     
    recover an expired or deleted tip-off.

**Comment by fpietrosanti** [comment]
add bug label.

**Comment by evilaliv3** [comment]
In the meantime i'm going to simply  remove this text from the mail template.

Frankly i'm not for adding any replacemente as this is an obvious statement present since the start while the first statement clarify well that the material should be managed with care: https://github.com/globaleaks/GlobaLeaks/blob/master/client/app/data/txt/tip_mail_template.txt

what do you think is missing?

**Comment by vecna** [comment]
there is any initiative using the link (receiver side) via Tor2Web ? I don't think so

**Comment by evilaliv3** [comment]
quite all the more Public Agency like: e.g. ALAC, Anac, ASL Brescia, etc.
anyhow a real initiative in the end would configure the templates he use; it's simply a matter of communicating well such a feature and making the interface for configuring it more simple of what is not.

let's keep the tor2web link in there for now so that it proves to the adopter such a possibility.
