### ISSUE TITLE
Support Unpublished Submission URLs?

### ISSUE THREAD

**Issue by t1msammut** [globaleaks/GlobaLeaks#1432]
Would it be possible to have an unpublished submission URL on a per-context basis? 

Our installation lists available contexts on the initial submission page. It would be nice to support submission to a context/group of receivers that is not listed on the general submission page but that is reachable only via direct-browsing to a URL. 

This would allow us to extend requests for information through our contacts, potentially for a limited time period, without exposing the submission process more generally.

**Comment by evilaliv3** [comment]
hi @t1msammut, this sound good to me.

i've only a question to ask.
right know globaleaks exposes all the data on how it behave in a public manner (via API) even when the UI is hiding some details.

From the point of view of your requirement are you requesting to hide the context simply from the UI or also from the REST API?

**Comment by t1msammut** [comment]
Hi, thank you for the quick reply. 

I don't really see this as a security feature since anyone with the URL could make a submission to the hidden context. Because of that, I think it is ok if the REST API exposes the context to REST clients.

This is more for convenience (on receiver side) and ease-of-use (on the submitter side).

**Comment by evilaliv3** [comment]
great so!

putting the changes required to the db on the developement branch right know! the feature will be ready even by the 24 on the  the current globaleaks stable.

any chance to get the [missing translations for the arabic](https://www.transifex.com/otf/globaleaks/language/ar/) so to be able to move the amety deoployment to current codebase? given that they have been updated since time by volunteers maybe a professionist review won't be bad at this stage.

\cc @fpietrosanti

**Comment by evilaliv3** [comment]
done!

in the next release there will be this option available in contexts:

```
Allow selection of this context through the context selector picker.
If disabled, submissions for this context will be allowed only accessing through direct link
```
