### ISSUE TITLE
Make footer text right-justified when RTL languages are used

### ISSUE THREAD

**Issue by t1msammut** [globaleaks/GlobaLeaks#1440]
The footer text is left justified when right-to-left languages like Arabic are used. If the browser is narrow enough to cause the text to appear on three lines, the third line is out of place under the logos and appears missing. 

The footer text should be right-justified for RTL languages and left-justified for LTR languages as text is in other parts of the tool.

Thanks!

**Comment by evilaliv3** [comment]
@t1msammut: sorry for the delay, all should be fixed now!

i've also took care that links in the footer are now swapped in the order, so that "Home" appear the top left in LTR and the top right in RTL.

![screenshot from 2016-01-13 14 27 11](https://cloud.githubusercontent.com/assets/217034/12295535/ea56a206-ba01-11e5-86b0-63b0f623b3b0.png)
