### ISSUE TITLE
Detect IE browser in compatibility mode and gives back a message about the need to disable it

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1480]
Detect IE browser in compatibility mode and gives back a message about the need to disable it

**Comment by fpietrosanti** [comment]
Way: https://gist.github.com/jasongaylord/5733469

**Comment by evilaliv3** [comment]
I found out that is not interesting simply detecting the compatibility mode as it is simply a support that is not bad that the browser has enabled.
The issue is simply that if the application does not specify his preferred order compatibility list the browser falls immediatly on the compatibility mode.

what he have to do in my opinion to fix this issue is to add the following meta-tage:
```
<meta http-equiv="X-UA-Compatible" content="IE=EDGE,11,10,9" />
```

this way we will clarify the browser that the app should use the maximumg IE version and eventually it will fall back on IE8 that is disabled and for IE8 we will provide the message indicating that the platform support only versions above IE8.
