### ISSUE TITLE
IE does not load logos uploaded as JPEG because GlobaLeaks service it as PNG

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1485]
It has been found that that IE does not load logos uploaded as JPEG because GlobaLeaks service it as PNG ("globaleaks_logo.png").

There are two way to handle this issue:
a) Prevent loading of Logos that are not PNG
b) Convert dynamically, into the browser using Canvas, the JPEG into PNG file and only after send it to the GlobaLeaks backend
http://stackoverflow.com/questions/6150289/how-to-convert-image-into-base64-string-using-javascript

We decided not to do any image conversion server side due to the fat/risky library required.

**Comment by evilaliv3** [comment]
Good analysisys @fpietrosanti  but i debugged the bug and i've now a clear idea and a solution:

the bug: the backend is answering with a wrong content type (png) when the file is a jpeg but called ".png"

the solution identified: simply serve the image as it is (png, jpeg, whatever) as base64 string inside the json answer as any content type along with it.
the operation that the server would need to do is to encode the file in base64 that is a safe conversion operation also suggested by pentesters (owasp italy guys) in order to make difficult for an user to load a possible attack vector providing a special base64 string.
the advantage that comes in addition to  solving the bug, being secure is also that would be also to not require canvas to be used.

**Comment by evilaliv3** [comment]
GlobaLeaks is now forcing the user to load only PNG images and in case other files  are loaded a proper error is shown to the user.

![screenshot from 2015-12-18 02 04 05](https://cloud.githubusercontent.com/assets/217034/11886564/ae6c67e8-a52b-11e5-8626-aba48133c103.png)
