### ISSUE TITLE
Missing "Description" field

### ISSUE THREAD

**Issue by danilort** [globaleaks/GlobaLeaks#1521]
After upgrading to version 2.60.120, on the home page, I do not see the "Description" field.
See the attachment.

Danilo 

[allegato1.pdf](https://github.com/globaleaks/GlobaLeaks/files/56591/allegato1.pdf)

**Comment by evilaliv3** [comment]
@danilort: it's intended by latest development that the text custoomable in the homepage is only one and it's the "Presentation" that is anyhow a multi line text.

Description is instead delegated to other usages that describe the node usage, to be exported in metadata and other places.

Do you find it useful this way or given a particular use case you prefer the old way?

**Comment by evilaliv3** [comment]
@danilort: after a short discussion with @fpietrosanti we decided to reput the string for now so it will be an other time visible since the release of today that would include also few of the bugfixing you were expecting.

we will evaluate later on to move the configuration to a separate page and enforce the use of such an information for meta-data uses only.
