### ISSUE TITLE
Whistleblower can't see the old submissions

### ISSUE THREAD

**Issue by danilort** [globaleaks/GlobaLeaks#1525]
After upgrading to version 2.60.121:
- the whistleblower can't see the old submissions (created using Globaleaks 2.60.120, or 2.60.119)
- the whistleblower can see the new submissions (created using Globaleaks 2.60.121)

See the attachment.
[allegato.pdf](https://github.com/globaleaks/GlobaLeaks/files/57816/allegato.pdf)

Ciao, Danilo

**Comment by evilaliv3** [comment]
Interesting bug @danilort; nobody reported it but lets see if i'm able to reproduce it.

There is no migration of the database between these releass; let me recheck and i will be back to you shortly.

**Comment by danilort** [comment]
globaleaks -v
GlobaLeaks Version: 2.60.121
GlobaLeaks DB version: 25

globaleaks -v
GlobaLeaks Version: 2.60.120
GlobaLeaks DB version: 24

**Comment by evilaliv3** [comment]
Bug verified and it affected the change from 2.60.120 to 2.60.121.

the package has been fetched only one time; given that you are still in staging @danilort is it ok to simplify the solution not handling to re-make the old tips functional for you? even not updating you are completely bug free since now.

**Comment by danilort** [comment]
Yes, my old TIP are not important.

**Comment by evilaliv3** [comment]
ok, thanks
