### ISSUE TITLE
Next step and previous step buttons should move the focus of the browser to the top of the page

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1530]
When there are 2 steps and WB click "next step" his focus goes on the first mandatory field, leading to a bad UX experience.

In sportelliriemergo questionnaire structure, the only mandatory field is at the end of the 2nd step, it means that after clicking "next step" (from the 1st step), the focus of the WB is at the end of the 2nd step (that's a long questionnare), so the whistleblower must "page-up" a couple of time in order to starts filling the 2nd step of the questionnaire from the bottom.

**Comment by evilaliv3** [comment]
@fpietrosanti you are wrongly diagnosing the issue here.

there is no logic at all that points the user at the level of a mandatory field.
what happens is the following: the next step button simply switch the step without taking the user to the top of the page so you are fooled in this behavior by the application while instead you are still at the scroll level you where when you clicked the next step button.
