### ISSUE TITLE
Allow to click submission button only if the user has performed has filed the form with something (i.e. form is in dirty state)

### ISSUE THREAD

**Issue by calamarim** [globaleaks/GlobaLeaks#1544]
You can complete the submission process without filling any field  in current Demo Instance
http://po47k4agopleagki.onion

**Comment by evilaliv3** [comment]
@calamarim, also if you feel this as a bug this is perfectly ok.

if you, as admin, want to avoid this you have simply to mark some questions as mandatory(required) and it would provide empty submissions to be sent.

anyhow i got your point and i will make the form submit button to be activated is dirty (not pristine) that means that at least the user has filed something.

**Comment by evilaliv3** [comment]
done!

what happens now is the following (supposing no required fields are configured)
1. the submit button remains disabled until the user fills at least a field of the questionnaire;
2. starting from the moment at which the user fills the form the button is enabled and it will remain enabled also if the user will clean the whole form; this is due to the dirty state/pristine state are not resetted by angular but i would not think this an issue.
