### ISSUE TITLE
the message saying that is better to use Tor Browser appears when using it

### ISSUE THREAD

**Issue by calamarim** [globaleaks/GlobaLeaks#1545]
The below message appears also using Tor Browser last revision

Iceweasel, Debian Jessie

"It appears that you are using Tor. To better protect your identity, you must use the Tor Browser.
The Tor Browser includes various privacy and security enhancements not present in other browsers"

**Comment by evilaliv3** [comment]
You are right marco. The original text wrongly replaced in https://github.com/globaleaks/GlobaLeaks/commit/22774e5a51eb0821a35665469ff3773a5d6f004d was " It appears that you are using Tor. To better protect your identity, be sure that you are using the Tor Browser."

@fpietrosanti i'm going to immediately recover it as the text was replaced due to a wrong integration of some suggestions; thanks to transifex translation memory we also will recover old translations.
