### ISSUE TITLE
Change naming for access control of users "Tor2web -> HTTPS"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1549]
Actually when a user want to enable connection of the different users to GlobaLeaks between Tor and Tor2web have to goes in the Tor2web section.

Tor2web doesn't mean anything for the administrator and it's common to refer to it as HTTPS.

This ticket is to change the name of Tor2web in HTTPS in the section where it's possible to enable different users (public, whislteblower, admin, receiver, custodian) access.

That way it's easier to explain "Tor and/or HTTPS" rather than having to explain what Tor2web is.

**Comment by evilaliv3** [comment]
@fpietrosanti: i'm wondering if it is valuable to simplify th HTTPS restrictions only to the whistleblower and let them always enabled for an admin/receiver.

what is your thinking?

\cc @vecna

**Comment by fpietrosanti** [comment]
Mmmm yes, having a default restriction for Tor Onion Services only for Whistleblower but leaving it reachable/enabled for Receiver/Admin make a lot of sense / flexibility!

P.s. We shall also change "Tor hidden services" to "Tor Onion Services" that's the new official naming convention

**Comment by evilaliv3** [comment]
@fpietrosanti i was not simply about to put the default to enable for admin/receivers but to remove also the possibility to prevent that reachability but ok for now let's simply open all except whistleblowing by default.

**Comment by evilaliv3** [comment]
@fpietrosanti in addition for what relates changing hidden service to onion service the tor project seems to miss any official announcement an all official websites still use the hidden service naming so i would suggest to not change it for now.

since time i've seen only informal discussions about this, and one time a newsletter announcing this as possibility (25th february 2015) we should suggest to fix almost these:
https://www.torproject.org/docs/hidden-services.html.en
https://www.torproject.org/docs/tor-hidden-service.html.en
https://en.wikipedia.org/wiki/List_of_Tor_hidden_services

**Comment by fpietrosanti** [comment]
@evilaliv3 The naming is now "Onion Services" and those will be advised for uses, more than for the "location anonymity" for it's independent "end-to-end encryption" and "ddos resiliency" features. 
Roger, George and Douglet at the #32c3 talk on Onion Services, the strategy to implement 1-hop transport, the load balancing to support wide deployment of it, where emphasizing this:
https://media.ccc.de/v/32c3-7322-tor_onion_services_more_useful_than_you_think
https://www.youtube.com/watch?v=oh9D2r-ck40
