### ISSUE TITLE
Alcuni problemi con la versione corrente

### ISSUE THREAD

**Issue by giamaio** [globaleaks/GlobaLeaks#1558]
Salve
Abbiamo appena installato sui nostri server la versione nuova di Globaleaks 

Riscontriamo una serie di problemi
1)	Non riusciamo a chiudere le segnalazioni
Una volta definiti quali sono i campi obbligatori e non, all’interno della configurazione del contesto, se cerchiamo di effettuare una segnalazione alla fine della procedura, rispettando l’obbligatorietà dei campi, il tasto invia non è accessibile
2)	 All’interno di configurazione del questionario, nel settore “Modelli di domanda configurati” – “tipo;gruppo di domande Vuoi fornire le tue informazioni identificative?”  manca la traduzione in italiano per genere maschile e femminile.
3)	 Il tasto esporta non funziona su chrome/firefox/torbrowser , stranamente sì su android. 
4)	Anche esportando il file json ( ed identificando il settore dove inserire la traduzione), non esiste un modo per reimportare il file corretto
5)	Non esistono howto o wiki della nuova versione online

ho, tra l'altro appena effettuato la proceudr di aggiornamento al changelog di oggi

 Changes in version 2.60.133 - 2016-01-14

Sperando che le cose vengano risolte al piu’ presto porgo i miei più……

**Comment by evilaliv3** [comment]
thanks you for your valuable feedback @giamaio 

after the reception of your mail we already started investigating the issues reported in order to provide you a fast response; we will be back to you shortly in order to properly fix your setup.

In the meantime:

For what relates to the issue 1) would you please provide more information on the browser/version used and eventually identify if some error is logged in the browser javascript console? This would be useful for us reproduce the possible bug.

Issues 2, 3 and 4 instead are all related to some features that are considered experimental and are currently included in the latest release just to get a feedback by some users.
Given that we discovered few malfunctions we are now going to make them available onlly explicitly accepting to run an experimental feature. this way this experimental feature won't impact on the stability of the platform: https://github.com/globaleaks/GlobaLeaks/issues/1557

Thank you also for the feedback on the documentation; We are trying to do our best and we will try to update it shortly.

\cc @fpietrosanti

**Comment by giamaio** [comment]
The first issue seem solved... The other issues..... OK ... but now we have another malfunction... if you build a new step, than import from "add question from model", save step, save contest, than, reopen the contest,select the step newly created, delete it, save the contest, reopen a new step and reimport from "add question from model", globaleaks give "Input Format Invalid [Whistleblower identity field Already present]""

**Comment by evilaliv3** [comment]
Thanks you for reporting this also.
We will keep this in mind while stabilizing the whistleblower identity field that is exactly   the main experimental feature on which we are working nowadays.

i will be back to you on this ticket when the issues reported will be fixed.

**Comment by AlessioZa** [comment]
Salve,
Come avete risolto il punto 1? Io ho lo stesso problema. 

Grazie

**Comment by evilaliv3** [comment]
Issues reported in this ticket should be now all solved; In case something is still verified as buggy please open specific issues.
