### ISSUE TITLE
Provide a "Test Email Notification" button to enable debugging of non working notification

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1565]
It happen often that there's some issue in configuring email notifications that does not work properly with some kind of configuration set.

From the debugging perspective of the admin and the sysadmin user it's not easy to debug problems with notifications, especially because there's not way to stimulate immediate sending of email from globaleaks.

This ticket is to provide a "Test Email Notification" button to enable debugging of non working notification.

When a Test of sending an email notification with this button is done, the "log level" of the software shall be dynamically raised to "DEBUG" in order to facilitate the debugging of the problem.

**Comment by fpietrosanti** [comment]
It would be useful for debugging problem with notifications like #1541 and #1200

**Comment by IuliiSe** [comment]
+1
looking forward to see this implemented.

**Comment by NSkelsey** [comment]
I have written the backend support for this feature. @luliiSe, @fpietrosanti I am looking for feedback on what email configuration you would like to test. Currently I have dropped a button like so in the admin notification UI:

<img width="638" alt="screen shot 2016-03-28 at 10 06 24 am" src="https://cloud.githubusercontent.com/assets/1095794/14079758/ffd64a1c-f4cd-11e5-8a99-756caf83b733.png">

The only question it answers is: **Can I (the admin) send emails to myself using these settings?**
It could be extended to test things like: **Can the smtp server send the receiver's encrypted email?** or ** Does the exception notification email address receive emails?**

What do you want to see?

**Comment by evilaliv3** [comment]
well done with this feature! i'ts cool you are learning so fast how to build handlers and interfaces!

i would suggest that you first describe in the tickets what you would like to do so that we can guide you on the already identified need or few direction.

e.g. you identified that the feature test use three different commands like 'admin', 'err-notif' and 'receiver' but i think that @fpietrosanti designed this feature when we had only one administrator; now things are changed; @fpietrosanti would you please clarify what you had in mind and who would receive this test notification?

my comments are:
1) think that now there is not only one admin but you can get the email of the user that is currently logged in! :)
2) i would not put a "Call save before sending" simply eventually disable the button if the form is in dirty state so that it will be clear for the user that the buttoon save will be available only when the user will have saved (https://docs.angularjs.org/api/ng/type/form.FormController)

**Comment by fpietrosanti** [comment]
1. Regarding the Test-Admin email, it may just mean "This currently logged-in admin user account's configured email or, if email is not configured for whatever reason for that user, the system configured one"

2. Regarding "Call save before sending" info, can't we just trigger automatically a "Saving of settings and then, if saving didn't triggered an error, testing email sending" to leave end-user action simplified?

**Comment by NSkelsey** [comment]
1. Okay it will just use the current account. Wasn't sure if you wanted recipient and other tests done.

2. Yes that is what that sentence means (I will get rid of it because it is confusing) "_Call_ save before sending." is an imperative sentence which instructs the reader to do something. While "_Calls_ save before sending." is a declarative sentence that describes what the button does. :)

**Comment by evilaliv3** [comment]
Correcting what fpietrosanti written every user (and so each admin ) has
always an email configured

**Comment by NSkelsey** [comment]
Internationalized. . . . . Well Sort of!

<img width="715" alt="screen shot 2016-04-04 at 1 21 26 pm" src="https://cloud.githubusercontent.com/assets/1095794/14256700/38ed3cf8-fa68-11e5-83b5-d74ee08b6154.png">

**Comment by NSkelsey** [comment]
The code that implements this feature is in the development branch. It should make its way into the next release.
