### ISSUE TITLE
Notification Templates messed up.

### ISSUE THREAD

**Issue by IuliiSe** [globaleaks/GlobaLeaks#1568]
After update to ver. 2.60.135

The %ReceiverName% does not display the names. 
Instead, it just remains %ReceiverName%

Most of the translations in notification templates went missing.

**Comment by evilaliv3** [comment]
Dear Iulii

thanks as usual for your valuable feedback.


1) the fact that the variable  is missing will be investigated.
2) the fact that some templates are missing the traslation is sadly due to
the current of uk translations:
https://www.transifex.com/otf/globaleaks/language/uk/

during time the texts has been reviewed but the ukrainian translation has
been not maintained. if you are able to provide translations we will push
them in ass soon a they are ready.

**Comment by evilaliv3** [comment]
@IuliiSe the issues with %ReceiverName% not resolved is due to an error by the translator, cause the variable was recently been renamed %RecipientName% but this was mistaken. As soon as the new release will be available you will need to reset templates to the default and the variable will be resolved.

Anyway ping me if by the chance you have someone that can translate and i will fastly integrate them.
