### ISSUE TITLE
Custom notification settings not honoured by GL node

### ISSUE THREAD

**Issue by marceloomens** [globaleaks/GlobaLeaks#1571]
My Globaleaks node does not honour customisations of the email notification templates made at /#/admin/mail

The node also does not honour my language settings. Irrespective of any customisations I make, the emails sent out are the default (English language) notifications.

The node is currently on version 2.60.127 of the Globaleaks software

**Comment by evilaliv3** [comment]
@marceloomens 
it is possible that currenntly the emails are always sent using the default language of the node as a lot of refactoring happened on this part.

if you are managing to customize the templates of the email (that is something still not done quite from no one) take care that in the latest updates we are changing them cause a lot of texts have changed and the capabilities of the emails are growing so that we were forced to reset templates to default.

due to this please take notes of your templates in order to be ready to reinsert them when needed.

**Comment by marceloomens** [comment]
I know what you mean @evilaliv3 but since I've been working on the node I've never been able to sent out customised email notifications. I'll be sure to keep an eye on the templates every time we upgrade the node.

**Comment by evilaliv3** [comment]
i see i will recheck it and let you know.

**Comment by evilaliv3** [comment]
Issue not present in latests releases; closing the ticket.
