### ISSUE TITLE
Per submission notification opt-in/opt-out (per recipient)

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1577]
Various adopters reported me back that in their work they would really benefit of an opt-in/opt-out feature for the submission notification.

The typical use case of such a feature is the following:
- a submission arrive;
- the submission is checked by the recipient and the recipient not finding that much relevant decides to not delete the submission giving the whistleblower the chance to provide more data but decides to opt-out from the notifications in order to not be interrupted in its work by further discussions; the recipient will then check that submission manually logging on the platform and looking at the new material.
- the recipient would then like to be in possibility to opt-in if the submissions turns out to be relevant.

Feature request strictly related to: https://github.com/globaleaks/GlobaLeaks/issues/1576

\cc @NSkelsey @marceloomens @infosquatter @fpietrosanti

**Comment by NSkelsey** [comment]
I think it is wise to do this before #1576.

Additionally, would silencing notifications mean excluding the tip from the digest? -- I think not.

**Comment by evilaliv3** [comment]
I agree; this feature is more simple and would allow you to learn step by step.

In addition is a lot valuable for a user in order to not be disturbed in case of not useful communications arriving from a tip.

And i think as you that eventually the digest should include all that arrive, eventually discriminating the new-new material an the new material part of an opt out.

**Comment by evilaliv3** [comment]
IE11 is now succeding;

IE10 and IE9 not; i'm going to see which are the tests that are failing now.

**Comment by NSkelsey** [comment]
I created some UI to handle the display of UI notifications. The toggle button could be red, but I went with warning yellow because this is a more neutral setting.

**From the tip page this is the new resting interface:**

<img width="284" alt="screen shot 2016-03-28 at 1 05 07 pm" src="https://cloud.githubusercontent.com/assets/1095794/14083917/3126b1a2-f4e6-11e5-995e-9a7d6aaa44da.png">

**With the Silence notif button hovered:**

<img width="313" alt="screen shot 2016-03-28 at 1 05 13 pm" src="https://cloud.githubusercontent.com/assets/1095794/14083929/3c7092f8-f4e6-11e5-89c0-f3c8912f875d.png">

**With the Silence notif toggled on. (Meaning this tip will not generate notifications):**

<img width="293" alt="screen shot 2016-03-28 at 1 05 26 pm" src="https://cloud.githubusercontent.com/assets/1095794/14083941/5200069e-f4e6-11e5-8b00-b36094ccba8f.png">

**The toggle dialogue to Re-enable notifications:**

<img width="372" alt="screen shot 2016-03-28 at 1 05 31 pm" src="https://cloud.githubusercontent.com/assets/1095794/14083953/6599c550-f4e6-11e5-9dbc-bd89fa1d7440.png">

**Comment by evilaliv3** [comment]
Good to go, i would suggest the specific icon that bootstap uses for this reasons that is:

```glyphicon glyphicon-eye-open```

and:

```glyphicon glyphicon-eye-close```

what do you think?

**Comment by NSkelsey** [comment]
Yeah, I looked at those too. I can switch it. I was going off of [video game semantics](http://z5.ifrm.com/30005/144/0/p1228933/LoLSilence.jpg) for silence.

     ¯\_(ツ)_/¯

And just to check @15a7e0c `enable_notifications` is a per recipient setting for each tip. It is not something that lives in the tip's `context`.

**Comment by evilaliv3** [comment]
yep i'm thinking it have to live in the receivertip as it has to be per-receivertip in order to be per-receiver/per-user.

do you see something wrong in this?

**Comment by NSkelsey** [comment]
Nope. This is the right choice.

**Comment by NSkelsey** [comment]
Merged. Please leave comments here if you find problems with the feature.
