### ISSUE TITLE
Fix UI Problems in Receiver Tip List

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1613]
There are a few little errors that should go away in the Receiver's UI.

1. The spacing of columns crushes the column labels
2. There is a hanging bold tag that bolds a few rows.
3. The export button should find a new home when the select box is hidden
4. ~~Short title's should be pruned to less than 30 characters~~ _it behaves the way it is supposed to_

<img width="1190" alt="screen shot 2016-03-28 at 11 05 41 am" src="https://cloud.githubusercontent.com/assets/1095794/14080855/8e01eed4-f4d5-11e5-8d6d-0ce8b916eec3.png">

**Comment by evilaliv3** [comment]
i numbered you point so that we can discuss them.

**Comment by NSkelsey** [comment]
1) I suggest we use tooltips for the smaller columns instead of full labels.

2) I would rather have a new pill. Like so:
<img width="203" alt="screen shot 2016-03-28 at 5 43 31 pm" src="https://cloud.githubusercontent.com/assets/1095794/14091174/b04c06e6-f50c-11e5-9c26-a5b4399b1f39.png">

3) The export button can go in the barcode column before the file name, when there is no mass select box.

**Comment by evilaliv3** [comment]
1. that would not solve anyhow; in the future every field of the submission will be possibly exported in a column: e.g. column name, surname, gender etc; this will be important to make possible search and order over a question/answer; things in general that we will probably end in having the possibility of having 100 columns (were anyhow we could have long column titles like "Persons involved" that in Arabic could be 4 long words)

**Comment by evilaliv3** [comment]
ops, @NSkelsey; cleaning my comment where i did not answer to all your questions i removed your questions for error; your questions were:

```
1. I suggest we use tooltips for the smaller columns instead of full labels.
2. I would rather have a new pill
3. The export button can go in the barcode column before the file name, when there is no mass select box.
```

I would say:
1. that would not solve anyhow; in the future every field of the submission will be possibly exported in a column: e.g.  name, surname, gender etc; this will be important to make possible search and order over a question/answer; things in general that we will probably end in having the possibility of having 100 columns (were anyhow we could have long column titles like "Persons involved" that in Arabic could be 4 long words); what would you say?

2. i'm not in general on having explicit indicators but here the interface without an explicit indicator would have more benefits: I) if you look in every part of the line (suppose a big screen and even the indicator out of the viewport) you can see if that line is new or not; i agree like you that in this image there is an error; the bold is not applied to all elements of the lines (e.g. the icons); the bold is applied on some parts of all the lines, even the one that are not new (for the preview); i would suggest simply to fix this an it should work better also for you. what do you think?

**Comment by NSkelsey** [comment]
2. The reason I added 2. to the list was because I did not realize what the bold indicator meant. I am okay with keeping it the way it is.

3. Okay

**Comment by comradekingu** [comment]
Quick-fix, would "Sent" "Updated" and "Expires" limit it to one line?

If spanning across two lines, changing "Submission date" to "Date sent" should do the trick.

**Comment by evilaliv3** [comment]
Sent, Updated and Expires would solve the issue in english but not generically in a language where every wor takes two words :) 

anyhow also if that is not a real case, we should make possible that the table could expand with a scrollbar because due to the configuration we can have infinite columns and this is acceptable and have to work; now instead the table is compressed in a limited space.

**Comment by evilaliv3** [comment]
@NSkelsey i've addressed the various things you highlighted:

- the bold is used on new tips; old tips line avoid to use the bold at all.
- the table avoid wrapping using css ```white-space: nowrap```; in case the table is wider than the page a scrollbar happen; this way we will offer invinite culumns when each question will be unrolled in a column like in the dreams of mr @fpietrosanti 

![screenshot from 2016-04-04 00 51 44](https://cloud.githubusercontent.com/assets/217034/14235577/ceb3792a-fa02-11e5-868d-72ab74b38934.png)
![screenshot from 2016-04-04 00 52 01](https://cloud.githubusercontent.com/assets/217034/14235573/b9fd4704-fa02-11e5-8a76-7e98f0131484.png)
![screenshot from 2016-04-04 00 52 13](https://cloud.githubusercontent.com/assets/217034/14235574/be72a48c-fa02-11e5-9399-71df23041b88.png)

**Comment by NSkelsey** [comment]
Righteous double scrollbar action!

**Comment by evilaliv3** [comment]
what do you mean and how would you solve this?

**Comment by comradekingu** [comment]
He means the content in the window out of bounds for both vertical and horizontal space.

A quick fix would be to run with mouseover icons only.
Especially for "Files" "Comments" "Messages" and "Connection" as the column headline eats horizontal space.
![overview](https://cloud.githubusercontent.com/assets/13802408/14260431/c4fe87e0-faab-11e5-8796-a252ec634359.png)

Since "Submission date" and "Expiration date" no longer wrap across multiple lines, they are problematic in that they also use more space than is required.
![Uploading overview.png…]()

**Comment by evilaliv3** [comment]
i get the point that in english it will work better and i'm ok for doing that;

my coomment was to say that also if we will do it:
- it won't solve the problem for the other languages;
- the horizontal scrolling should be infinite anyhow because we will unroll all the questions/answers on a specific column.
