### ISSUE TITLE
Enable enforcing that a user is connecting with HTTPS, detecting that's not in HTTP

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1664]
This ticket is to enable enforcing that a user is connecting with HTTPS, detecting that's not in HTTP (unless is connecting to an address URL ending up with .onion).

This check should be disabled by default, but configurable (ie: if it's enable by default, it's a problem for the first setup, until the HTTPS is setup).

This check could improve client-side security w.t.r. to attacks when a whistleblowing website is with HSTS header's set, but at the first connection (going in HTTP in cleartext) there's a generic active MITM, downgrading the security to HTTP with an active-proxy.

This check can be bypassed by an active attacker with a "specific GLClient forging", but increase the attack sophistication required, requiring a GlobaLeaks-specific attack tool.

Once implemented, must be documented in GlobaLeaks Application Security Document https://docs.google.com/document/d/1SMSiAry7x5XY9nY8GAejJD75NWg7bp7M1PwXSiwy62U/pub

**Comment by evilaliv3** [comment]
@fpietrosanti: The sooner that we start implementing HTTPS this ticket should be taken into account and properly addressed.

We will have always (also when using Tor) enrich the design allowing HTTPS over Tor. This will be done automagically with Let'sencrypt+TorHS configuration and could be anticipated in the design of aself signed certificate just as first step of the lets encrypt implementation that will lead us to build the components anyhow required by letsencrypt.

The reasons and the detail of the failures are reported below:

Aside from security reasons it has also an important impact from the functional point of view.
The webcrypto API is not available in unsecure contexts so that Chrome+TorSocks on HTTP will always result in a failure.
This is the reason of at the base of the failure of https://github.com/globaleaks/GlobaLeaks/issues/1842 and  https://github.com/globaleaks/GlobaLeaks/issues/1843

If you notice the test performed by the adopter with a Safari + Tor proxy, accessing via onion, resulted in not fining the webcrypto API.

The same can be reproduced simpli accessing demo.globaleaks.org via IP on HTTP at: http://194.150.168.64:8082/#/ with a simple Chrome.

Links of reference:
- https://www.chromium.org/blink/webcrypto
- https://github.com/w3c/webcrypto/issues/28

Example of the failure when accessing via HTTP and accessing the webcrypto API:

![image](https://cloud.githubusercontent.com/assets/217034/21452046/593bba78-c904-11e6-9a30-220bbf1fd551.png)

\cc @NSkelsey

**Comment by fpietrosanti** [comment]
Tor + LetsEncrypt does not work because LetsEncrypt are domain validated certs, while the only way to achieve HTTPS over Tor Onion is to use Extended Validated certificates (non domain validated) Ref: https://twitter.com/fpietrosanti/status/676796552590008320

**Comment by NSkelsey** [comment]
The sun setting of plain HTTP by modern browsers is slowly happening. https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html

With javascript on the page we can connect when a connection has come in over the plain net without an onion looking host name.

A suggestion for the message which I think sufficiently blames the administrators for the configuration problems:

```
Danger! Your connection is not protected from interception or intentional manipulation. Any information you provide to the platform can be recorded by a third party. The site administrators have not configured the application correctly.
```

In addition to this we can disable the submission interface to prevent someone from accidentally compromising the content of a valid submission by authenticating with their token over HTTP.

**Comment by NSkelsey** [comment]
This ticket is handled and documented by our usage Strict-Transport-Security headers, when HTTPS is configured. Further our detection and redirection of HTTP and HTTPS is further explained here #1982.
