### ISSUE TITLE
wizard has inconsistent password enforcing policy

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1687]
Despite the client report the password being "Strong", when the POST is received:

    2016-05-31 10:37:52+0200 '[!] Failed wizard initialization InvalidInputFormat: <<Invalid Input Format [password requirements unmet]>> (2) HTTP:406'
    2016-05-31 10:37:52+0200 [http] 406 POST /admin/wizard (127.0.0.1) 615.79ms

because the password is lacking of the previous (backend) password strength check (I used my email as password, and is lacking of a number, part of the previous requirement)

**Comment by evilaliv3** [comment]
Right!

I would suggest that we can leave this validation only clientside.

As the javiscript library work we have no reason to do the test also on the
backend and after the clientside encryption and password hashing we would
not be anyhow able of doing it server side.

in alternative the server side check should be replaced with
http://packages.ubuntu.com/xenial/python-zxcvb

The package is available in Debian and Ubuntu since the last version so it
is possibile to add it to the full debianized package.

I would suggest we proceed simply for removing the server side check.

@fpietrosanti what do you think?

**Comment by fpietrosanti** [comment]
@evilaliv3 yes, i don't see risks, someone making a custom GLClient using it to reduce the password complexity on purpose, it's only harming to himself without any reasons

**Comment by evilaliv3** [comment]
@NSkelsey would you please take care of reviewing this fix (that is simply code removal).

**Comment by evilaliv3** [comment]
@fpietrosanti: as discussed with @NSkelsey, with this and other changes we are really moving a lot of safety on the platform on the client and this is why from now one it is becoming important to not support unsafe browers that do not offer the webcryptoAPI.

e.g. the SALT generation and the password strength validations will be two things done by the client.
