### ISSUE TITLE
password strength checker has a small inconsistency

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1688]
Despite the two password are the same:
![image](https://cloud.githubusercontent.com/assets/89555/15668578/656189b6-271c-11e6-80da-49a8c9f29ab1.png)

still report they are different

**Comment by vecna** [comment]
Update: the password is not accepted because is "weak" but is not communicated that I can't use a weak password.

**Comment by NSkelsey** [comment]
On it.

**Comment by NSkelsey** [comment]
@vecna I can't reproduce the bug. The save button should be disabled and the * passwords do not match should not be displayed.

This is what I see when I check out the issue above:

<img width="425" alt="schermata 2016-05-31 alle 11 14 45 am" src="https://cloud.githubusercontent.com/assets/1095794/15669506/f250060a-2720-11e6-9fd4-3a913d1f5b00.png">

**Comment by vecna** [comment]
sorry, I forget to specify, is happening in the wizard

**Comment by NSkelsey** [comment]
Ahhh! Okay yeah one moment

**Comment by evilaliv3** [comment]
I've applied minor changes to  the commit already authored by @NSkelsey 

the behaviour is now the following:
- we never show errors on the password configrmation until the password constraints are satisfied.
- in case the password does not satisfy the required strenght we are now showing the text "The chosen password is too weak. Make it more secure by adding special characters, numbers, and unusual symbols."

the texts has being studied in order to be general and easy internationalizable.
