### ISSUE TITLE
Can't upload images / deleted images on update

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1747]
After updating the software to the latest version, all the uploaded images disappeared (the custom .css was also deleted). I got to re-upload the logo image, but trying to re-upload the users logo/images simply doesn't work. Ref: Mexicoleaks.

**Comment by evilaliv3** [comment]
what issue are you encountering in re-uploading the images?

recently (from various releases) we moved the images from the filesystem to the database and specific migration has been implemented for this.

the issue you may have encountered is that the platform since ever, supports only PNG images, but that support was not enforced so that if you loaded a JPG it was shown anyway.

 now instead for technical reasons this encorcement is present and if you load an image that is not a PNG you will see a blank or damaged image; is this the case?

**Comment by infosquatter** [comment]
im trying to upload .png images and I can see them on the preview. i
save it etc, but the changes dont have any effect afterwards.
Giovanni Pellerano:
> what issue are you encountering in re-uploading the images?
> 
> recently (from various releases) we moved the images from the filesystem to the database and specific migration has been implemented for this.
> 
> the issue you may have encountered is that the platform since ever, supports only PNG images, but that support was not enforced so that if you loaded a JPG it was shown anyway.
> 
>  now instead for technical reasons this encorcement is present and if you load an image that is not a PNG you will see a blank or damaged image; is this the case?
>

**Comment by evilaliv3** [comment]
thanks @infosquatter 

can you confirm that this is the latest version?

we are now proceeding retesting if there is a defect in the current release.

**Comment by evilaliv3** [comment]
@infosquatter issue conformed; i will be back to you shortly when we have a fix.

**Comment by evilaliv3** [comment]
@infosquatter: with version 2.63.2 you should be able to load the images correctly;

sadly it was right a migration part was failing to save the css file and the images of the recipients; i'm sorry for the inconvenience.

**Comment by infosquatter** [comment]
thanks a lot! will update and let you know.

cc @marceloomens

Giovanni Pellerano:
> @infosquatter: with version 2.63.2 you should be able to load the images correctly;
> 
> sadly it was right a migration part was failing to save the css file and the images of the recipients; i'm sorry for the inconvenience.
>
