### ISSUE TITLE
Enable "Test Email Notification" button for test send email

### ISSUE THREAD

**Issue by strikerno19** [globaleaks/GlobaLeaks#1757]
I don't know to configuration to enable "Test Email Notification" button for test send email ,please guide for me , Thanks You

**Comment by NSkelsey** [comment]
Hi @strikerno19,

The "Test Email Notification" button will send emails to the email address of the currently logged in user. The emails are sent from an STMP server described by the "SMTP Server Address" field.

Right now it looks like demo.globaleaks.org is not sending emails. If you are using "demo.globaleaks.org" emails will not for the moment because the server is broken. The test email button is not working for me either.

I will ask the volunteers who run the demonstration server to look at the issue, but they are busy. A solution around this is to run your own SMTP server or contact a group like [Whistleblowing Solutions](https://whistleblowing.solutions) to help you run one.

If you are not receiving emails at your account, first check that the username/password and hostname of the SMTP server you are using. If you are using the default server, sorry but its not working today.

**Comment by strikerno19** [comment]
Thanks You for your guideline to set that.

**Comment by NSkelsey** [comment]
Happy to help
