### ISSUE TITLE
Make failures with required fields in a submission with steps easier to see.

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1778]
Required fields tend to be ignored by the Whistleblower when they are paging through steps.

We can place a collection of errors at the bottom of a step for validation errors that occur on that step as a summary. In addition to the checks in #1754.

**Comment by evilaliv3** [comment]
Yes i agree on this desiderata.

Following the more common implementations i would suggest that instead of the bottom error we put this information box at the top, before the first field of the step.
In addition while addressing this ticket we could also move the file upload status next to the field the specific file upload leaving so the right column available for additional contextualization about the fields and their validation; This is in general a change that we will have to do in order to importove the file upload.

**Comment by evilaliv3** [comment]
This ticket has been addressed.

details of the implementation are on #1754
