### ISSUE TITLE
The sticky footer implementation is not working well on devices with small screen

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1779]
While retesting the interface for AutovieVenete on small devices we just spotted that the sticky footer implementation is not working well on devices with small screen.

This issue is not easy solvable given the browser support for implementing a sticky footer (totally missing).

The current implementation, that is the common one make use of padding-bottom strategies that require an exact sizing of the footer and has the known issue of not being responsible.

**Comment by evilaliv3** [comment]
After a day of retesting of the different css / javascript based solutions i found that non is really satisfying to be adopted in place of the current one.

There is a CSS3 directive (flex) that has being specified for implementing features like these but it is known to not being well implemented by all browsers.

The best approach, proposed by @NSkelsey is to adopt the css media query to the browser in order to apply different styling depending on the size of the browser; this way the beautified sticky footer could be applied only to the screen biggers than a certain size that are in the fact the only screens that would benefit of that.

**Comment by evilaliv3** [comment]
@NSkelsey build on your ideas i've sketched this implementation that seems to me to work really well.

```
@media (min-width: 800px) and (min-height: 600px) {
  body {
    min-height: 100%;
    padding-bottom: 10em;
  }

  #FooterBox {
    position: absolute;
    bottom: 0;
  }
```

The padding of 10em for my tests is a reasonable size that is working well both for single line and multi line footers big up to the size of autovie venete and even more so that in the general use cases it will never require any tweak from the end user.

**Comment by NSkelsey** [comment]
@evilaliv3 for the chosen position of when to switch to floating the footer [here](https://github.com/globaleaks/GlobaLeaks/commit/36111809b9902448880d186020028fbe81fa94a3#diff-f688b2d4c25f705d9242ca6ff1811a48R16), we should use the same media query that bootstrap uses, so that everything reflows at once.

The default media query for `md` is the following:
```less
/* Medium devices (desktops, 992px and up) */
@media (min-width: @screen-md-min) { ... }
```

We use this on col-md elements and we should use it as the reference for devices with limited view ports versus full windows on the desktop. 

You may consider it too big, but if that is the case we can move everything at once (at a later point) to small:

```less
/* Small devices (tablets, 768px and up) */
@media (min-width: @screen-sm-min) { ... }
```
