### ISSUE TITLE
If recipients selection is disabled, the "select all recipients by default" option should be forcefully ON

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1790]
Its not there:

![schermata 2016-10-11 alle 6 19 48 pm](https://cloud.githubusercontent.com/assets/1095794/19278884/5357db7c-8fdf-11e6-86e8-f0edbdf19ef5.png)

And with a switch:

![schermata 2016-10-11 alle 6 19 43 pm](https://cloud.githubusercontent.com/assets/1095794/19278898/5a492de6-8fdf-11e6-8db2-741089b03399.png)

It appears.

**Comment by evilaliv3** [comment]
This is not a bug, but the intend behaviour.

Look at the images and read the following description:
- situaton 1: you dont want the whistleblower to select its recipients -> so the interface for selecting all recipients by default should be forcefully ON. (the bug is that we are not forcefully setting this ON on the backend)

- situation 2: you want to allow the whistleblower to select its recipients; here one can choose if having select all recipients by default ON or OFF to configure the behaviour of the recipients selector by default.
If you want to let the user choose the whi
If the user

**Comment by evilaliv3** [comment]
@NSkelsey: this is exactly why few time ago i added these lines: https://github.com/globaleaks/GlobaLeaks/blob/master/backend/globaleaks/handlers/admin/context.py#L157

```python
    if not request['allow_recipients_selection']:
        request['select_all_receivers'] = True
```

i added those lines few time ago (early september) now that i remember i think i implemented this specifically while debugging the same issue on some other adopter: https://github.com/globaleaks/GlobaLeaks/commit/c2bebd27515a14a529432d1d9eb1ac9b6c66243a

if you want from now on we can even a db check constraints (but we need a migration that fixes these eventually).

in case the existing solution work for you in current devel, i think we can close the ticket.

**Comment by NSkelsey** [comment]
No, right now, the only people on the planet who know how to set this setting are me and you because the UI does a show and hide that makes zero sense.

I will agree to close this when there is a toggle that clearly displays the choices you can make.

**Comment by NSkelsey** [comment]
Fixed. 

## Closed
![schermata 2016-10-12 alle 6 24 56 pm](https://cloud.githubusercontent.com/assets/1095794/19318489/3e2b1a82-90a9-11e6-8d48-ba25c50e8458.png)

## Open
![schermata 2016-10-12 alle 6 24 48 pm](https://cloud.githubusercontent.com/assets/1095794/19318498/44855b4a-90a9-11e6-9eec-dacb5fd32b6a.png)

**Comment by evilaliv3** [comment]
@vodkina why are you reopening this ticket?

**Comment by vodkina** [comment]
Sorry, I was rearranging issues visualization on the zenhub board and eventually re-opened this and other tickets.
The situation is back to normal, now.
