### ISSUE TITLE
Submission export in some languages returns an empty data.txt

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1803]
The issue has to do with the usage of default strings within `backend/handlers/export.py` along with the values within `appdata.json`

**Comment by evilaliv3** [comment]
The issue here is that catalan has probably been initialized with an empty
string when it was still not translated and we have no code to inject the
translation as it is added.

I think that for things like this (that are not custonable) we should
remove them fron the APi and havw special handling in the data migration
and force their update.

**Comment by evilaliv3** [comment]
This should be addressed by the migration fix added for user.language.

Lets close the ticket and reopen if further serialization will still continue to have the issue.
