### ISSUE TITLE
Failure in starting globaleaks: Unmet requirements cffi and enum34

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1804]
Instruction to fix dependency error after upgrades are incorrect with the path to execute "pip install" to be invalid.

The way to fix it is to adjust the path printed by removing "backend" 
<img width="1085" alt="screen shot 2016-11-03 at 8 27 51 am" src="https://cloud.githubusercontent.com/assets/770363/19958463/b451344c-a19f-11e6-8cc1-f9d0e4d1a939.png">

**Comment by fpietrosanti** [comment]
After trying to start the command with the right path (pip install -r /usr/share/globaleaks/requirements.txt), globaleaks does not yet start giving the same error:

<img width="1395" alt="screen shot 2016-11-03 at 8 37 16 am" src="https://cloud.githubusercontent.com/assets/770363/19958601/d01a086a-a1a0-11e6-8c88-ca5f6614a99f.png">

**Comment by evilaliv3** [comment]
The instructions are correct but sadly cannot apply to this really specific issue.

This issue affected a very limited set of releases and i expect not that much initiatives.

I leave here the commands and rename the ticket in order to be able to refind them:

When one gets exactly the error:
```

Unmet requirements:
     cffi==0.8.2 [ Installed 1.3.1 ]
     enum34==0.9.23 [ Installed 1.1.1 ]
```

the solution is to perform the following commands:
```
rm /usr/local/lib/python2.7/dist-packages/enum* -rf
rm /usr/local/lib/python2.7/dist-packages/cffi* -rf
pip install -r /usr/share/globalaks/backend/requirements.txt
```
