### ISSUE TITLE
Check accepted filetype for custom_blah

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1805]
Currently an admin can place pngs where html files should be.

The admin interface should prevent this from happening so that adopters do not load the wrong things in the wrong places...!

**Comment by evilaliv3** [comment]
Around this would be great if we could implement the  following:

1) a configuration variable in the controller for defining the list of extensions
2) a parameter in the directive (e.g. filetypes=)
3) if we could add a variable to the file uploader so that even in the submission fields we could allow only certain extensions.

1 and 2 are preliminar and should be the driver for the implementation to be applied first to the admin interfaces; then we can work on 3 and add a configuration variable to the fields of type file upload.

**Comment by fpietrosanti** [comment]
Please does not consider this a perfect security feature as we deeply analyzed in past that it can be bypassed anyway. It shall be considered more as a deterrent to just send .exe or nasty stuff.
Implementing this feature properly (yet, imperfect) require a lot of work as documented on #355 as https://github.com/globaleaks/GlobaLeaks/issues/355#issuecomment-20186034 so please time-cap the implementation effort. IMHO we need to go by estimates time-capping small features

**Comment by NSkelsey** [comment]
We are using filename instead of the flow assigned 'filetype'. Getting into how the filetype is chosen across platforms will consume a huge amount of time. ```.PNG .pnG .PnG .png``` are all valid.

Visual examples:
#### PNG upload denied
![man-fail](https://cloud.githubusercontent.com/assets/1095794/21691688/ef9b7178-d379-11e6-87c3-6d0339aafa9a.png)

#### Favicon.ico denied
![errord](https://cloud.githubusercontent.com/assets/1095794/21691704/faf67c8e-d379-11e6-991e-c97dde387edf.png)

The only thing that is going to get me to look at this again are more comments or failing tests. ;) ;)
