### ISSUE TITLE
change base64 to base85 to gain more entropy

### ISSUE THREAD

**Issue by flipchan** [globaleaks/GlobaLeaks#1825]
hi i have a small suggestion 

to encode with base85 instead of base64 to gain much more entropy

https://github.com/globaleaks/GlobaLeaks/blob/master/backend/globaleaks/security.py

**Comment by evilaliv3** [comment]
@flipchan could you please elaborate why in your opinion encoding the same entropy in a different manner should gain more entropy?

**Comment by flipchan** [comment]
ofc @evilaliv3 :) useing base85/ascii85 you will get a  bigger charset of characters == more special characters when  u encoden urandom == more entropy

**Comment by NSkelsey** [comment]
Hi flipchan, if we used the same amount of bytes for the buffer drawn from `/dev/urandom` we would end up with the same amount of entropy.

What would change is the size of the encoding and as you rightly point out using base85 would decrease the size of the stored salts. I prefer to keep the API simple, lose the extract space and stick with base64 encodings everywhere.

If we were a bit more serious about saving space we could just define the salt column in the DB as a blob, which I do not think we will do because it is nice to be able to see the salts.

So thanks for the contribution. I am marking this as closed.
