### ISSUE TITLE
Sessions must expire on new login by the same user

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1836]
Currently multiple users can log with the same credentials at the same time.

This ticket is to make sessions sessions expire on new login by the same user.

**Comment by NSkelsey** [comment]
Commit #ffb57e9 addresses recipient, admin, and custodian sessions.

Some thought to fixing the interface is needed for Whistleblowers. The current issue is that the error display of a 412'd Non-authd whistleblower action does not display correctly in the frontend.

**Comment by NSkelsey** [comment]
Will wait for build to pass before closing.

**Comment by NSkelsey** [comment]
@evilaliv3 The reason `revoke_all_sessions` remains instead of using a beak and renaming to`revoke_one_session`. Is because I do not find the performance difference noticeable and I feel that asserting that every session is revoked for the passed user_id is much more powerful than removing one.

The `GLSessions` `TempDict` should have a second dict that maps user_ids to session objects.

**Comment by evilaliv3** [comment]
Ok go for it @NSkelsey lets keep the full loop :)

Let's not add the secondary dictionary that would make too complex the solution with possibility for circular references on a critical resource like sessions.
