### ISSUE TITLE
Unhandled exception in getWebCrypto().digest

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1842]
GlobaLeaks version: 2.65.9

URL: http://xxxx.onion/#/submission

User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

Error Message: TypeError: undefined is not an object (evaluating 'getWebCrypto().digest')

Stacktrace:
[
  {
    "source": "xxxxxx@xxx.com://xxxx.onion/js/scripts.js:9094:36", 
    "columnNumber": 36, 
    "lineNumber": 9094, 
    "functionName": "work", 
    "fileName": "http://xxxx.onion/js/scripts.js"

**Comment by evilaliv3** [comment]
With the previous commit i think i've addressed the issue by correctly blocking the browser that is out of support with an improved check.

The past one one was not properly assessing the preence of all the required webcrypto APIs.

**Comment by evilaliv3** [comment]
This is a Chrome browser using Tor directly and thus HTTP.

Chrome when using HTTP does not enable the WebCrypto API.

The fix in https://github.com/globaleaks/GlobaLeaks/commit/ca66d2641eb61208c09169f0b8e95f2fc39687de is sufficient to block the issue. The error provided will be misleading because will say to the user that the browser is not supported but will show chrome as supported browser.

Ticket 1664 will solve the issue by always implementing HTTPS on top of Tor.
