### ISSUE TITLE
Unhandled exception on "Cannot call method 'digest' of undefined"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1843]
GlobaLeaks version: 2.64.9

URL: https://www.xxxxx.org/#/submission

User Agent: Mozilla/5.0 (Linux; U; Android 4.2.2; en-gb; GT-I8200 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

Error Message: TypeError: Cannot call method 'digest' of undefined

Stacktrace:
[
  {
    "source": "    at work (https://www.xxxxx.org/js/scripts.js:9064:37)", 
    "columnNumber": 37, 
    "lineNumber": 9064, 
    "functionName": "work", 
    "fileName": "https://www.xxxxx.org/js/scripts.js"

**Comment by NSkelsey** [comment]
This is an IOS device with problems producing the digest. Our minified JS only has around 1k lines in it. I wonder why it is printing 9064.

```bash
> wc scripts.js 
      20      60     817 scripts.js
```

**Comment by evilaliv3** [comment]
This issue is just a duplicate of #1842 with no any additional detail.

The stacktrace difference is given by the difference of the mobile used for testing the platform.

**Comment by fpietrosanti** [comment]
Are there in the code execution flow any check to prevent that kind of error? As #1842 seems a different error on a different platform

**Comment by evilaliv3** [comment]
same exact error on same exact line, what change is that in one of the stacktrace the browser does not give visibility of the function name probably due to a different implementation of the stacktrace library we use in relation to the library.

Yes the new check that i've added to fix the issue will simply prevent to reach that stage and will give the platform unsupported message.

I will now take care of finding a platform that allows us to test does mobiles and test in detail.

**Comment by evilaliv3** [comment]
Commit ca66d2641eb61208c09169f0b8e95f2fc39687de perfectly fix this issue by checking the presence of the subtle API and whill say that the browser is not compatible.
