### ISSUE TITLE
IE 9 browsers are not shown the platform compatibility interface

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1875]
**Current behavior**

Visit demo.globaleaks.org with an IE 9 browser and get stuck with the loading modal.

**Expected behavior**

The page should display: "Warning your browser is not supported!"

**Minimal reproduction of the problem with instructions**

IE 9 -> demo.globaleaks.org -> observe the spinning loading panel for ever.

**What is the motivation / use case for changing the behavior?**

There are people that still use this browser.

* **GlobaLeaks version:** 2.65.4 to 2.65.11

Tested on 2.65.4 and 2.65.11

* **Browser:** [IE 9]

IE 10 does not show the same behavior.

**Comment by NSkelsey** [comment]
Stranger is that you can get the bug to disappear if you open the developer tools in IE 9 and visit demo.globaleaks.org.

**Comment by evilaliv3** [comment]
I've analyzed the bug and solved the issue.

On IE9 and others IE versions console.log like other console methos are only available when the console is open.

The issue is a well known issue discussed on stack overflow: https://stackoverflow.com/questions/7742781/why-does-javascript-only-work-after-opening-developer-tools-in-ie-once

I'm going to apply the following fix in order to be able to leave the console.log calls that we have that help debugging browsers incompatibilities:
```
if(!console) {console={}; console.log = function(){};}
```

This fix has been already retested with Windows in the problematic versions;

**Comment by NSkelsey** [comment]
Closing as resolved.
