### ISSUE TITLE
apparmor profile denies access for gnupg's _find_agent

### ISSUE THREAD

**Issue by combs** [globaleaks/GlobaLeaks#1883]
~                           

**Current behavior**

When I start up globaleaks, it outputs the following:
```
Jan 25 12:05:11 transfer.[OURHOST].com globaleaks[1092]: File "/usr/local/lib/python2.7/dist-packages/gnupg/_meta.py", line 115, in _find_agent
Jan 25 12:05:11 transfer.[OURHOST].com globaleaks[1092]: if (proc.name() == "gpg-agent") and proc.is_running():
Jan 25 12:05:11 transfer.[OURHOST].com globaleaks[1092]: File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 634, in name
Jan 25 12:05:11 transfer.[OURHOST].com globaleaks[1092]: name = self._proc.name()
Jan 25 12:05:11 transfer.[OURHOST].com globaleaks[1092]: File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1092, in wrapper
Jan 25 12:05:11 transfer.[OURHOST].com globaleaks[1092]: raise AccessDenied(self.pid, self._name)
Jan 25 12:05:11 transfer.[OURHOST].com globaleaks[1092]: psutil.AccessDenied: psutil.AccessDenied (pid=1)
```

**Expected behavior**

**Minimal reproduction of the problem with instructions**

Install on Raspberry Pi 3 Raspbian, per instructions here
https://forum.globaleaks.org/t/raspberry-pi/63

Start up Globaleaks
`/etc/init.d/globaleaks start`

Check its status
`systemctl status globaleaks.service -l`

**What is the motivation / use case for changing the behavior?**

It won't start

* **GlobaLeaks version:** 2.X.Y

GlobaLeaks Version: 2.65.14
GlobaLeaks DB version: 35

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Other (specify) ]

n/a

**Comment by evilaliv3** [comment]
Hi @combs than you for opening this issue and reporting your issue in detail.

Currently the apparmor profile of GlobaLeaks is written in relation to Ubuntu so that probably it would require some fixes in order to work on your raspbian.

What you could do right now, just to test it out without Apparmor, is to disable it. You could do this issuing the following commands:
```bash
echo "APPARMOR_SANDBOXING=0" >> /etc/defaults/globaleaks
/etc/init.d/apparmor reload
/etc/init.d/globaleaks restart
```

In order instead to start debugging which capabilities should be added to ```/etc/apparmor.d/usr.bin.globaleaks``` in order to make it work with Apparmor enabled you should simply running as you are doing and reporting us the issues that you are reading in ```dmesg``` logs.
With one or two round trips of bugfixing i'm quite sure that we will get it working!

**Comment by combs** [comment]
Without Apparmor it does start successfully.

**Comment by NSkelsey** [comment]
At the moment Rasbian is not an officially supported OS. I feel this is safe to close and archive as a note for future work.
