### ISSUE TITLE
sandboxing globaleaks

### ISSUE THREAD

**Issue by flipchan** [globaleaks/GlobaLeaks#1951]
Apparmor is a privledge tool basically so if a third party where to hack/exploit and get remote code execution on a globaleaks he/her/it could then use a privledge escalation to bypass it . My suggestion is to run globaleaks in a sandbox like bubblewrap (https://github.com/projectatomic/bubblewrap) so if the attacker gets remote code execution he would be able to take over the whole server. Of you could run it in a VM like vagrant or docker. This should be in some wiki somewhere. My suggestion is to use bubblewrap

**Comment by NSkelsey** [comment]
There are admins who have employed [Whonix](https://www.whonix.org/) to accomplish this form of sand boxing as well. Docker is a portability solution that does not provide meaningful sand boxing from a security point of view.

I've always liked the idea of using a VM, but that will remain out side of the scope of what we implement in this repository because it significantly changes the deployment mechanisms involved.

Anyways there are two tickets that discuss this in more detail. The discussion about evaluating bubble wrap should go there: #919, #861

**Comment by NSkelsey** [comment]
Those tickets are more related to specific tech.

The Docker ticket #1622 is here.

@flipchan I invite you to leave your reasons that you think bubblewrap fits with GL here.
