### ISSUE TITLE
Deprecate Ubuntu Precise and gracefully notify laggards of the change.

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1997]
12.04 is out side of its maintenance window and given the problems we have with continuing to support it. #1911. @evilaliv3 and I propose to drop support by releasing a package for precise which describes and implements an end of life procedure for GlobaLeaks installed on the machine.

It would be wise to warn the admin and users of the closure of the support window. We could go so far as to add a note in the UI that the server which the program is running on is no longer updated.

**Server Operating System and Version (if applicable):**
 
Ubuntu 12.04

**Comment by evilaliv3** [comment]
I confirm the need for this.

Ubuntu 12.04 has no support since April 2017
Tor has removed the support from their repository and removed even the released packages so that it is currently now possible to run the latest release without compiling/setupping Tor manually.

I would suggest to issue a release with a message in the terminal when running globaleaks informing the user that the software is not going to be updated anymore.

Even if Tor has removed the package, all the existing precise setup should have already the required package because in past we used to install the package from the tor repository and the required version has been published by the tor project long time ago.

This behaviour is the one that we have on the demo machine so i expect that maintained precise release will not have problems with this, while instead only eventual new setups with precise wont work.

An additional improvement we may do is to recognize in the install script that the user is trying to do a new setup on a precise and prevent it. 

\cc @fpietrosanti

**Comment by fpietrosanti** [comment]
From deb repository http access log, when is the last time a precise has fetched something?

We probably need to setup such http statistics per Linux distro and per globaleaks version / time to get also an idea

**Comment by evilaliv3** [comment]
We have only stats of the last 3 months in which no precise fetch has been performed.

I'm about to proceed with shutting down the precise repository and deprecate new setups on precise by means of edits just to the install script.

Let's proceed just with this for the moment without no edits to the build script so to be still in the possibility to emit a precise package if a specific need will raise.

**Comment by evilaliv3** [comment]
From the analyzed stats of the previous months there are not ubuntu precise setups or they are not maintained; Ubunu precise has been so deprecated in the repository.

Users that will try to update will receive the ubuntu notice that the repository is not there anymore and will hopefully get back to the wiki or forum.
