### ISSUE TITLE
Fix unhandled exception "RuntimeError: Request.write called on a request after Request.finish was called."

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2003]
**Current behavior**
This ticket is to fix the unhandled exception coming from GlobaLeaks 2.67.8 with error:
"RuntimeError: Request.write called on a request after Request.finish was called."

**Expected behavior**
The expected behaviour is that this error would not get triggered by the unhanded exception handler.

Ref:
https://stackoverflow.com/questions/8384648/python-twisted-error-request-write-called-on-a-request-after-request-finish-w

**Comment by NSkelsey** [comment]
@fpietrosanti in v2.70.0 the issue was addressed in the following commit: 4532a1ce1ad71c87e684db9e4dc25644d10fb546

For clients that do not upgrade off of v2.67.8 and v2.67.6 (when we deprecated cyclone), connections that are canceled from the client side, these exceptions will be generated by the backend.

For administrators that see these exceptions we recommend you update to the latest version of GlobaLeaks.
