### ISSUE TITLE
GlobaLeaks startup script fail but does not report to fail if apparmor utils are not present

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2009]
**Current behavior**
GlobaLeaks startup init scripts try to uses "aa-exec" of apparmor utiles but does not prbe testing if it does exists or not.

**Expected behavior**

If the commandline tool does not exists because it's not installed into the system the startup script should fail report the failure properly.

Below syslog log:
Jul 13 14:01:20 sd-100960 globaleaks[30989]:  * Starting GlobaLeaks daemon globaleaks
Jul 13 14:01:20 sd-100960 globaleaks[30989]: /etc/init.d/globaleaks: line 229: /usr/sbin/aa-exec: No such file or directory
Jul 13 14:01:20 sd-100960 globaleaks[30989]:    ...fail!
Jul 13 14:01:20 sd-100960 systemd[1]: Started LSB: Start the GlobaLeaks server..
Intsalling

**Comment by evilaliv3** [comment]
the missing aa-exec could be an additional condition in which we could start witout apparmor.

I find really strange the condition; @fpietrosanti do you have any step to reproduce?

apparmor is a requirement of the globaleaks debian package; the only thing possible here is that maybe the binary is not always installed inside /usr/sbin/aa-exec or maybe its not always mapped to this directory due to a particular virtualization technology.

do we have a vps where to reprodue/investigate the issue?

**Comment by fpietrosanti** [comment]
Yes, it's the server "parcogiochi" where transparenzaitalia is running that's an Ubuntu 16.10 .

Btw one more if (test) integrity check is a good check for apparmor consistency / existance before uses

**Comment by fpietrosanti** [comment]
It appened also on Ubuntu 17.10, installed from iso image in a virtualbo

**Comment by fpietrosanti** [comment]
root@ubuntu-VirtualBox:/var/log# which aa-exec
/usr/bin/aa-exec

The binary "aa-exec" changed path

**Comment by fpietrosanti** [comment]
That way starts, the PATH is ok to find itself where the command is
root@ubuntu-VirtualBox:/var/globaleaks# grep aa-exec /etc/init.d/globaleaks 
        STARTCMD="aa-exec --profile=usr.bin.globaleaks -- $STARTCMD"
