### ISSUE TITLE
Bad redirection in HTTPS Configuration process

### ISSUE THREAD

**Issue by vodkina** [globaleaks/GlobaLeaks#2024]
**Current behavior**
When configuring HTTPS through the Automatic option, at the end of the process, the user is prompted to or review the configured certificate or to enable the conf.
If the user chooses to review the parameters by clicking on the "Review" button, it is redirected to the initial page of HTTPS configuration instead of being redirected to the "Manual configuration" page where it can review the certificates.

**Expected behavior**
When clicking on "Review" button the user has to be redirected to the Manual conf page for HTTPS in order to effectively review the certs.

**Steps to reproduce the problem or feature illustration**
As an Admin, in the "Administration interface - Network settings" select the tab "HTTPS  Settings", verify the hostname by clicking on Verify and then on Proceed buttons. When prompted to select between "Automatic" and "Manual" options, opt for Automatic; check "I Agree with the Term of Services" and click on "Proceed" button. At the end of the process, in the page with the two buttons "Review" and "Enable", click on "Review"

**What is the motivation or use case for changing the behavior?**
It's a bug. It can be confusing for not skilled users, that get stopped and can't configure HTTPS. 

**GlobaLeaks version:**
Version currently installed on example.globaleaks.org

**Browser:**
Chrome 59.0.3071.115 (Official builds) (64 bit)

**Server Operating System and Version (if applicable):**
see example.globaleaks.org server info

**Client Operating System and Version (if applicable):**
Mac OS X Sierra; Linux Debian Jessie on VirtualBox

**Comment by evilaliv3** [comment]
Thanks for reporting this, with @NSkelsey we were already aware but i forgot to create a ticket.

Going to pick up this and solve it by tomorrow morning.

**Comment by evilaliv3** [comment]
While retesting and issue on example.globaleaks.org i encountered the rate limit of Letesencrypt; i was resetting and re-registering multiple time.

I will restart the test tomorrow.

Probably for the future we should evaluate avoiding to delete the letsencrypt registration for a domain until the configured domain is not changed in order to avoid that a user encounter this issue.

**Comment by evilaliv3** [comment]
Ok the issue should be fixed; The user will be now redirected to the page for manual configuration.

The configuration will appear not editable but just reviewable; e.g. the user wont' be able to change files but just to see if all have been loaded correctly and read some informative details of them.

Let's keep the ticket open until release 2.71 an proper live retesting.

**Comment by NSkelsey** [comment]
Thanks for picking this up @evilaliv3 and for reporting @vodkina. The fix looks good from here. I'll be able to test easily on a setup I have shortly as well.

**Comment by NSkelsey** [comment]
On a live node running 0e4f997e8c which is post 21c9111 we see the review button redirect properly to the file display page. This functions correctly so I am closing the ticket.

![confirmed](https://user-images.githubusercontent.com/1095794/28472369-9635feb6-6e40-11e7-983b-cd52cdb0d543.png)

Notice the delete buttons are disabled while unfortunately the download buttons are too. In order to keep this simple, we are going to leave the download buttons unusable. To change this behavior we would either need to find a super hack to fly the buttons over the disable CSS or rework the interface -- yet -- again.
