### ISSUE TITLE
Change password form will not allow you to paste new password

### ISSUE THREAD

**Issue by aliteralmind** [globaleaks/GlobaLeaks#2028]
It is currently not possible to paste your new password into the "new password 1" and "new password 2" fields on the "change your password" form. As someone who uses crazy 30 character long passwords, as created by 1Password, this is pretty frustrating.

This behavior is true both on the iPad and Google Chrome on Windows 8.

Please consider changing this behavior so you can paste passwords. With something as critically sensitive as global leaks, this kind of discouragement of better passwords is not a good thing in my opinion.

Thanks.

**Comment by NSkelsey** [comment]
I agree with you @aliteralmind, I use KeePassX and it kills me everytime I need to input a password generated from that! 

We need to convince @evilaliv3 to remove the `data-stopccp` directive from the password `input` tags.

**Comment by evilaliv3** [comment]
I agree that the ticket is legit but i would suggest considering this change while implementing https://github.com/globaleaks/GlobaLeaks/issues/113

In fact the problematic of password lockout is to be considered as well; if copy&paste is good for allowing the usage of a reasonably secure password, that is the more common way users locks theirself out of the platform.

**Comment by aliteralmind** [comment]
Agreed that no password recovery is a big problem as well!

**Comment by NSkelsey** [comment]
The administrator of the system has full ability to edit users. So that the only issue with lockout that can occur is with a system with a single administrator that copies and pastes their poorly written password into the /user/preferences/password-configuration-page. Only if they have no ability to do a reset via the command line or ask someone to do a reset from the command line are they locked out.
 
For everybody (receivers, custodians) else the "lock-out" issue does not exist, because the password recovery mechanism is a manual request to change the password to the application administrator.

**Comment by DavidLemayian** [comment]
Just want to drop this interesting read here - https://coreyjmahler.com/2016/10/04/copying-and-pasting-passwords/

Hoping this is implemented.. 🤞

**Comment by evilaliv3** [comment]
thanks @DavidLemayian 

the reasos behing the feature where not related to security but just to prevention of possible user lockout.

accepting anyway the good suggestions of the GlobaLeaks community :) feature removal on its way.

we will then prioritize #113 in order to address the issue of the lockout prevention.
