### ISSUE TITLE
Include an entity relationship diagram within the documentation

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#2041]
**Summary**
Our documentation lacks useful information about the internal structure of globaleaks. It would be very nice to have up to date entity relationship diagrams shipped with our documentation. Using the python library [eralchemy](https://pypi.python.org/pypi/ERAlchemy) we could include the generation of schema with the MAKE of the documentation.

**Manual Steps**

Follow the following steps to reproduce the graphs by hand:

```bash
> apt install graphviz-dev
> pip install eralchemy
> eralchemy -i sqlite:///globaleaks/tests/db/populated/glbackend-37.db -o entity-relations.pdf
> touch entity-relations.pdf
entity-relations.pdf: PDF document, version 1.5
```

**Example output**
Files generated on 02/08/2017:
- [ER-v2.70.10.pdf](https://github.com/globaleaks/GlobaLeaks/files/1194505/ER-v2.70.10.pdf)
- [ER-v2.67.4-multitenancy-fork.pdf](https://github.com/globaleaks/GlobaLeaks/files/1194509/ER-v2.67.4-multitenancy-fork.pdf)

**Todo**

- Validate build process supports custom logic like this
- Implement install of reqiurements.txt
- Implement move of files into proper assets directory
- (Maybe) add annotation to document version/build dates.

**Comment by vodkina** [comment]
It seems to me a great advice, but I can hardly see the usefulness of entity relationship diagrams in user documentation. I think that those have to be included in the developer documentation, because it is something useful to developers when tweaking with the code.

**Comment by NSkelsey** [comment]
I agree with you that for user facing documentation, this does not serve a useful purpose. While working on this project it has been super useful to have these schematics though. I'll close this and just leave this here as instructions on how to generate these docs.

**Comment by fpietrosanti** [comment]
Or make a wiki page or quick reference on the development documentation

**Comment by NSkelsey** [comment]
Sure, can do. One question for @vodkina or @fpietrosanti  is the wiki sticking around for developer documentation? I thought everything was going to be moved in the readthedocs project.

**Comment by vodkina** [comment]
Developer documentation will almost surely move on readthedocs, but up to
now I feel it's better to keep it in the github wiki.


On 22 Aug 2017 19:01, "Nick Skelsey" <notifications@github.com> wrote:

Sure, can do. One question for @vodkina <https://github.com/vodkina> or
@fpietrosanti <https://github.com/fpietrosanti> is the wiki sticking around
for developer documentation? I thought everything was going to be moved in
the readthedocs project.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/globaleaks/GlobaLeaks/issues/2041#issuecomment-324089260>,
or mute the thread
