### ISSUE TITLE
Fix incorrect file size display in upload and source interface

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#2044]
**Current behavior**

When a whistle-blower uploads a file, the reported file size is incorrect. It is not clear if the issue is just in the directive or if the estimation for the file uploader is affected.

Here are some screen shots:

On upload with a comparison of system reported values
![inaccurate-upload-sizes](https://user-images.githubusercontent.com/1095794/29181883-164cb72c-7dfd-11e7-8f46-7ff89c5366ab.png)

Stored and displayed in frontend
![also-stored](https://user-images.githubusercontent.com/1095794/29181913-2dc78a6c-7dfd-11e7-926d-ba4e81582d93.png)

**Expected behavior**

File sizes should match their actual size when downloaded to disk.

**Steps to reproduce the problem or feature illustration**

Upload a file and observe!

**GlobaLeaks version:**

Confirmed on v2.70.9

**Browser:**

Chrome 59

**Comment by evilaliv3** [comment]
@NSkelsey: this is not a bug, it's just the difference between kb considered as 1000bytes or 1024bytes.

I remember you already gone into this discussion, let me refind where it was the clarification.

**Comment by evilaliv3** [comment]
Not founding the old conversation but recreating it here.

the reason is that the library that we use to print (angular-filter) consider a kB 1024 bytes while your operating system consider a kB 1000 bytes.

in the real the two are two different units Kb 1000 (Kilobyte)  while the other is KiB 1024 (kibibyte )but in the common use are always misused and called both kilobye: https://en.wikipedia.org/wiki/Kilobyte

here the simple math that solve your issue:
```
189.9 * 1000 / 1024 = 185.44
146.4 * 1000 / 1024 = 142.95
133.6 * 1000 / 1024 = 130.47
```
