### ISSUE TITLE
Test and bugfixes install script on Linux Mint 18 (codename sarah) 

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2054]
**Current behavior**
Linux Mint 18 it's based on Ubuntu 16.04 that's a supported GlobaLeaks Ubuntu platform but installation attempt fail:
XXXXX  "GET /install-globaleaks.sh?DISTRO=sarah&LAST_COMMAND=&LAST_STATUS= HTTP/1.1" 200 49871 "-" "curl/7.47.0"

**Expected behavior**
This ticket is to test the installation script on Linux Mint 18 and evaluate if, with minor fixes here and there, the installation proceed up to point where it reach attempt to install GlobaLeaks (just fixing install script itself).

**Comment by fpietrosanti** [comment]
Modifications before make installation on Linux Mint 18.2 to works fine (is equivalent of Ubuntu 16.04)

**Comment by evilaliv3** [comment]
This should be now ok thanks to @fpietrosanti commits.

i've revised the solution with some corrections that look forward for next available distributions.

Some code related to setup of python-dev has been removed because now become unneeded because already trusty/wheezy/precise handle that install and all linuxmint versions mapped on them will naturally use those packages.

Leaving for the moment the ticket open in case some users will retest it.
