### ISSUE TITLE
When install script is executed multiple time and globaleaks is already installed, let's ask for a confirmation

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2062]
**Current behavior**
We noticed that actually some end-users execute multiple time the installation script (actually for unknown reasons).

**Expected behavior**
When install script is executed multiple time and globaleaks is already installed, let's ask for a confirmation, explaining that globaleaks is already installed, asking if he want to proceed.

**Comment by NSkelsey** [comment]
The install script in its current form should be idempotent. So there should be no harm from rerunning it.
Our documentation now states that if there is an issue updating from the apt repo just [rerun the install script](https://github.com/globaleaks/GlobaLeaks/wiki/Upgrade-Guide#in-case-of-errors).

I think asking to reconfirm and detect that GL is already on the system is a bit disorienting.

**Comment by fpietrosanti** [comment]
But why people end-up running it multiple time, at distance of several minutes from different runs, and each run is successful (no errors)?

That's the kind of things we need to understand and fix as it should not happen as a normal behaviour

**Comment by NSkelsey** [comment]
In my experience deploying GlobaLeaks, I have tried to run the script and encountered the situation where I was not able to connect to the platform (or tor never came up or some error threw) it is super natural to just try the same command again after a little bit of searching around.

I think that if both times the script is concluding successfully it may be an indicator of poor communication about the next step.

Otherwise it could be two machines with the same public IP :man_shrugging:

**Comment by NCommander** [comment]
Looking carefully at the install script, its idempotent, and it's also a way of updating dependencies/requirements of GL. I think it's completely valid and sane to re-run install.sh and would be counter-inventive to introduce this behavior. 

I'm going to close this bug unless there's an actual usecase for this.
