### ISSUE TITLE
Handle exception ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2070]
**Current behavior**
Handle unhandled exception

Platform:  ()
Version: 2.71.3

twisted.internet.error.ConnectionLost Connection to the other side was lost in a non-clean fashion

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 45, in run
    yield self.operation()

ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.

**Comment by NSkelsey** [comment]
This is a twisted.internet.error.ConnectionLost exception thrown during an external network connection with one of our jobs. Its not clear from the output which job failed, but there are only three candidates. I would rule out delivery_sched though because this email arrived. The other two could have failed for any number of network related reasons.

- `delivery_sched`
- `exit_nodes_refresh_sched`
- `update_check_sched`

What is frustrating about this type of failure is that the callback chain which really contains information about the point of failure is eaten, because self.operation is a `twisted.internet.deferred`. To work around this we need to handle the proper export of errors in callback chains.

**Comment by NSkelsey** [comment]
A related stack trace that is similarly generating errors.

```
Platform: ()
Version: 2.71.1

twisted.internet.error.ConnectionRefusedError Connection was refused by other side

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 43, in run
    yield threads.deferToThread(self.operation)

ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
```

This code here is an exception from a different job however.  Lines 42-45 of `jobs/base.py` as of v2.71.x

```python
        try:
            if self.threaded:
                yield threads.deferToThread(self.operation)
            else:
                yield self.operation()
```

**Comment by NSkelsey** [comment]
At least one source of the original exception posted was handled in ff1189dd9de5cf6e238aff6cdf8da83db03e4bb5. These failures were thrown on an improper shutdown of the `onion_service` job.

**Comment by NSkelsey** [comment]
This exception has also been seen on `Exit relay fetch` job.

```
2017-07-02 07:53:51+0000 [-] [E] Exit relay fetch failed: [&lt;twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.&gt;, &lt;twisted.python.failure.Failure twisted.web.http._DataLoss: &gt;]
2017-07-02 07:53:51+0000 [-] Stopping factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x31c6ef0&gt;
```

The commit 6731b53 handles this case. So this exception generated in other contexts should be covered. Seeing this issue in any version newer than v2.72.5, suggests new code paths are throwing the error.
