### ISSUE TITLE
Cannot postpone expiration. Submissions about to expire!

### ISSUE THREAD

**Issue by aliteralmind** [globaleaks/GlobaLeaks#2071]
As an admin, I have set every context to NOT expire submissions. I have also given every recipient the ability to postpone expiration dates (for those submissions whose expirations were grandfathered in). 

![000408](https://user-images.githubusercontent.com/1482392/29798780-350d0200-8c2d-11e7-96b9-0b65a566db47.jpg)

But it's not working. When a recipient clicks on the "postpone expiration" button in a submission, it pops up an "are you sure" dialog, but then it does nothing. The date is not postponed at all.

![000409](https://user-images.githubusercontent.com/1482392/29798903-0abb558c-8c2e-11e7-9954-1a2aa5008b2e.jpg)
![000410](https://user-images.githubusercontent.com/1482392/29798904-0c6cfd40-8c2e-11e7-9eab-39ba93c2a2a2.jpg)

We are now about to lose submissions to expirations. This isn't a matter of losing data (we have backed up all the files just fine), but rather that we're losing the main venue in which submitters have to communicate with us.

We are unsure what to do. We can only assume this is a bug that we have no control over. In the meantime, can we manually change this information in the backend somehow?

Thanks.

**GlobaLeaks version:**
Software version: 2.70.10

**Browser:**
Google Chrome Version 60.0.3112.101 (Official Build) (64-bit)

**Client Operating System and Version (if applicable):**
Windows 8

**Comment by evilaliv3** [comment]
Dear @aliteralmind,

We are sorry for the inconvenience and we are going to investigate the
issue with hight priority.

From the screenshot you are providing i'm thinking to have already a
solution for your issue.

I guess (I may be wrong) that recently disabled the expiration but that
this event happened after some submission happened. You have to keep in
mind (and we will fix the interface to make it more explicit) that by the
current implementation on this condition the expiration of existing
submissions is non changed.

Due to a bug anyhow since you set the expiration to not happen the platform
is using internally a postpone period of 0 and this is not postponing at
all.

To temporarily fix your issue in the context settings set an expiration
period to a value like 365 day (a year) and then perform a postpone. This
would allow you to postpone the existing submissions of 365 days.

Please let me know if this fix your issue.

In any case i will update the ticket as soon we have more information and
try to have already a release including the patch by today.

>

**Comment by evilaliv3** [comment]
After few tests i confirm that the short term manual fix proposed in past comment works.

**Comment by aliteralmind** [comment]
I changed the expiration for each context to 365 days, and then postponed each submission. It worked. Thank you!

**Comment by aliteralmind** [comment]
I look forward to a more permanent solution.

**Comment by evilaliv3** [comment]
Fix integrated in the platform stable release starting from version v2.72.
