### ISSUE TITLE
Wrong migration 38 results in missing context/questionnaire association

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2078]
**Current behavior**
Platform: xxx.xxx.xx ()
Version: 2.72.0

URL: /submission

User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1

Error Message: TypeError: undefined is not an object (evaluating 'context.questionnaire.steps')

Stacktrace:
[
  {
    "source": "~~~~~~@~~~~~~://xxx.xxx.xx/js/scripts.js:20362:75", 
    "columnNumber": 75, 
    "fileName": "https://xxx.xxx.xx/js/scripts.js", 
    "functionName": "prepareSubmission", 
    "lineNumber": 20362
  },

**Comment by evilaliv3** [comment]
I know this kind of issue and i've got it some times while migrating very old nodes; it seems and it happens when to the context is not assigned a questionnaire and the context is serialized.

going to pick this up implementing a small fix to not serialize the context if no questionnaire is assigned.

we will skip instead the migration analysis until it will not eventually rehappen.

**Comment by evilaliv3** [comment]
After analyzing a bit more the topic in relations to some of the doubts i had, i've identified that migration 38 result in missing context/questionnaires assignment.

Result of the wrong migration is a context with an unassigned questionnaire.

A manual fix is obviously possibile and requries the user to manually reassign the context.

The issues is not responsible of any data loss

The patch has already been integrated in the devel branch and will be released starting from version 2.72.9
