### ISSUE TITLE
Missing Favicon / shortcut favicon

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#210]
This ticket is to introduce a default favicon and favicon icon and make the favicon configurable by the node administrator.

This will show out graphically in the tab with:
                                   <link rel="shortcut icon" href="favicon.ico">

**Comment by evilaliv3** [comment]
This feature was removed while ago simplifying the delivery of the application to the user.

Now that we have added the serialization in the /public api of the main resources needed in order to bootup the application the feature can be reintroduced and the favicon could be stored in a file resource with the id ```favicon```

**Comment by evilaliv3** [comment]
Just as memory so far no user noticed this missing feature and it was AutovieVenete that recently asked me for that.

**Comment by vodkina** [comment]
Could you please estimate this issue? :)

**Comment by evilaliv3** [comment]
Implemented!
