### ISSUE TITLE
Issue when enabling multiple entries for field of type Date

### ISSUE THREAD

**Issue by damian-garrido** [globaleaks/GlobaLeaks#2202]
**Current behavior**

when you create an a date entry to the form with the possibility of adding multiple dates, the form in the front dont work with new dates because only change the first field date and open a double calendar

**Expected behavior**

open one calendar for each input field

**Steps to reproduce the problem or feature illustration**

![imagen](https://user-images.githubusercontent.com/25389333/36981604-6019c036-206c-11e8-9c40-46f3e7023944.png)

**What is the motivation or use case for changing the behavior?**

using multiple dates

**GlobaLeaks version:**

2.72.28

**Browser:**

firefox 58.0.2

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

Fedora 27

**Comment by evilaliv3** [comment]
Thank you @damian-garrido  for reporting this!

**Comment by damian-garrido** [comment]
i made this
![imagen](https://user-images.githubusercontent.com/25389333/37032895-d025c95e-2122-11e8-8312-51b05aa6fad1.png)
adding a date field and then mark the multiply response

**Comment by evilaliv3** [comment]
Got it so that maybe the issue is on fields of type date that are marked to "aceptar multiplest respuestas".

From my point of view it makes not particular sens to implement that feature on Dates, so i think we will remove it in the future to prevent the bug.

In case you are making a question for "Start Date + End Date" i would suggest to:
- Create a parent field of kind "Fieldgroup"
- Create two child field of the fieldgroup with the type Date

this way in the two fields of type Date you will be able to add also two different labels like in my axample "Start Date" and "End Date".

Please let me know if this is what you wanted to achieve and if my suggestion solves your problem.

**Comment by damian-garrido** [comment]
perfect!!
this solution works pretty well for me (:

**Comment by evilaliv3** [comment]
I've addressed the issue by disabling the possibility for fields of type Date to be configured as multy entry fields.

This option has been left as a possibility only for fields of type: fielgroup, fileupload.
