### ISSUE TITLE
Upgrade to LetsEncrypt v2

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2219]
**Current behavior**
Actually we are using LetsEncrypt v1, but the v2 has been released.

This ticket is about analyzing and collecting the required tasks, issues and compatibility requirements to upgrade to LetsEncrypt v2 in GlobaLeaks.

**Comment by evilaliv3** [comment]
Main reference for this topic is: https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578

It seems that acme v1 and v2 api will remain both available but it is not clear when api v1 will be shutdown.

it seems not python library exists except certbot that supports v2 only starting from versions 0.22;
this version by the current date is expeted to be included only in the upcoming new LTS version of debian/ubuntu so its adoption is expected to require hardcoding of the library inside globaleaks at the time of the packaging.

a full list of python clients (not libraries) is available at: https://letsencrypt.org/docs/client-options/#acme-v2-compatible-clients

**Comment by NCommander** [comment]
As an alternative to hardcoding in certbot 0.22 or later, it may be better to simply create a new deb package that can be included in the existing APT repo and then pulled in as a dependency. This would allow pip style installs to work while also making the existing requirements-xenial.txt work.

Creating a backport package is relatively straightforward though a few special rules have to be applyed for when the system will upgrade from 16.04->18.04 at a later point. This is likely an easier approach to the problem, and then we can simply pull in the new acme library and add the necessary magic to use the v2 API.

**Comment by evilaliv3** [comment]
Good analysis @NCommander; would be good to investigate how difficult it would be.

We are not concerned in relation to the upgrade as we generally recommend to perform a clean migration to a new vps by simply moving the directory /var/globaleaks on the new system and install globaleaks that will naturally start using the existing directory.

**Comment by evilaliv3** [comment]
Actually certbot is backported official to xenial! we are fine!
http://ppa.launchpad.net/certbot/certbot/ubuntu/dists/

so we require to add the repository as well as we do for Tor, and it will be fine and more secure.

for Stretch instead we should wait that version 0.22 is added to the stretch-backports:
- https://packages.debian.org/stretch-backports/certbot

@bmw @pde: is there an official debian repository that you maintain for Debian and specifically for the Stretch backport?

**Comment by bmw** [comment]
@evilaliv3, we do not have an additional repository for Debian.

We work closely with our Debian maintainers though. They uploaded 0.22.0 versions of Certbot and most of its plugins to Debian unstable over the weekend so it shouldn't be too much longer before it's in `stretch-backports`.

**Comment by NCommander** [comment]
Just for future reference, I'm an active Ubuntu Core Developer, and I can renew my credentials with Debian to reactivate my DD status for the future so I can assist with official efforts to put stuff in *-backports if need be.

From a coding perspective, I think the v1->v2 migration is a relatively straightforward affair for handling single domain certificates (aka LE v1). Do we however want to assist a user with obtaining a wildcard certificate (which is necessary to allow tenants to work as coded). If so, that requires passing a DNS-01 challenge.

To do so, we'll have to do the initial challenge step which causes the ACME server to generate the necessary TXT records (DNS-01 requires that the root of the zone have _acme_challenge as a DNS record to validate ownership), show the key in the UI, and then have the user add the necessary bits to the zone, validate on our end that we can see them, and then ask LE to issue the certificate. It also requires.

Per SSL specification, for everything to work as expected, you need a certificate that has both *.example.com and example.com in the CN/SANs else *.example.com will *not* match example.com and you'll get a common name validation failure. This works with LE, but you have to answer two challenges for both.

**Comment by evilaliv3** [comment]
thank you @bmw 

@NCommander: thank you for this analysis.
i agree, it would be worth the experiment all that you are mentioning.

i would suggest the following:
- let's keep the current interface for the HTTPS configuration in the tenant (DNS-01 challenge)
- let's add the possibility to configure an additional wildcard certificate for the multitenancy ( http-01 challenge)

this will allow us to have two different configurators, one only  HTTP-01 based and one DNS-01 based.
this way at least for the moment we may skip the following problems:
- we will bypass for the moment to have to implement detection of what the user written (wildcard or not) and we will require a not-wildcard in the first interface and a wildcard in the second interface
- we will bypass to have to implement SAN

what do you say?

**Comment by NCommander** [comment]
@evilaliv3, I think your challenges are backwards, GL uses the HTTP-01 challenge, and you need to do DNS-01 for the wildcard.

I'm somewhat questioning the value of actually automatically supporting LE wildcard certs; DNS-01 can't be automated easily, and requires specific support from whatever is the DNS master zone. That being said, for folks that are using multitenant mode, how common is it that they allow arbitrary users to create new platforms aka try.gl.org. For some setups, its likely easier just to allow the existing system allow inputting additional SNIs and then validating them which is trivial to automate.

Anyway, here's my first look at what this will take in actuality; right now, with acme 0.22.2, GL breaks due to the fact that acme.jose moved to pyjose. Trivial enough to fix but the entire V2 interface appears to be implemented as a new class (acme.client.ClientV2) which is not well documented at this moment. I've reached out to #letsencrypt-dev to get some hints. I'll work on this on and off but I'm less concerned on this being a high-priority item for the immediate future until an EOL date is actually posted for the V1 API.

For backporting acme, we'll need to pull the pyjose module; if Debian/Ubuntu are properly backporting the base acme library, we should get this "for free" however. If we end up shipping it in GL, that will be something we'll have to keep in mind.

**Comment by evilaliv3** [comment]
@NCommander @fpietrosanti: i think that we can all agree to postpone the topic for a while while V1 is  not subject to any EOL.

we may go around the need for a wildcard by configuring a certificate for each tenant as it is created.

We may probably switch to 0.22, using the backports in order to:
- continue to use V1
- avoid to manage compatibility code in relation to jose for distros that has python-acme < 0.22 and distros that has python-acme > 0.22

What do you say ?

**Comment by NCommander** [comment]
That sounds like a relatively sane plan to me, but if you intend to support an LTS for the full five years, we'll likely have to deal with the certbot/jose problem at some point. It also might be supporting wildcards just remains out of scope of GL; for my personal setup, I have GL sitting behind a nginx app proxy which works well enough for me w/ a manually issued wildcard.

**Comment by evilaliv3** [comment]
Thanks @NCommander for your feedback.

Actually nginx is not required and you can just use GlobaLeaks and configure your manually issued wildcard.

**Comment by NCommander** [comment]
@evilaliv3 due to the way the system is setup, port 443 is in use by other things so I wanted to leave it on a vhost as the machine requires SNI for it's SSL setup. In general, I prefer to use proxy->application servers as it tends to allow more flexibility in the long run, and for a production install, would let me drop in varnish for additional performance with relatively little pain as you need to do SSL termination.

That being said, it's probably a decent idea to make GL *aware* of this type of configuration and allow host headers to recongize X-Forwarded-For, and X-SSL-On (or whatever flag is current the vogue as that was never a de facto standard).

**Comment by bmw** [comment]
> Just for future reference, I'm an active Ubuntu Core Developer, and I can renew my credentials with Debian to reactivate my DD status for the future so I can assist with official efforts to put stuff in *-backports if need be.

@NCommander, we're actively looking for help with Certbot's Debian packaging. Up until now it's just been one volunteer, with one other person recently stepping in to help, so if you're interested, let me know if you'd like me to connect you with the current maintainer(s).

**Comment by NCommander** [comment]
Id be happy to give a hand. Feel free to get in touch either by my email,
or on Freenode (handle NCommander). I beleive im currently in
#letaencrypt-dev.

Ill be home in about an hour.

On Mar 22, 2018 14:52, "Brad Warren" <notifications@github.com> wrote:

Just for future reference, I'm an active Ubuntu Core Developer, and I can
renew my credentials with Debian to reactivate my DD status for the future
so I can assist with official efforts to put stuff in *-backports if need
be.

@NCommander <https://github.com/ncommander>, we're actively looking for
help with Certbot's Debian packaging. Up until now it's just been one
volunteer, with one other person recently stepping in to help, so if you're
interested, let me know if you'd like me to connect you with the current
maintainer(s).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/globaleaks/GlobaLeaks/issues/2219#issuecomment-375419089>,
or mute the thread

**Comment by evilaliv3** [comment]
@NCommander: understood.

the reasons we embed in general HTTPS in Globaleaks is for a mix set of reasons:
- it ease the setup for the user
- it make the code portable (hopefully on different systems soon)
- it make possible to embed secure configurations (e.g. in the selection ciphertexts)

**Comment by NCommander** [comment]
So I'm going to eat crow, and actually manage to deliver a branch that support v2 ACME support; major shoutout to #letsencrypt-dev that got me over the stumbling blocks though I had to stare pretty hard at certbot's internals to divine the final steps to get a certificate to issue.

No new features added so this is functionally equivalent to the v1 branch, but opens the floor to letting us do multidomain much easier + wildcards in the future.

Of course, this doesn't actually solve the backport problem. Obviously we can just pull in the PPA into the build script, but I'm slightly concerned that the ACME API changes (such as pyjose) might break existing apps into the distro. It's likely the issue of outdated dependencies will come up again so I'm sorta in favor figuring out how we want to address this problem moving forward.

**Comment by evilaliv3** [comment]
Great analysis.

Do not mind about other apps when dealing with globaleaks dependent cues
because anyhow a Globaleaks system is expected to run only globaleaks by
design or few more. So if we could have the backport of 0.22 we should be
totally fine
