### ISSUE TITLE
Apparmor error with unknown functional impact

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2286]
On a GlobaLeaks server with Ubuntu 16.04 reporting the problem of #2175 we also hit this specific error while debugging it:

[   41.618914] audit: type=1400 audit(1526636024.087:20): apparmor="DENIED" operation="capable" profile="usr.bin.globaleaks" pid=2043 comm="globaleaks" capability=2  capname="dac_read_search"

This ticket is to prevent apparmor profile from giving this kind of error

**Comment by fpietrosanti** [comment]
Looking at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=872817 we should probably add to apparmor profile:
+  capability dac_read_search,

**Comment by evilaliv3** [comment]
This capability is necessary as well as dac_override to allow root processes to read or write files where root is not owner and lacks permissions to access the file.

In our scenario this is generally always necessary because all files are owned by globaleaks and not by root. 

The capability is added both to cups and tor in Debian/Ubuntu:

In place of the dac_override_read i will just add dac_override because GlobaLeaks when starting requires to fix permissions.

**Comment by evilaliv3** [comment]
I just noticed that we have already the dac_override capability.
I will so just add also dac_read_search (that actually should be already included by dac_override)

**Comment by NCommander** [comment]
This was fixed by @evilaliv3, closing.
