### ISSUE TITLE
Can't change default language 

### ISSUE THREAD

**Issue by faffa42** [globaleaks/GlobaLeaks#2299]
**Current behavior**
When a different language than English is set as default, the platform keep using english both on the admin page and the user's submission side

**Expected behavior**
It should show the default language as set in the options

**GlobaLeaks version:**
last version

**Browser:**
Tor browser last version

**Server Operating System and Version (if applicable):**
Ubuntu(14.04)

**Comment by faffa42** [comment]
Solved: Globaleaks identify the browser's language and choose it's own accordingly to it.

**Comment by evilaliv3** [comment]
Thanks for opening and updating the ticket as you managed it.

Yes i confirm that GlobaLeaks for usability reasons try to accomodate the browser language in order to provide to the user one of the languages that he will likely speak.

It will be up to the user to choose a different language if this automatic detections do not satify best user choice (e.g. the user is an italian but has downloaded an english version of the tor browser)
