### ISSUE TITLE
It should be possible to extend the maximum number of days of data retention policy

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2324]
**Current behavior**
A corporate user require to have data retention of 10 years or 3650 days. It's not possible to set this number.

**Expected behavior**
This ticket is to enable configuration of 3650 days of data retention, even if generally unhealthy, that's a context where it make sense.

**Comment by evilaliv3** [comment]
The reason the data retention period has been intentionally reduced to 3 years is to prevent users to make nasty configuration.

Anyway since the time we add that limit we changed our position and we made possible to completely disable the data retention and we should accept bigger limits.

Let's go for 10 years max (3650 days).

**Comment by evilaliv3** [comment]
Done!
