### ISSUE TITLE
Enable configuration of unauthenticated SMTP server for sending notification

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2345]
**Current behavior**
Actually GlobaLeaks do require mandatory authentication with TLS to send notification via email, but there are situation where the local email relay in the intranet does not support that setup and require to disable authentication, such as in the Barcelona setup.

**Expected behavior**
This ticket is to enable  configuration of unauthenticated SMTP server for sending notification.

**Comment by evilaliv3** [comment]
I've been always critic of this feature but actually i recognize some value in this change as many user have implemented secure deployments where a local SMTP server is used for sending emails.

Many development environments in addition have required and continued to require this in order to ease first approach to the software.

For the same reason In addition to enable unauthenticated SMTP connections i would make a path to not require transport security.

**Comment by evilaliv3** [comment]
Here the implemented interface, to support the configuration but invite the user to carefully pay attention to the setting.

![screenshot-127 0 0 1 8082-2018-06-29-15-10-51](https://user-images.githubusercontent.com/217034/42095768-d7d48596-7bb3-11e8-8d4d-1925c8dc5062.png)
