### ISSUE TITLE
Create globaleaks daemon/user with uid < 1.000

### ISSUE THREAD

**Issue by marceloomens** [globaleaks/GlobaLeaks#2397]
**Current behavior**
The Globaleaks install script creates the `globaleaks` user with a user id in the => 1.000 space. This space is by convention set aside for regular users, not for daemons.

We now have an issue on one of the Publeaks deployments where the uid of one the the Greenhost ops (these uid's are used infrastructure wide) clashes with the uid of the globaleaks user.

**Expected behavior**
We suggest that the install script creates the `globaleaks` user with a user id in the < 1.000 space that is set aside for system processes. This can be accomplished with:

```adduser [...] --firsutid=500 --lastuid=999```

**Steps to reproduce the problem or feature illustration**
n/a

**What is the motivation or use case for changing the behavior?**
Congruent with convention; avoiding issues such as the one described above

**GlobaLeaks version:**
v3.3.6

**Browser:**
n/a

**Server Operating System and Version (if applicable):**
Ubuntu 16.04

**Client Operating System and Version (if applicable):**
n/a

**Comment by evilaliv3** [comment]
The suggestion is surely legit, good for implementing it! thank you @marceloomens 

Specifically in relation to the publeaks deployments at greenost i would recommend to recheck them in detail because i suspect that a possible failure may be present there independently from GlobaLeaks.
Current implementation of Globaleaks in fact do not use static allocation of the id but leaves the operating system select the ID.

If the infrastructure at Greenhost is failing is probably due to the fact that some code in it is using a static allocation considering that the static configured ID will be always free and available but this is definitelt a wrong assumption. as confirmed by the failure.

\cc @frozen-sky
