### ISSUE TITLE
Error on input validation [need at least one recipient] 

### ISSUE THREAD

**Issue by dfranzoni** [globaleaks/GlobaLeaks#2423]
**Current behavior**

Hi,
I have "Error on input validation [need at least one recipient]" with my Globaleaks installation in any contexts.

I read this forum issue https://forum.globaleaks.org/t/error-on-input-validation-need-at-least-one-recipient/222 but I have not solved the problem.
I have the same result with all "Select all the recipients by default" settings.

Can you help me?

Thank you very much

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

3.4.1 

**Browser:**

any

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Dear @dfranzoni,

i guess during the wizard you enabled the platform to receive submission only if users has configured their PGP key.

This is probably preventing your submissions with this error because every recipient you configured is disabled for this reason.

You may disable this option in the Advanced settings.

**Comment by dfranzoni** [comment]
Perfect.
It works.

Regards

**Comment by evilaliv3** [comment]
Thank you for your feedback @dfranzoni !
