### ISSUE TITLE
Extend the whistleblower identity feature with a show/hide capability

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2497]
This ticket is for implement an extension of the whistleblower identity question to make it possible to hide/show the identity of the whistleblower behind asteriks.

This useful feature, already suggested by many users, is a requirement for the project of Comune di Milano that is currently prototyped in https://github.com/Comune-Milano/Globaleaks-3.1.9-CdM

**Comment by evilaliv3** [comment]
After thinking a little to this i consider that there is no need for a feature implementation.

We could just set the defailt status of the whistleblower identity to ```collapsed``` and this would serve the use case.

**Comment by fpietrosanti** [comment]
Does this fulfill the end user UX experience in dealing with
secret/sensitive data such as passwords?


Sent from mobile

On 7 Oct 2019, at 12:24, Giovanni Pellerano <notifications@github.com>
wrote:

After thinking a little to this i consider that there is no need for a
feature implementation.

We could just set the defailt status of the whistleblower identity to
collapsed and this would serve the use case.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/globaleaks/GlobaLeaks/issues/2497?email_source=notifications&email_token=AAF4CO2PPQLXHUHUJUC3YUDQNME6JA5CNFSM4GSEZ222YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAPY2NY#issuecomment-538938679>,
or mute the thread

**Comment by evilaliv3** [comment]
I think so.

As improval i'm adding a specific button/icon with written hide/show and with a specific icon Let me provide you a screenshot of the current interface.

**Comment by evilaliv3** [comment]
![Screenshot-2019-10-7 evilaliv3 gmail com](https://user-images.githubusercontent.com/217034/66314247-0b513580-e914-11e9-9c5c-362cdd1df80a.png)

![Screenshot-2019-10-7 evilaliv3 gmail com(1)](https://user-images.githubusercontent.com/217034/66314273-1015e980-e914-11e9-94d6-80bdc25a3f52.png)

**Comment by evilaliv3** [comment]
Here the reworked interface; i think we could close this as implemented :)

![Screenshot-2019-10-7 evilaliv3 gmail com](https://user-images.githubusercontent.com/217034/66314247-0b513580-e914-11e9-9c5c-362cdd1df80a.png)

![Screenshot-2019-10-7 evilaliv3 gmail com(1)](https://user-images.githubusercontent.com/217034/66314273-1015e980-e914-11e9-94d6-80bdc25a3f52.png)
