### ISSUE TITLE
3.6.11 Unhandled exception in backoffice when you try to remove a questionnaire assigned to a context

### ISSUE THREAD

**Issue by zazzati** [globaleaks/GlobaLeaks#2511]
3.6.11 Unhandled exception in backoffice when you try to remove a questionnaire assigned to a context

**Current behavior**

Login in to backoffice. 
If you try to cancel a questionnaire assigned to a context GL raise an exception

![image](https://user-images.githubusercontent.com/28624698/52342800-a1942b00-2a16-11e9-918b-ebd9e9daa79e.png)

**GlobaLeaks version:**

3.6.11

**Browser:**
Chrome

**Server Operating System and Version (if applicable):**
 Ubuntu(18.04)

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Thank you so much @zazzati for reporting the issue you encountered.

this is a known issue.

This exception is due to the fact that we implement an internal general check for the situation, that prevents you to remove any resource that is in use.

The error you are reporting is already considered as part of this ticket: https://github.com/globaleaks/GlobaLeaks/issues/2188

I'm closing your ticket just because of this duplication
