### ISSUE TITLE
Dynamic messaging when maximum number of Recipients is reached

### ISSUE THREAD

**Issue by SylvainFPU** [globaleaks/GlobaLeaks#2530]
**Current behavior**
With a Globaleaks setting where a maximum amount of Recipients is fixed, when the whistleblower reach this number there is nothing that tell him/her why he/she can't on another recipient. 

**Expected behavior**
A dynamic messaging with hint/error message "You've reached the maximum amount of recipients" in red.

**Steps to reproduce the problem or feature illustration**
On the "Recipient selection" page:
* Select the maximum amount of recipients (eg. 5)
* Select another one (eg. the 6th)
* Nothing happen, no reaction of the system, no hint to explain why you can't select more.

**What is the motivation or use case for changing the behavior?**
User experience

**GlobaLeaks version:**
Software version: 3.5.8

**Browser:**
All, but tested on Firefox Web Browser (Version 65.0.2-1) and Tor Browser (tor-browser-linux64-8.0.5)

**Server Operating System and Version (if applicable):**
Unknown

**Client Operating System and Version (if applicable):**
Ubuntu(18.04)

**Comment by evilaliv3** [comment]
Considering the current interfaces design we have identified to implement this ticket adding a string that communicate when the maximum number of recipients.

This is an example of the current feature on the [Publeaks](http://secure.publeaks.nl/) project:
![screenshot-2019-10-22_publeaks_-_safely_and_anonymously_share_information_with_the_media](https://user-images.githubusercontent.com/217034/67309601-6f6f1e80-f4fc-11e9-920f-52f7374a5948.png)

And this is an example of the messaging on the new designed interfaces, that are more compact in terms of UX/UI in order to work better for example on small screens.

![Screenshot_2019-10-22_10-44-22](https://user-images.githubusercontent.com/217034/67309369-0a1b2d80-f4fc-11e9-9262-45b37b22b5ec.png)
![Screenshot_2019-10-22_10-44-32](https://user-images.githubusercontent.com/217034/67309373-0e474b00-f4fc-11e9-9330-7c7dd355b8e9.png)

**Comment by SylvainFPU** [comment]
![ScreenshotPubleaks_Selection recipient](https://user-images.githubusercontent.com/46898563/69861267-53e3fa00-1298-11ea-99a2-6b6158206573.png)

@evilaliv3 are the boxes to click supposed to appear in black? It does not look great and and it makes unclear to the users that they can click on it UX wise

**Comment by evilaliv3** [comment]
Thank you @SylvainFPU, this is actually the new default style of bootstrap.

I reverted just this precise icon to the regular style.

Here is the output: 
![Screenshot_2019-11-30 Blow the whistle](https://user-images.githubusercontent.com/217034/69900101-e4413e00-136f-11ea-9c7a-72e20d8f757a.png)

**Comment by evilaliv3** [comment]
Closing as implemented.
