### ISSUE TITLE
receipt_regexp not used in the code - cannot configure receipt strength

### ISSUE THREAD

**Issue by qertoip** [globaleaks/GlobaLeaks#2545]
settings.py has receipt_regexp which is not used anywhere in the code so effectively there is no way to configure receipt password strength

**Comment by evilaliv3** [comment]
Dear @qertoip, i confirm that the parameter receipt_regexp is not used and wont be used.

Currently the password strenght is not configurable and enforced by the software by using advanced password steenght evaluation library:

It is possible that in the future we will make it possible to configure the parameters of the library as advanced settings of the software but this won't happen soon due to current privatization and time and resources constraints.

Which is your use case?

**Comment by evilaliv3** [comment]
Dear @qertoip,

ignore my previous answer that was out of topic due to a misunderstanding.

Yes, i confirm that that parameter is currently not used and that the receipt is currently generated as a sequence of 16 digits and that this parameter is not configurable.

Could you please clarify your need?

In the future we may consider making it possible to make configurable the set of character making them alphanumeric but for a large set of requirements i think that we wont change the number of characters used.

The consideration to be kept in mind are:
- security considerations subject to penetration tests that are periodically performed
- usability: in relation to internationalization digits works well but other character sets do not work as well.
- retro-compatibility: the platform has many features related to the precise receipt format and for retro compatibility reasons with a different format many would be the required changes to guarantee retrocompatiblity.

**Comment by qertoip** [comment]
Thanks a lot for the rationale.

The thing I am afraid of is potential password enumeration **despite** KDF and anti-brute force techniques employed. The password space seems small (10^16) / 53 bits of entropy. Attacker only needs to find a single password to be successful.

Anyway, I think I do understand your rationale. Please close if you believe there are other priorities.

**Comment by evilaliv3** [comment]
Thank you for your feedback and i'm really interested in your evaluations.

To complete my previous clarification (an thank you for digging that much in our specs/rationale) i would like to make you an additional consideration:
the valid receipts are limited in time by the fact that automatically the receipt expires three monts after the last access by  the whistleblower or the last update of the tip, so that basically receipts keeps expiring and rotating.
