### ISSUE TITLE
Some translations are not effective despite rebuild and restart

### ISSUE THREAD

**Issue by qertoip** [globaleaks/GlobaLeaks#2562]
**Current behavior**

For most texts it is enough to change the language json file, rebuild the frontend, and restart the backend.

However, some entries present in language json file are apparently not used and changing them has no effect.

Even completely removing the database won't help: the generic texts are still used to populate the new database.

The only way seems to be editing the database - but that does not propagate across tenants and deployments.

Example of such texts:

* "Blow the whistle" (the primary button on the #/ page)
* "Describe your submission in a few words." (the field labels)

**Expected behavior**

Any way to apply language json changes to texts that are kept in database.

**What is the motivation or use case for changing the behavior?**

Being able to fundamentally change globaleaks defaults - in a way that is effective for re-deployments and for future tenants within a deployment.

**GlobaLeaks version:**

3.7.1

**Comment by evilaliv3** [comment]
Hello @qertoip,

Actually this is not a bug in the software but it does just not work as you were expecting with two different reasons
- "Blow the whistle" this string is initialized by the software at tenant creation in the default of the tenant; so new tenants should have the up to date text while old tenants will continue to have the configured configuration. The configuration of this text is exposed in the "Advanced Settings" of the tenant and its configuration" so that you do not need to tweak the database to fix this but just reconfigure via the globaleaks web interface.
- Describe your submission in few words": this text is the text of a questionnaire and specifically of the default basic questionnaire. This questionnaire are not expected and any change will be overridden at every version bump by the new available 'default' questionnaire that we will make available in the software.

Please let me know if this answers your doubts
-

**Comment by qertoip** [comment]
Thanks so much for the prompts answer! That clarifies a lot.

Maybe these texts should be removed from the language json files (l10n/*) to avoid confusion?

Otherwise, the issue can be closed.

**Comment by evilaliv3** [comment]
I see. 

Right now every text of the application appear in the l10n files, but we will evaluate what we can do about it.

Thank you so much for your suggestions.
