### ISSUE TITLE
Submission management

### ISSUE THREAD

**Issue by mdwarf** [globaleaks/GlobaLeaks#2655]
**Current behavior**

I have configured my test account in order to try the service. I wrote a test submission and  recipient user regularly received submission notification (by email) and specific a submission identification code.

**Expected behavior**

Now, how can recipient user can access and manage whistleblowing submission? Where can he access to read and managed submission?
Thank you in advance

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

test platform: https://<mydomain>.try.globaleaks.or

**Browser:**

Firefox 68.0.1 64 bit

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Hello @mdwarf,

thank you for your message.

In order to access as recipient, log in at the /login URL with the following default credentials:
username: recipient
password: password

thos are the default user credentials generated by the system at its setup.

Actually this ticketing system is for bug reporting and feature requests. For next requests of this kind please consider the community forum: https://forum.globaleaks.org
