### ISSUE TITLE
Custom CSS not working properly

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2677]
I have modified the original css element in order to change the header colour
#HeaderBox {
  color: #FFF;
  background-color: #428bca;
}
With the following
#HeaderBox {
  color: #424242;
  background-color: white;
}
It worked beautifully so far (v3.10.8). 
It is not working as expected (v3.11.10). Header shows the default #428bca background.
OS Ubuntu 18.04
client chrome, edge on win 10.

One more element I have changed in css is working properly.

**Comment by evilaliv3** [comment]
@elbill: starting from release 3.11.8 we are using rltcss in order to make it possible that the layout works perfectly when a user is using an RTL language (e.g. arabic)

For this reason many css classes are now automatically postprocessed and have the [dir] prefix like:

```
[dir] #HeaderBox {
    background-color: #428bca;
}```

when you notice that the css is define as above, define your css with the additional [dir] as above.

This should fix your issue.

**Comment by evilaliv3** [comment]
Neverming @elbill, i've found a solution that will make it work your customization without any change.

I'm about to include in a release 3.11.12

**Comment by elbill** [comment]
Great @evilaliv3. I will wait for next release to upgrade.

**Comment by evilaliv3** [comment]
It's out @elbill !

**Comment by elbill** [comment]
It worked just fine. Thanks @evilaliv3
