### ISSUE TITLE
Analyze and re-integrate any modification from ISWeb's fork

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2691]
Current behavior
This ticket is to document, keep track and re-integrate into stock GlobaLeaks software all the minor and major features that has been developed by IsWeb as per https://www.isweb.it/pagina659_pawhistleblowing.html .

Expected behavior
It shall be possible to reproduce the configuration of ISWeb, giving a path to the public agencies using it, a way to upgrade in a smoooth way to latest GlobaLeaks release.

At first, the latest edition of IsWeb diffused modified GlobaLeaks must be obtained and clearly put into a GlobaLeaks fork archive. 
Secondly an analysis including a report on the modifications must be published.

After integration, all interested parties (ISweb, private and public companies using it, the private company that have done the modification) must be notified, including a public announcement of this outcome to prevent spread-diffusion of an unmaintained fork.

**Comment by evilaliv3** [comment]
@larrykind: Is there any patch that your team made that could be good to integrate withing the official release?

**Comment by larrykind** [comment]
Hi @evilaliv3, the patched fork is now fully deprecated but still in use, right now we are switching to official updated version. In the new version we haven't developed patches.

**Comment by evilaliv3** [comment]
Would you require any patch to be added to globaleaks, for the users that are using the old fork ?

**Comment by larrykind** [comment]
Since some istitutional customers are excluded from follow last ANAC specifications/directives, maybe the missing optional feature, that is on the old version, should be the pre-registration (with customizable form) of the whistleblower to limit in advance the access to the tenant with a login form, and the identity should be verifiable in some way. 
Most of private companies also require this feature.

With updated version this is workaroundable by forcing the identity submission, but that's not the same thing, because access to platform is still open and "prone" to fake submissions.

Do you think that's valuable?

**Comment by evilaliv3** [comment]
Thank you for the feedback @larrykind.

As i think you clearly understand, unfortunately we would not be able to implement such a feature because as you know the software tries to represent a model for best practices of whistleblowing in which pre-registration and authorization of the whistleblower is considered serious threat affecting the security and safety of the whistleblower and as well the anti-corruption process.

A pre-registration + the authorization implemented in many commercial software, would in fact enable pre-discrimination.
For which reason we could definitely not support official integration of such a feature.

For the moment i will just close this ticket as unneded, but please feel free to continue to provide any suggestion for improvement.
