### ISSUE TITLE
platform password registration non accepting double characters on new password setting 

### ISSUE THREAD

**Issue by AriDanikas** [globaleaks/GlobaLeaks#2719]
when one is asked to create a new password on platform the system will not accept double  symbols as part of a password . 

**Current behavior**
not accepting double symbol such as $$.

**Expected behavior**
be able to type any repeated symbol or provide a pop up warning that such action it is not allowed 

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**
when user adds the password and choses to repeat symbols in concesius as part of password  ,it is not accepted but there is no warning as to what he is doing wrong ,thus it creates confusion .

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Hello @AriDanikas, thank you for your feedback.

I just tried to reproduce your issue but i'm not able to get your same issue.

Would you please provide a screenshot?

```A valid password should be at least 10 characters long and contain a variety of characters including at least a lowercase character, a capital character, a number and a special character.```

Does your password meet these requirements?

thank you!

**Comment by AriDanikas** [comment]
ok so i proceed and created a new password:
1.if i enter the following 10 digit password : Aris1791$$  me that the password is weak and will not proceed.
if   i change the password to Aris1791$# then it proceeds :
![IMG_1906](https://user-images.githubusercontent.com/51485691/67967678-b224ab00-fc0e-11e9-97bf-7d38e7917b4a.jpg)
![IMG_1907](https://user-images.githubusercontent.com/51485691/67967690-b6e95f00-fc0e-11e9-9229-be5388a108bf.jpg)
so clearly a repeat of two identical symbols on a 10 digit password is not allowed
try it

**Comment by evilaliv3** [comment]
Thank you @AriDanikas, you are very helpful.

I rechecked the algorithm that is currently taking into account also repetitions and do not allows any. (in other words it is currently requiring 10 different characters)
For example it would not allow Aris1791## as well.

Given the fact that the password policy is really strict i'm going to modify it slightly allowing up to 2 repetitions. (in other words i'm going to modify it slightly requiring only 8 different characters so that a password like Aris17##$$ will be still accepted as secure and will be slightl more usable for the user.

Thank you!

**Comment by AriDanikas** [comment]
precisely my thoughts .We want the user to simplify his efforts to register an account so the instruction was not as clear thus the confusion .many people like to repeat characters on a password in order to remember it :) so following the 10 digit instruction there was confusion as to not be able to repeat characters
