### ISSUE TITLE
Post activation email not showing username and password

### ISSUE THREAD

**Issue by vodkina** [globaleaks/GlobaLeaks#2723]
See attached picture.
Actually, this behaviour is shown in Czech language, but it could be affecting other languages too. (could be related to this issue: https://github.com/globaleaks/GlobaLeaks/issues/2713)

<img width="582" alt="Screenshot 2019-11-13 07 43 06" src="https://user-images.githubusercontent.com/2151323/68740009-71ec0200-05ea-11ea-9c74-752808701bba.png">

**Comment by evilaliv3** [comment]
@vodkina: This is actually not a bug but a mistake in the translations in CZec that i corrected time ago.

To fix this you should reset the mail templates of the EAT setup to the default and up to date translations; You can do this in "Notification settings", tick th box "Reset mail notification templates" and press save. This will reset all mail templates notifications in every language to the default.

The issue is that in the previous versions {Password} was translated in {Heslo} so that globaleaks could not anymore find the variable to replace.
