### ISSUE TITLE
Globaleaks behind reverse proxy

### ISSUE THREAD

**Issue by xjobex** [globaleaks/GlobaLeaks#2736]
Hi, I would like to expose our Globaleaks behind our Nginx reverse proxy (that resides on a separate virtual machine), like we do with other websites. I tried to configure Nginx as I usually do with other websites:

    ...
    location /globaleaks/ {
        proxy_pass http://globaleaks.internal/;
    }
    ...

but I receive an HTTP error 400 (Bad request) when I try to open the homepage. Direct access to Globaleaks works normally.
Are there any special configurations needed to put Globaleaks behind an Nginx reverse proxy?

I attached Globaleaks log files as requested on forum.globaleaks.org
[access.log](https://github.com/globaleaks/GlobaLeaks/files/3921045/access.log)
[globaleaks.log](https://github.com/globaleaks/GlobaLeaks/files/3921046/globaleaks.log)

**Comment by evilaliv3** [comment]
@xjobex: thank you for your feedback.

I just verified your log files and in my opinion the issues could lie in the fact that you have not configured the hostname inside globaleaks.

e.g. just set globaleaks.site.it as you have used it in your reverse proxy configuration.

GlobaLeaks in fact is giving you a 400 error because it do not recognize that hostname.

**Comment by fpietrosanti** [comment]
We may gives an error, in case of 400 code, that self explain the error,
like “hostname %s has not been found/configured on the system. Please check
in the administrative interface that %s is properly configured” ?



Sent from mobile

On 4 Dec 2019, at 15:26, Giovanni Pellerano <notifications@github.com>
wrote:

@xjobex <https://github.com/xjobex>: thank you for your feedback.

I just verified your log files and in my opinion the issues could lie in
the fact that you have not configured the hostname inside globaleaks.

e.g. just set globaleaks.site.it as you have used it in your reverse proxy
configuration.

GlobaLeaks in fact is giving you a 400 error because it do not recognize
that hostname.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/globaleaks/GlobaLeaks/issues/2736?email_source=notifications&email_token=AAF4CO3C23TP2H2ZY4GVY6LQW64Y3A5CNFSM4JVFNQRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEF5GGCA#issuecomment-561668872>,
or unsubscribe

**Comment by evilaliv3** [comment]
Actually not @fpietrosanti if you ask google to give you p0rn.com it do not answers you: Check the interface and check that p0rn.com is properly configured. Why should we?

Its is also called as reflected xss vulnerability and could be exploited in many way.

**Comment by fpietrosanti** [comment]
The software, in the presence of error, should indicate the cause of the
error.

If in that case is not providing a resolution path but just a unknown
error, then it should be improved

Sent from mobile

On 4 Dec 2019, at 18:53, Giovanni Pellerano <notifications@github.com>
wrote:

Actually not @fpietrosanti <https://github.com/fpietrosanti> if you ask
google to give you p0rn.com it do not answers you: Check the interface and
check that p0rn.com is properly configured. Why should we?

Its is also called as reflected xss vulnerability and could be exploited in
many way.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/globaleaks/GlobaLeaks/issues/2736?email_source=notifications&email_token=AAF4CO5QAON7GV34PT5FRGTQW7VCPA5CNFSM4JVFNQRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEF55P5A#issuecomment-561764340>,
or unsubscribe

**Comment by evilaliv3** [comment]
I see what you mean. In this case the proper message is to answer: ```Virtualhost not found```.

**Comment by xjobex** [comment]
> @xjobex: thank you for your feedback.
> 
> I just verified your log files and in my opinion the issues could lie in the fact that you have not configured the hostname inside globaleaks.
> 
> e.g. just set globaleaks.site.it as you have used it in your reverse proxy configuration.
> 
> GlobaLeaks in fact is giving you a 400 error because it do not recognize that hostname.
> 
> As soon that you set it get sure to restart globaleaks with `/etc/init.d/globaleaks restart`; the restart is required due to a bug that we have just fixed and for which we still need to issue a new package.
> 
> Please let me know if you need further assistance.

Hi, setting the hostname in Globaleaks options solved the problem, now the site is reachable.
Thank you!

**Comment by evilaliv3** [comment]
After long evaluation we considered to not support this use case.

Current design of GlobaLeaks considers to always terminate the TLS connection on the backend implementing in an end-to-end fashion from the browser of the whistleblower to the server and opening explicitly to the possibility to add revers proxies in between would break most of the assuptions of the applications.
