### ISSUE TITLE
When basic authentication is enabled the 2FA authentication doesn't work properly

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2738]
**Current behavior**
When basic authentication is enabled the 2FA authentication doesn't work properly, as the basic authentication get asked again.

To reproduce the issue:
- Enable basic authentication
- Enable 2FA authentication
- Access the globaleaks site
- Insert login/password of basic authentication
- Insert username and Password, press enter
- Insert 2FA, press enter
(At this point the basic authentication prompt again in a unexpected way)

**Expected behavior**
Once a user session has been authenticated with "basic authentication", any action on the application, should not trigger it again.

**Comment by evilaliv3** [comment]
This behaviour is probably browser dependent.

Which has been the browser used during your experimentation?

**Comment by fpietrosanti** [comment]
Using Chrome, latest version on Windows

**Comment by evilaliv3** [comment]
The bug lies in the following:
- I need a code to communicate the client that i need to perform the two factor autentication and i selected 403
- Every HTTP return in the family 4XX invalidates the basic authentication

I found a quick and dirty fix that is to use a code of the family 3XX. This is not standard but what is a standard in this case anyway?
