### ISSUE TITLE
Submit Button not working

### ISSUE THREAD

**Issue by manojt21** [globaleaks/GlobaLeaks#2741]
**Current behavior**
When i click submit button. system is not doing anything and not giving any error message

**Expected behavior**
System supposed to confirm with the submission number.

**Steps to reproduce the problem or feature illustration**
https://test123.try.globaleaks.org/#/ 
click on blow the whistle
enter short title and full description and hit submit

the submit button doesn't works

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**
<!--
Indicate which browsers exhibit the bug and their version
chrome, firefox, Microsoft Edge, Safari

**Server Operating System and Version (if applicable):**

**Client Operating System and Version (if applicable):**
 Windows 10

**Comment by evilaliv3** [comment]
@manojt21: I see that on your demo instance you have currently removed the default recipient.

In order to configure it properly, create a new receipient and then inside the context configuration you have to associate your recipients to the context.

I'm closing the issue as the reason for the failure is know but please let me know if any clarification is needed.
