### ISSUE TITLE
Enhance questionnaire print

### ISSUE THREAD

**Issue by emanuelegreco** [globaleaks/GlobaLeaks#2745]
**Current behavior**
Each questionnaire can be print on paper and exported to PDF.
Print is quite poor, since it replies the page in b&w, look at [original Globaleaks print](https://github.com/globaleaks/GlobaLeaks/files/3939218/Original.Globaleaks.print.pdf)

**Expected behavior**
Users expect a better document, in case they want to save, print or share the data recorded in Globaleaks.

**Suggested improvement**
I suggest this CSS improvement so that [Original print](https://github.com/globaleaks/GlobaLeaks/files/3939218/Original.Globaleaks.print.pdf) can look like [Modified print](https://github.com/globaleaks/GlobaLeaks/files/3939224/Modified.Globalieaks.print.pdf)

`@media print {
[dir] .card 	{
	border:none; 
	}
[dir] .card-header {
	background-color: white;
    	font-size: 1.6em;
	color: navy;
}
.fa, .fas, .btn {
	display:none;
}
.nested{
padding: 0px;
}
.question-label, .fieldLabel {
    font-style: italic;
    font-size: 18px;
}
}
`

It applies just in print case, removes borders and useless buttons, makes the titles bigger and apply little differentiation between questions and answers.

This work can be made a lot better, but the CSS posted works and is effective.

**Comment by evilaliv3** [comment]
Thank you @emanuelegreco 

Would you please clarify around the suggestion and the choices of your code?

While implementing any single feature we need to verify the browser compatibility and the rationale to not affect other users.

For example i see that you have hidden completely any icon or button of the application but this is probably a choice that should be done carefully because it completely alters the real interface.

I recognize the value of your feedback but probably we should try to understand how to better implement a print format with the data that is valuable to print and leave the current print interface as it is?

**Comment by emanuelegreco** [comment]
Hi @evilaliv3 ,
this issue is not a bug, but just a suggestion based on my experience, in which user asked for a document-like print instead of a screen-shot. 

Actually I don't know if changing printig feature is an improvement even for other Globaleaks projects. 
If the answer is 'yes' we can inspect how to do this.

In a document-like context any icon or button is just annoying and has no meaning. 
That's why  I've hidden them (look at the difference between the documents attached).

I posted that CSS code sample because it allowed me to reach the result posted as attachment, that was accepted by users. 
I understand that this code could be written in a better and clearer way, knowing exactly the meaning of each CSS class and testing browser compatibility.
