### ISSUE TITLE
Terms of service attachment not showing properly 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2763]
**Current behavior**

Terms of service attachment not showing properly. In MS Edge not showing at all. Chrome and opera just showing the upper band of the pdf. Left click and download on the link works fine. 

**Expected behavior**

It should show the whole page with a scrollable pdf file.

**Steps to reproduce the problem or feature illustration**

https://testme2.try.globaleaks.org/s/meletiplanet2016.pdf
![PowerPoint Presentation - Google Chrome 23_1_2020 12_06_16 μμ](https://user-images.githubusercontent.com/23246886/72975069-d7255600-3dd8-11ea-8268-c94a8506b089.png)

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

Check whether this is still an issue in the most recent version of the software
v 3.11.61  & 3.11.62

**Browser:**

Indicate which browsers exhibit the bug and their version
Chrome, opera on windows (showing partial)
edge (not showing at all)

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
@elbill: Thank you for your feedback.

I just tried to open the link (testme2.try.globaleaks.org/s/meletiplanet2016.pdf) with firefox and chrome and i di not see any issue.
Is it possible that you have problems with your network or firewall?

**Comment by elbill** [comment]
Firefox on windows worked fine.
Chrome and opera on windows did not. That is on the same network.
Tried chrome on a different pc and is the same.

**Comment by elbill** [comment]
What is quite strange is that it says on the tab "powerpoint presentation".

**Comment by elbill** [comment]
@evilaliv3 I also tried on a different network (mobile tethering) still no luck.

**Comment by evilaliv3** [comment]
Thank you @elbill, actually i've retried it and i'm able to reproduce the issue.

As for "powerpoint presentation" i found it inside the doc metadata as the title of the document.
I suspect that this is due to the specific PDF and that the different browsers are handling it differently.

Have you tried with different PDFs to see if the behaviour is the same?

Or opening the file indipendently from the platform?

**Comment by elbill** [comment]
PowerPoint presentation was the title of the PDF document. With a different
pdf it was different.

**Comment by evilaliv3** [comment]
I see, actually i'm quite confident that its an issue with this PDF and its visualization with the browser but is unrelated from the platform

**Comment by elbill** [comment]
@evilaliv3 this is very strange.
I have the same results with a vodafone manual.
https://testme2.try.globaleaks.org/s/vodafone.pdf

**Comment by evilaliv3** [comment]
@elbill: Bug identified!

Actually the issue is related to the content security policy.
The browser seems to inject some CSS to load the PDF and that is blocked for security reasons by our rules.

I will now try to understand if we can force the browser to download the file.

![Screenshot_2020-01-23_16-28-25](https://user-images.githubusercontent.com/217034/72998019-7d835280-3dfd-11ea-9639-355900c31bb5.png)

**Comment by evilaliv3** [comment]
Reference for the issue: https://bugs.chromium.org/p/chromium/issues/detail?id=271452

**Comment by evilaliv3** [comment]
Actually what we could do is to get sure that the link in the application when clicked forces a file download, this way we could get sure that the user is able to download the file.

This is the only way to be user that exploit code is not injected and runned in the context of the website.

**Comment by elbill** [comment]
It seems very inconsistent.
The chrome issue may have affected the pdfs when downloading since for some
pdfs it is working fine, some others not?
internet explorer 11 and firefox are not affected, the ones using the
chromium engine are. Edge has some issues as well.
The funny thing is theta you can still see part of the file. On edge it
does not show at all.
Downloading the file may be the only safe solution for the moment.

**Comment by evilaliv3** [comment]
@elbill: The reason is the following: 

1. we enforce some CSP policy where we block the possibility to include inline CSS styles
2. any correct CSP engine should block, but the way the block is implemented vary: some show the content blocking also the feature to be blocked, some block completely the access to the file.

I'm going to issue a patch where the browser will force the download of the file when the user will click on the link. For what related users copying the link and opening it in a new tab there is actually not that much that we could do.

Consider that this prevents many attacks to happen where a fake whistleblower could upload malicous CSS or JS to try to exfiltrate information so this protections is really necessary in this context.
