### ISSUE TITLE
exception in v 3.11.68 and 3.11.67

### ISSUE THREAD

**Issue by marangiom** [globaleaks/GlobaLeaks#2765]
Hi
we are receiving some mails from our whistleblowing system
-------------------------------
twisted.web._newclient.ResponseFailed 
   L{ResponseFailed} indicates that all of the response to a request was not
   received for some reason.

   @ivar reasons: A C{list} of one or more L{Failure} instances giving the
       reasons the response was considered to have failed.

   @ivar response: If specified, the L{Response} received from the server (and
       in particular the status code and the headers).

Traceback (most recent call last):

 File "/usr/lib/python3/dist-packages/globaleaks/jobs/job.py", line 49, in run
   yield self.operation()

twisted.web._newclient.ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
-----------------------------------

what is the error and what can we do to solve it?

thanks
Marcello

**Comment by evilaliv3** [comment]
Thank  you for reporting this @marangiom.

The exception that you are reporting is related to a connection failure in one of the periodic task (could be mail notification, update check for example) but is not related to your specific software version and i expect it to be transient.

We will improve the detection of this in the upcoming versions so that it will be more easy to identify the failure.

At which hour of the day are you receiving it? Can you correlate it to the job/time that you read from the admin panel inside System overview?

**Comment by marangiom** [comment]
Hi @evilaliv3 
the emails occurred between 5:00 and 10:00 AM.
I have no anomalies nor activities logged into the system; how can I retreive the info you asked for?

**Comment by evilaliv3** [comment]
Thank you @marangiom;

My guess is that among 5 and 10 am the resource https://check.torproject.org/exit-addresses was not available and globaleaks was not able to fetch the list of exit nodes.

We will fix this condition on a next update were to implement caching an just logging the situation without triggering an email notification.

**Comment by evilaliv3** [comment]
Closing the ticket as the issues resulted a temporary failure of an extern resource and many are the tickets that already deals with proper logging.
