### ISSUE TITLE
errors on versione 4.0.0

### ISSUE THREAD

**Issue by marangiom** [globaleaks/GlobaLeaks#2783]
hi
since we updated to version 4.0.0 I keep receiving the following error:
Platform: Whistleblowing Regione Puglia
Host: xxxxxxxxxxxxx
 (edznpopefjctqidtgvz2btgjkqzvljwii5g6u2segqudr6vfvuti7tyd.onion)
Version: 4.0.0

twisted.internet.error.ConnectionRefusedError Connection was refused by other side

Traceback (most recent call last):

 File "/usr/lib/python3/dist-packages/globaleaks/jobs/job.py", line 49, in run
   yield self.operation()

twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.

is there something misconfiguration?
thanks
M

**Comment by evilaliv3** [comment]
No @marangiom, actually its all fine. 
The mail that you received are related to the fact that your setup was finding our repository down.

In fact today we an issue in the release 4.0.0 ans we temporarely disabled the repository to stop people to update while fixing it. The issue that was preventing authentication in 4.0.0 is now fixed in 4.0.2.
