### ISSUE TITLE
labels migrated from a previous version, are not editable

### ISSUE THREAD

**Issue by jbitlloch** [globaleaks/GlobaLeaks#2801]
**Current behavior**

I'm installing the current version of globaleaks from the scratch,  but incorporating previous data from a previous installation.

the issue is :  previous labels are shown in the submission list, but when I enter inside a submission, the label doesn't appear. 
in the list appear the old ones, it seems tjat old and new labels are recorded in different places

**Expected behavior**

label in submission list and inside a submission (for the same receiver) should be the same

**Steps to reproduce the problem or feature illustration**

1)have an old install with submissions and labels
2)do a new install, copying previously the  previous data
3)enter to he new instalation and enter to a submission that had a label
4)observe  that inside the submission, there isn't label.  change the label
5)observe that in the submission list still appear  the previous label

I can give you a direct access to a an instance whith this behaviour

**What is the motivation or use case for changing the behavior?**

it's an issue

**GlobaLeaks version:**

new version 4.0.4
data extracted from version:  3.0.26

**Browser:**

Chrome

**Server Operating System and Version (if applicable):**
 
Ubuntu

**Client Operating System and Version (if applicable):**

Ubuntu

**Comment by evilaliv3** [comment]
Thank you Joan, this is acutally due to feature: https://github.com/globaleaks/GlobaLeaks/issues/2727

Basically in previous releases the Label was personal for each recipient.
In the current inversion instead it is now possible to configure the system to use shared Labels among each recipients.

Up to you are two choices:
- You could preserve the possibility to have private labels (you can enable this feature in Advanced settings) and the system will work like before
- You can swich to the new mode that uses shared labels by defaults but you will require to make a copy of the existing labels and apply them to each tip.

**Comment by jbitlloch** [comment]
great,  
I solved it preserving the old behaviour

in case of migrating from previous versions, may be it's prefereble to have by defauld marked the old behaviour.

thanks

**Comment by evilaliv3** [comment]
Thank you @jbitlloch, I will change the migration script in order to preserve this behaviour.
