### ISSUE TITLE
Make it possible to export all the reports at once

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2824]
This is a new feature proposal. While there is the possibility to delete multiple submissions, there is no possibility to export multiple submissions. Is there any reason behind this. ISt ehre some other way to have access to submissions and import to another case management system or softwares such as excel?

**Comment by evilaliv3** [comment]
Thank you @elbill for opening this discussion.

both the two features that you are discussing are interesting and have been as well previosuly discussed.

1) As for the integration (as export) with external case management you read active work on: https://github.com/globaleaks/GlobaLeaks/issues/1223
2) As for the integration (as import) with external case management we never discussed this possibility because actually as far that we know no opensource case management exists that would justify such an effort.
3) As for the export in other formats as well it has been previously discussed but there have been currently no implementation due to missing funding. as well we need to finalize the analysis of the open formats that could be worth it to use (e.g. .xlsx will be preferred while simple xls wont be implemented); you find preliminary discussions here and i invite you to add your considerations and suggestions: https://github.com/globaleaks/GlobaLeaks/issues/1413
4) The topic of export of multiple submissions has been currently is considered but still not implemented due to resource constraints and priorities

I will rename the ticket to deal only with topic 4; if you can for the next time would you please open different tickets for different ideas and check if the topic you are proposing is already discussed on existing tickets? Thank you so much for your support and continue feedback!

**Comment by evilaliv3** [comment]
Closing the ticket as the feature was implemented and included in release 4.1.10

**Comment by elbill** [comment]
Great! Thanks @evilaliv3 . One small issue. Context name appears like this:
ID: 3
Date: Tuesday 30 March 2021 07:57 (UTC)
Label: NON URGENT
Status: Closed (Inadequate evidence)
Context: {ContextName}

**Comment by elbill** [comment]
@evilaliv3 have you seen this or should I open a new issue?

**Comment by evilaliv3** [comment]
Seen thank you! For now you can keep this as it is. In general it is more useful if you could open new tickets as it helps us handinling and documenting the bugfixing (e.g. interconnection the change to the changelog with links that clearly identify the issue).

Thank you!
