### ISSUE TITLE
Translations and Text Customization not displaying (Bosnian)

### ISSUE THREAD

**Issue by vkotek** [globaleaks/GlobaLeaks#2840]
**Current behavior**
When adding Text Customization to text such as "Have you already filed a report? Enter your receipt." the original English text is shown on the portal when language is set to Bosnian. Changing the text directly in the bs.json file does not have any effect on the page either (the translation in the file was the same as original text, English).

**Expected behavior**
The Bosnian translation should be visible after adding it to Text Customization or after editting the bs.json file.

**Steps to reproduce the problem or feature illustration**

1. Add Bosnian Language
2. Navigate to homepage and check translation of "Have you already filed a report? Enter your receipt."
3. Try to add custom translation to "Have you already filed a report? Enter your receipt."
4. Navigate to homepage and check if text is translated

**GlobaLeaks version:**
GlobaLeaks version: 4.0.18
Database version: 52

**Browser:**
Chrome, Safari, Internet Explorer

**Server Operating System and Version (if applicable):**
Ubuntu 18.04.4 LTS

**Client Operating System and Version (if applicable):**
Windows 10

**Comment by evilaliv3** [comment]
Thank you @vkotek this seems to be just a bug on the precise text that due to a bug seems to contain the word "submission" instead of "report" that is a recent change we applied. Let me check on it and fix it.

P.s.: i just granted you permissions on Transifex so that if you like you can now complete existing bosian translations of GlobaLeaks and as soon that they are completed we may proceed issuing a new release.

Thank you!

**Comment by vkotek** [comment]
Thanks for the fast response!! There are other texts that aren't translating but I just checked and they all seem to contain the word "report" so you might be onto something there! 👍

**Comment by evilaliv3** [comment]
Hello @vkotek , i think to have identified the reason of the problem.

Bosnian translation fallen below 50% and for this reason was a language to be removed. When this happened we did not remove it because we suspect that the language could be in use by some projects but saddenly the software is not fetching new translations.

Do you mind to try to complete them? I will commit to issue a new release as soon that you reviewed it. (p.s. if you like the idea i may set you as coordinator for the language so that you can revise as well existing translations and eventually invite other of your team members to support this activity; i invite you as well to join our slack at: slack.globaleaks.org)

**Comment by evilaliv3** [comment]
@vkotek: I just verified that this applies as well to Slovenian, Albanian, Ukrainian, Serbian. By any chance you or some of your teammates may support the completion on this languages on transifex?

**Comment by vkotek** [comment]
Hi @evilaliv3, let me check with my colleagues as I am getting the translations from them, I am sure we can get it well above 50% for Bosnian! Unfortunately I personally do not speak any of these languages. The translator role will be enough as I'll get the translation from my colleagues on .po format.

So will this resolve the problem even if currently some text translations for Bosnian are working while some are not?

Thank you for the really great support!!

**Comment by evilaliv3** [comment]
Yes it will work!

**Comment by vkotek** [comment]
Hi @evilaliv3, I've  just uploaded the Bosnian translation to transifex with near 100% completion.

**Comment by evilaliv3** [comment]
I'm going to issue a release 4.0.19 including the new bosnian translations so that you could eventually ask your translators to check them live and see if they would like to apply any revision.

thank you @vkotek

**Comment by vkotek** [comment]
Hi @evilaliv3, when can I expect release 4.0.19 to be available? Thanks!

**Comment by evilaliv3** [comment]
Thank you @vkotek, we are proceding with some retesting that hopefully will conclude today with the release!

**Comment by evilaliv3** [comment]
@vkotek: Release 4.0.19.

When you like you can proceed with your review. Eventually you can already test it live on try.globaleaks.org
