### ISSUE TITLE
Postpone problem ?

### ISSUE THREAD

**Issue by alessandro-battezzati** [globaleaks/GlobaLeaks#2872]
**Current behavior**
When you try to postpone a report, the proposed date is the current one and not a date in the future

![image](https://user-images.githubusercontent.com/60136048/85056341-5ad44a80-b19f-11ea-8b3f-b8f55826769a.png)

**GlobaLeaks version:**
4.0.19

**Browser:**
Chrome last version

**Comment by evilaliv3** [comment]
Dear @alessandro-battezzati ,

By the current implementation the postpone date implement the renewal of an entire period.
Supposing you received a submission today, that will will expire in 3 months, if you postpone it today the day of expiration wont be different because will be set to be in 3 months from today.

I hope this clarify what you are experiencing.

Please let me know if you need any other clarification.

**Comment by alessandro-battezzati** [comment]
thx
