### ISSUE TITLE
Cittadini Reattivi website programming with participatory map and whistleblower page

### ISSUE THREAD

**Issue by gloriaschiavi** [globaleaks/GlobaLeaks#2873]
I’m writing here following your message on the gl-support-ita chat on Slack prompting us to use the ticketing service on Github to put forward our requests. 

Cittadini Reattivi is planning to set up a new website because the current one is constantly attacked by bots and the layout doesn’t work well on mobile, plus we need to restore the whistleblowing page. 

Our new website needs to include different features/sections:
-one standard part for news/blog
-a participatory map where registered users can add their own project
-a page for whistleblowers.

We understand that putting together these three parts -or the two parts, the map and the whistleblowing- is not simple.

We have a programmer who is setting up the website, which will then be passed on to you for the security features. 

Unfortunately, at the moment the programmer is delaying a lot and he doesn’t seem to have time to work on our website, but on our side it is getting quite urgent lo fix it. 

Maybe someone in your network can assist us with programming and then you also take charge of the security/whistleblowing part. The programmer was working probono, but considering the urgency, we can invest something.

Thanks for your help, we look forward to see what can be achieved.

Gloria Schiavi and Rosy Battaglia
for Cittadini Reattivi APS 
ITALY

**Comment by evilaliv3** [comment]
Dear @gloriaschiavi, thank you for writing here following up my request. I recognize that with my message I was probably i did not express well the context of use. The GlobaLeaks team infact deals just with the development of the software and of the documentation on its uses in order to facilitate the adoption and this specific ticketing system only deals with Globaleaks as software and should be used just for discussiong improvements to the software in relation to what it does wrong (bugs) or what it still is not able to provide in relation to other commerical whistleblowing softwares (software features).

Rosy already clarified my your needs and i will be contacting you in a little with some updates.

Please feel free to write here eventually as soon that by using the software you will have specific feedback on it. Thank you!

**Comment by gloriaschiavi** [comment]
Sorry! We definitely misunderstood the request. Thank you anyway and speak soon.

**Comment by evilaliv3** [comment]
That's no problem! Thank you!
