### ISSUE TITLE
Problems to decrypt files

### ISSUE THREAD

**Issue by taniatabilo** [globaleaks/GlobaLeaks#2877]
Dear all:
I hope you are well. I am writing to you because I had some problems on my work computer and I am using my personal computer, but on this computer I do not have an application installed to decrypt the files that arrive in PGP format in the complaints box. I tried downloading Kleopatra and creating my key, but it doesn't allow me to decrypt files. Could you help me with that, please?
Thank you very much.
Best.

**Comment by evilaliv3** [comment]
Dear @taniatabilo, thank you for writing here (feel free to reach us directly via email on this details).

Actually ithe software you have installed is correct (kleopatra), but in order to decrypt your files you don't need to create a new key.

What you need to do is to export your original key from your working computer and import it on your personal computer.
In fact files are encrypted with the key that is stored on your original working computer. 

What you should do is:
- Open Kleopatra on your original work computer
- Start Kleopatra and right click on your certificate, under the Trusted Certificates store.
- Select Export Secret Keys.
- Click on the disk icon to the right of the text box, leave Passphrase Charset as default.
-  Chose a location to save the file putting it on a USB stick.
(i took this exact steps from a manual but on the up to date version of kleopatra they may vary).

After this, plug your USB stick on your personal computer and look for the import function on Klepopatra.
After you finish i advise you to store the USB key in secure save in an hidden location. You will need that key to recover your files and any person that will get access to that key would be able to access the data. If you received any recommendation by your original trainers on globaleaks please follow them or ask for more specific advices.

**Comment by taniatabilo** [comment]
Dear Giovanni:

Thank you so much for your permanent help.
Best.


[http://www.chiletransparente.cl/1.jpg]
Tania Tabilo Morales
Coordinadora oficina Asistencia Legal Anticorrupción - ALAC
Chile Transparente<http://www.chiletransparente.cl/>
Capítulo Chileno de Transparencia Internacional
+56 9 3020 6966
Merced 152, of 102, Santiago
https://denunciacorrupcion.cl/


________________________________
De: Giovanni Pellerano <notifications@github.com>
Enviado: jueves, 23 de julio de 2020 2:14
Para: globaleaks/GlobaLeaks <GlobaLeaks@noreply.github.com>
Cc: Tania Tabilo (TI CL) <ttabilo@chiletransparente.cl>; Mention <mention@noreply.github.com>
Asunto: Re: [globaleaks/GlobaLeaks] Problems to decrypt files (#2877)


Dear @taniatabilo<https://github.com/taniatabilo>, thank you for writing here (feel free to reach us directly via email on this details).

Actually ithe software you have installed is correct (kleopatra), but in order to decrypt your files you don't need to create a new key.

What you need to do is to export your original key from your working computer and import it on your personal computer.
In fact files are encrypted with the key that is stored on your original working computer.

What you should do is:

  *   Open Kleopatra on your original work computer
  *   Start Kleopatra and right click on your certificate, under the Trusted Certificates store.
  *   Select Export Secret Keys.
  *   Click on the disk icon to the right of the text box, leave Passphrase Charset as default.
  *   Chose a location to save the file putting it on a USB stick.
(i took this exact steps from a manual but on the up to date version of kleopatra they may vary).

After this, plug your USB stick on your personal computer and look for the import function on Klepopatra.
After you finish i advise you to store the USB key in secure save in an hidden location. You will need that key to recover your files and any person that will get access to that key would be able to access the data. If you received any recommendation by your original trainers on globaleaks please follow them or ask for more specific advices.

**Comment by evilaliv3** [comment]
You are welcome Tania!

Please let me know as you will have managed to solve your problem. Thank
you!
