### ISSUE TITLE
Email notification link in user's email address change malfunction

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2880]
**Current behavior**

1) If an user changes his email address with a non existing one, and then with an existing one, the first notification email will never be received. The second one will. In the second email, if email confirm link is clicked, server says "link expired or not valid".
After first link expire time will be the second link active? How much email link expire lasts?

2) If the above failure link in the browser (that is rewritten as route) is simply manually changed replacing "failure" with "success", server reponds "email address is validated". User's email address is changed with the new one.

**Expected behavior**

1) If user modifies his email address more and more times, every clicked link should validate the email address.
2) The link (token?) should be no more active after email validation

**Steps to reproduce the problem or feature illustration**

1.1. Log in as user and try to change user's email address with a non existent one
1.2. No email will be received for that email change, system tries to send it. - Email address will never be changed.

2.1. change user's email one more time with a working one.
2.2. Email with link confirm is received
2.3. Clicking link for new email activation makes the system respond "link expired or not valid".
2.4. if the email validation route in the browser is modified by replacing "failure" with "success", system responds "email address is validated"
2.5. Log out and log in - email address is changed with the new one.

**What is the motivation or use case for changing the behavior?**

1) Links for email validation shoud work when regenerated and older ones shoud not work
2) Validation routes in the browses should be one-shot

**GlobaLeaks version:**

4.0.39

**Browser:**

Firefox 78

**Server Operating System and Version (if applicable):**
 
debian 10.3

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment]
Thank you @larrykind, i would kindly ask you to repeat your procedure because i just tried it and i was not able to reproduce it.

Actually i've as well looked at the code and here is what the platform does:
- anytime you try an email change a new token is emitted and the previous one is invalidated (the database can store just one email change token)
- if you change it multiple times only the last token will be valid for validating the last email
- any token correctly used will result in being deactivated (i suspect you may have experienced some strange browser cache issue as configurmed that your token was correctly used)

**Comment by evilaliv3** [comment]
@larrykind ?

**Comment by larrykind** [comment]
@evilaliv3 I'm sorry for my late reply.
Did some retry without experiencing the problem. Don't know why. Anyway ticket can be closed. thanks.
