### ISSUE TITLE
Trigger conditions do not work for template questions

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2881]
**Current behavior**
In a questionnaire two selection box questions that have been input from templates can not trigger each other. 

The Trigger conditions appear instead
 question1: option1 (Sufficient)
appears like
: option1 (Sufficient)

**Expected behavior**
I would expect the triggering to work in a similar way to non-template questions.

**Steps to reproduce the problem or feature illustration**
Make two selection box question templates, create a questionnaire, input 2 questions from the templates, and try one to trigger the other. It is actually the question that triggers that causes the issue. A non-template question can trigger successfully a question that has been imported from the template. 

**GlobaLeaks version:**
4.0.49

**Browser:**
chrome

**Server Operating System and Version (if applicable):**
Ubuntu(18.04)

**Comment by evilaliv3** [comment]
Thank you @elbill from your feedback.

Technically speaking this would be not duable because actually by design a question template can only contain trigger to questions contained within the template. This is how template are ment.

If you have this requireement probably you need to re-design your two question templates merging them into a singel question template.

Please let me know if you have any question.

**Comment by elbill** [comment]
@evilaliv3 thanks for the clarification. Do you mean merge them into a group of questions?

**Comment by evilaliv3** [comment]
In a single template of type group of question. I confirm.

This is needed because from within a template you can reference only templates.

**Comment by elbill** [comment]
That worked. Thanks!
