### ISSUE TITLE
Importing questionnaires gives an error

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2902]
**Current behavior**

Trying to import questionnaire, also **within same version** gives an error . Attached the screenshot trying to export and import "Default" questionnaire.

![import_quest](https://user-images.githubusercontent.com/61267901/94530795-e26c3380-023b-11eb-87d6-07610966180b.JPG)

**Expected behavior**

Importing questionnaires, between the same and different platform versions should not throw errors.

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

v.4.0.54

**Browser:**

firefox 81

**Server Operating System and Version (if applicable):**
 

ubuntu bionic

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment]
Than you @larrykind for getting back to us on this.

Actually the current implementation gives error anytime you load a questionnaire that is already loaded onto the same system or to a different tenant. In order to be able to load the same questionniare twice please and edit it please use the function 'clone'.

**Comment by larrykind** [comment]
ok @evilaliv3 got it. Thanks.
