### ISSUE TITLE
 ability of administrator to change user passwords

### ISSUE THREAD

**Issue by alessandro-battezzati** [globaleaks/GlobaLeaks#2906]
**Current behavior**

The ability of dministrator to change user passwords seems disabled. 

The option in the configuration is grayed out and disabled.

![image](https://user-images.githubusercontent.com/60136048/96281802-2603c300-0fda-11eb-8e26-025c1d9fc5db.png)

**Expected behavior**

Force users' passwords

**GlobaLeaks version:**
Versione del software: 4.0.19

**Browser:**
Chrome, Firefox, last version

**Comment by evilaliv3** [comment]
@alessandro-battezzati: This is an expected behaviour.

GlobaLeaks by default creates one administrator, enables the possibility to change user passwords and provides to this administrator the possibility to change user passwords.

This administrator only could:
- change user password
- assign other administrators the possibility to change user password

Only administrators with the possibility to change user passwords could eventually disable this feature.

The reason why you see this option grayed out is because probably you are currently accessing with an administrator that is not enable to change user passwords.

I hope this clarify your situation.

Current version of the software and upcoming version have an interface that would try to clearly make the feature understandable.

**Comment by alessandro-battezzati** [comment]
thx
