### ISSUE TITLE
Make it possible for recipients to exchange private messages, sub-statuses and attachments not visible to whistleblower.

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2931]
While whistleblowing is all about transparency, case management often needs to be conducted confidentially to avoid legal risks and disclosure of personal data.
Often recipients working remotely wish to comment on submissions between them without access from the whistleblower.
Could private messages be extended to include all recipients and exclude the WB?
Similarly while status is a great feature, recipients would like to classify submissions to substatus like "high risk" or "possibly malicious" without upsetting/discouraging the WB or creating any legal risks. While recipients could use the label, I believe a more structured approach like an option which substatuses will be not visible to the WB (like a checkbox) is more suitable.
If this kind of confidentiality can be extended to file attachments exchanged between recipients then globaleaks becomes much more powerful case management system that can also be used for investigations.

**Comment by evilaliv3** [comment]
Thank you @elbill for your valuable feedback.

Actually i would advise to try to brakedown your feature requests so that they could be more easily analyzed.

As for being able to generiucally mark a report as important i advise you to check the "mark as important" feature implemented in 4.1.0. You can see it automatically enabled on the report and reports' list page.

As for being able to make private annotations (via a sort of comments / notes), there is already this ticket: https://github.com/globaleaks/GlobaLeaks/issues/1957

As for the ranking of submissions i think we could instead use the tickets that deals with the automatic / manual score feature that already exist in automatic form.

**Comment by elbill** [comment]
You are right @evilaliv3 . Got a bit carried away! Thanks for your guidance regarding the implemented features. Just checking 4.1.1 before updating. I will close the issue and see if it make sense to open a new one.

**Comment by evilaliv3** [comment]
Thank you @elbill for your great suggestion and support!
