### ISSUE TITLE
Error when updating to version 4.1.11

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2964]
**Current behavior**
There is an error when updating from 4.0.58 to 4.1.11.
same error comes up when updating to 4.1.9 or 4.1.10
No error when updating to 4.1.1
I have tried to run the install script for updating globaleaks with the same result.

**GlobaLeaks version:**
4.0.58

**Server Operating System and Version (if applicable):**
Ubuntu 18.04LTS

![error](https://user-images.githubusercontent.com/23246886/104653699-ad3d0180-56c3-11eb-90e7-daaf207fceb1.png)

**Comment by evilaliv3** [comment]
Thank you for reporting this @elbill 

The error is due to the fact that your system do not appear to have python-cryptography at version > 2.6

Would you please try to do an update with ```apt-get update && apt-get upgrade``` to get sure all the required dependencies are updated and confirm me if this would fix your issue?

I will get sure to add this check in the package for other users so that the package will be upgraded automatically.

thank you!

**Comment by evilaliv3** [comment]
@elbill: If you would like to give it a try i've issued a package 4.1.12 that enforce the requirement for python3-cryptograhy > 2.6.

Please let me know if this will fix the issue.

**Comment by elbill** [comment]
Thanks @evilaliv3. Update worked as expected.
