### ISSUE TITLE
GPG error: https://deb.globaleaks.org focal/ Release: The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>

### ISSUE THREAD

**Issue by k-saari** [globaleaks/GlobaLeaks#2985]
The error we're getting now on Ubuntu 20.04, when installing globaleaks.

Is the gpg key got old?

**Comment by evilaliv3** [comment]
Thank you, Yes, its likely! 

Time passes! GlobaLeaks grows!

Let me check this right away!

**Comment by netra-news** [comment]
We are having the same issue:

> W: GPG error: https://deb.globaleaks.org focal/ Release: The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
> E: The repository 'http://deb.globaleaks.org focal/ Release' is not signed.
>

**Comment by evilaliv3** [comment]
The key has been update and as well the signatures on the repositories.

You can now proceed installing by downloading the up-to-date install script.

If you need the up to date key to load it on your server or verify the software you can find it here: https://deb.globaleaks.org/globaleaks.asc

**Comment by skaag** [comment]
This does not help if you're on Ubuntu Focal and already have Globaleaks installed. Downloading that key is not enough, as `apt update` will still complain about the previously bad key.

**Comment by evilaliv3** [comment]
@skaag : absolutely, the above command will add the file to apt by means of the apt-key part that follows the pipe

**Comment by coccolesto** [comment]
Having same error from a fresh ubuntu 20.04 install.

root@glk:~# apt-key list
/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-archive.gpg
------------------------------------------------------
pub   rsa4096 2012-05-11 [SC]
      790B C727 7767 219C 42C8  6F93 3B4F E6AC C0B2 1F32
uid           [ unknown] Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg
------------------------------------------------------
pub   rsa4096 2012-05-11 [SC]
      8439 38DF 228D 22F7 B374  2BC0 D94A A3F0 EFE2 1092
uid           [ unknown] Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

/etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg
------------------------------------------------------
pub   rsa4096 2018-09-17 [SC]
      F6EC B376 2474 EDA9 D21B  7022 8719 20D1 991B C93C
uid           [ unknown] Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>

root@glk:~# curl -L https://deb.globaleaks.org/globaleaks.asc | sudo apt-key add
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5519  100  5519    0     0  58094      0 --:--:-- --:--:-- --:--:-- 58094
OK
root@glk:~# apt-key list
/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2013-04-16 [SC] [expires: 2024-04-07]
      B353 922A E445 7748 559E  7778 32E6 7926 2404 5008
uid           [ unknown] GlobaLeaks software signing key <info@globaleaks.org>
sub   rsa4096 2013-04-16 [E] [expires: 2024-04-07]

/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-archive.gpg
------------------------------------------------------
pub   rsa4096 2012-05-11 [SC]
      790B C727 7767 219C 42C8  6F93 3B4F E6AC C0B2 1F32
uid           [ unknown] Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg
------------------------------------------------------
pub   rsa4096 2012-05-11 [SC]
      8439 38DF 228D 22F7 B374  2BC0 D94A A3F0 EFE2 1092
uid           [ unknown] Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

/etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg
------------------------------------------------------
pub   rsa4096 2018-09-17 [SC]
      F6EC B376 2474 EDA9 D21B  7022 8719 20D1 991B C93C
uid           [ unknown] Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>

root@glk:~# apt-get update 
Hit:1 http://it.archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://it.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://it.archive.ubuntu.com/ubuntu focal-backports InRelease
Ign:2 https://deb.globaleaks.org focal/ InRelease       
Hit:5 http://it.archive.ubuntu.com/ubuntu focal-security InRelease
Get:6 https://deb.globaleaks.org focal/ Release [741 B]
Get:7 https://deb.globaleaks.org focal/ Release.gpg [833 B]
Ign:7 https://deb.globaleaks.org focal/ Release.gpg
Reading package lists... Done
W: GPG error: https://deb.globaleaks.org focal/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
E: The repository 'http://deb.globaleaks.org focal/ Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by nsturtz** [comment]
For me it is still broken on Ubuntu 20.04 new install

**Comment by evilaliv3** [comment]
Thank you Nate, the repo is currently not signed for other reason as we are
issuing a new package and we have some delay. you will find out a release
4.2.9 that will work like a charm!

Thank you for your patience

**Comment by nsturtz** [comment]
Ok thank you

**Comment by skaag** [comment]
Still not fixed for me on Ubuntu Focal, I tried to update the key again, it's still giving me a BADSIG as if the repository is not signed.

I ran:
```
curl -L https://deb.globaleaks.org/globaleaks.asc | sudo apt-key adda
apt update
```

And I still get the BADSIG error
```
Err:8 https://deb.globaleaks.org focal/ Release.gpg
  The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
```

**Comment by evilaliv3** [comment]
thank you for reporting this @skaag.

 actually the repository of focal was probably not signed since last release. would you please retry now?

**Comment by jestboniface** [comment]
Still  getting BAGSIG on Ubuntu 20.04.2 LTS (GNU/Linux 5.8.0-1041-aws x86_64)

Additional Information: 


W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be upgraded:
  globaleaks
1 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
Need to get 2274 kB of archives.
After this operation, 138 kB of additional disk space will be used.
Err:1 https://deb.globaleaks.org focal/ globaleaks 4.2.12
  404  Not Found [IP: 51.15.240.96 443]
E: Failed to fetch https://deb.globaleaks.org/focal/globaleaks_4.2.12_all.deb  404  Not Found [IP: 51.15.240.96 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by evilaliv3** [comment]
@jestboniface would you please retry now?

**Comment by TjebbeVQ** [comment]
@evilaliv3 We are also experiencing this BADSIG issue for the ubuntu 20.04 LTS Focal.

**Comment by hackvokat** [comment]
I'm getting the same error today on a new Ubuntu 20.04.2 LTS

`W: http://deb.globaleaks.org/jammy/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: GPG error: https://deb.globaleaks.org jammy/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
E: The repository 'http://deb.globaleaks.org jammy/ Release' is not signed.`

**Comment by Kheru** [comment]
Time for the globalaks-archive-keyring package?!

**Comment by evilaliv3** [comment]
Thank you @Kheru 

Definitely we would need to do something like this at some stage. 
do you have experience with this? Are you able to support this effort?

**Comment by Kheru** [comment]
An approach like this should be profitable. https://stackoverflow.com/a/71384057

**Comment by iidmitaly** [comment]
Due to a certificate error I'm trying to update Today:


root@vmi1547294:~# globaleaks --version
GlobaLeaks version: 4.13.18
Database version: 66
root@vmi1547294:~# apt-get update && apt-get install globaleaks
Hit:1 http://asi-fs-n.contabo.net/debian bookworm InRelease
Hit:2 http://asi-fs-n.contabo.net/debian bookworm-updates InRelease
Hit:4 http://deb.debian.org/debian-security bookworm-security InRelease
Ign:3 https://deb.globaleaks.org bookworm/ InRelease
Get:5 https://deb.globaleaks.org bookworm/ Release [751 B]
Get:6 https://deb.globaleaks.org bookworm/ Release.gpg [833 B]
**Err:6 https://deb.globaleaks.org bookworm/ Release.gpg
  The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
Fetched 833 B in 1s (1,078 B/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.globaleaks.org bookworm/ Release: The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>**
W: Failed to fetch http://deb.globaleaks.org/bookworm/Release.gpg  The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be upgraded:
  globaleaks
1 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
Need to get 82.6 MB of archives.
After this operation, 6,144 B of additional disk space will be used.
Err:1 https://deb.globaleaks.org bookworm/ globaleaks 4.13.21
  404  Not Found [IP: 95.174.23.119 443]
E: Failed to fetch https://deb.globaleaks.org/bookworm/globaleaks_4.13.21_all.deb  404  Not Found [IP: 95.174.23.119 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
root@vmi1547294:~#

**Comment by iidmitaly** [comment]
it is Debian 12 (Bookworm).
