### ISSUE TITLE
mail notification not working

### ISSUE THREAD

**Issue by RangersMS** [globaleaks/GlobaLeaks#3005]
**Describe the bug**
I have installed GlobaLeaks in version 4.2.6 with the official [docker-scirpts](https://github.com/globaleaks/globaleaks-docker-scripts). Everything but email notification is working fine. GlobaLeaks is not able to send any mail no matter which settings are used. The web ui just shows the running circle forever and in a tcpdump I can see that GlobaLeaks even didn't tried to contact the mail server.

**To Reproduce**
1. Go to 'Notification settings'
2. Click on 'Test the configuration'
3. See error

**Expected behavior**
I was expecting that the ui would return that everything is good and I get an email with a test message or the ui says there was an error.

**Screenshots**
![Screenshot_2021-05-10_08-13-28_4679afb7-bada-4784-8462-b5d7744f1590](https://user-images.githubusercontent.com/48658285/117614740-0f38df80-b169-11eb-98b8-82eb44ae07f6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 88.0

**Additional context**
This issue is known in the [GlobaLeaks Forum](https://forum.globaleaks.org/t/help-needed-debugging-mail-configuration/597) and was discussed there before without any result yet.

**Comment by evilaliv3** [comment]
Thank you for reporting this.

Actually the Docker script is considered experimental and is provided just
for testing purposes.
I expect this could likely be one of the reason of the malfunctions.

Would you please attach the file /var/globaleaks/logs/globaleaks.log?

**Comment by evilaliv3** [comment]
From the log i see that the smtp connection is using a sock proxy to
connect via Tor.

This means that you have enabled the functionality to anonymous outgoing
submissions.

Please disable this functionality and restart the process.

Probably Tor connections are not working in your setup due to docker and
this is the reason of the failure.

Following my suggestion instead all the connections will be direct to the
smtp server and you should see them with TCP dump

**Comment by RangersMS** [comment]
Yes, disabling 'Anonymize outgoing connections' worked for me. Just tested it. Test mails and even some old test reports were delivered via email now. Thanks @evilaliv3 !

**Comment by k972** [comment]
what is Anonymize outgoing connections?

**Comment by RangersMS** [comment]
It's an option within the admin settings. Go to 'Network settings' and click on 'Tor'. There you'll have the option 'Anonymize outgoing connections'.

**Comment by k972** [comment]
i do not have this option

**Comment by k972** [comment]
i am facing the same problem

**Comment by k972** [comment]
Anonymize outgoing connections is not showing

**Comment by k972** [comment]
could you please help me to fix this issue

**Comment by evilaliv3** [comment]
Dear @k972, thank you for your questions.

Please consider that this ticketing system is a tool offered to the community in order to collect software issue and feature request. I would kindly ask you if you can to use for this reasons and to try to not use it as a chat system in order to solve your personal setup issues.

I invite you to eventually post questions like this on the forum or to join our community slack where maybe someone could support you or engage professionally.

Thank you for your understanding

**Comment by k972** [comment]
how to check the log file

**Comment by k972** [comment]
I am not a pro it

**Comment by k972** [comment]
please guide me

**Comment by k972** [comment]
please help me

**Comment by k972** [comment]
are you there?
