### ISSUE TITLE
Failed to import Questionnaire after new install

### ISSUE THREAD

**Issue by usama247** [globaleaks/GlobaLeaks#3034]
We had running docker based whistleblower application on our old server. Now we have migrated it to newer one. Our running versions are mentioned below:

Whistleblower
4.0.58 version

SW info:
Web server: Nginx.
Database: unknown.
Running OS: Ubuntu on AWS.

Problem : I wanted to export the Questionnaire from old server and import it into the new one, But when I import it to new one, I am facing the 500 internal server error.

I’ve seen and old thread on this same issue but the solution gave over there by some of your guy was to delete all default questionnaires and then import the one which I wanted to. That didn’t work either.

**Comment by evilaliv3** [comment]
@usama247: Thank you for reporting this.

Would it be possible for you to share the questionnaire so that we would look into it? This way i could look at it and try to figure out the exact reason of the failure. I suspect that you may composed your questionnaire using question templates that currently are not automatically exported / re-imported.

**Comment by usama247** [comment]
Thanx for responding back. I'm facing a problem regarding ulpload of .json(questionnaire which i've imported to share with you) file. The format is not supported by this chat box.

**Comment by usama247** [comment]
[Speak Up!(1).txt](https://github.com/globaleaks/GlobaLeaks/files/7038591/Speak.Up.1.txt)


I've changed it from .json to .txt file

**Comment by evilaliv3** [comment]
Thank you for providing this @usama247; I will try to test your questionnaire and provide you feedback.
