### ISSUE TITLE
Always encrypt downloads with PGP when the user key is available

### ISSUE THREAD

**Issue by brianwynne** [globaleaks/GlobaLeaks#3087]
Feature Request  -
When a Recipient provides a PGP key - Encrypt all downloads and report exports with this public key.

**Additional context**
Given that the functionality is already present to encrypt data on the fly using a supplied PGP key  this feature would ensure that the disclosure & documents etc. would be unreadable by anyone except the Journalist for whom they are intended. Allowing the data to be downloaded in the clear onto even corporate machines which are encrypted has the disadvantage of allowing a court order to be secured against the organization compelling the corporate encrypted machine keys to be provided to decrypt the files. If the reports & downloads were encrypted with the journalists individual PGP keys the organization cannot be compelled to provide the keys as it does not possess them thus protecting the data itself from being disclosed unwillingly to anyone.
It also would protect the data if it was inadvertently downloaded to a machine which was not protected.

**Comment by evilaliv3** [comment]
Thank you @brianwynne for such useful feedback.

In previous of GlobaLeaks we were using PGP to encrypt files at rest but this had the following countereffects that lead us to deprecate it:
- only files where encrypted with PGP so that the export of the report was anyhow in plaintex
- files where encrypted at rest per each recipient requiring significant space as the file was stored multiple time
- in case of PGP key loss the files were lost without possibility to recover them.

Encryption on the fly the download would offer the possibility to bypass this 3 limitations.

Are you a developers and would you like to give it a try developing this patch?

**Comment by evilaliv3** [comment]
Implemented! 

Now the PGP key, if available, will be always used for any recipient download included exports.

The feature will be released with package version 4.5.0

**Comment by brianwynne** [comment]
Wow fantastic, . I was still waiting for a reply from our dev team !!!!..

thank you,

**Comment by evilaliv3** [comment]
You are welcome, thank you for your suggestion @brianwynne !
