### ISSUE TITLE
Make it possible to manually configure the TOTP secret

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3088]
Hi!

This might be a stupid suggestion/request , but anyway I ask it anyway :-)

Would it be possible some how to "share" a MFA token generator for the same user across multiple sites? As an admin/recipient for a large number of sites, the number of individual sites in the Authenticator app is growing and will soon be hard to use.

My idea is, that when creating a user on a specific site, you should have the option to add the key from a previously known QR  code, and hereby add the user to the same token generator (does it make sense?)

I don't know if this is possible at all or it is too big a security issue.

If it isn't an option - is there any other ideas to deal with this challange? Maby adding the option to use SMS/email as MFA (in other applications, I've used a combination of email/sms. A token was generated by application and send to an external SMS provider that forwarded the token to the user phone)

**Comment by evilaliv3** [comment]
Thank you @schris-dk for this valuable suggestion.

I think i could issue a patch to make it possible to edit the code so that you could eventually load an existing two factor key.

The interface will be like this:
![Screenshot_2021-11-04 GLOBALEAKS - Preferences(2)](https://user-images.githubusercontent.com/217034/140307868-e797c1c6-62e1-4426-8f05-3b62089e04d9.png)

![Screenshot_2021-11-04 GLOBALEAKS - Preferences(3)](https://user-images.githubusercontent.com/217034/140307880-4e447802-16bb-4757-b117-f9ed8e9e9a79.png)

In relation to the second suggestion we would not prefer to integrate third party services within the system.

For the future we may evaluate to offer the possibility to enable two factor authenticatios by means of U2F for who prefers to have a phisical key in place of an app based token (https://github.com/globaleaks/GlobaLeaks/issues/1352)

\cc @elbill @maxmois

**Comment by evilaliv3** [comment]
This feature will be added starting from release 4.4.6

**Comment by schris-dk** [comment]
Absolutely perfect :-)
