### ISSUE TITLE
Editable page title and description in html source

### ISSUE THREAD

**Issue by JackBRN** [globaleaks/GlobaLeaks#3115]
Description in "Site settings/Main configuration" is editable, but it is not visible anywhere. Problem probably connected to issue #3113.

In html source code visible is default description, even language is set to other than English. The same situation with title tag:

```
<title>GlobaLeaks</title>
<meta name="description" content="Secure whistleblowing platform based on GlobaLeaks free and open-source software.">

```
**Expected behavior**

- Page Description in html source should be connected to value set in "Site settings/Main configuration/Description".
- Page Title in html source should be the same as value of #TitleBox section.

GlobaLeaks 4.5.6

**Comment by evilaliv3** [comment]
Dear @JackBRN, thank you for your ticket.

I just verified and actually in current version 4.5.6 both the Title and the Description settings are correctly working.
The application does change them at runtime after successful startup. To see it you could for example inspect the application with the JavaScript inspector of your browser.

Please let me know if it works for you or eventually please provide the name and the version of your browser so that i will proceed testing the application with your exact configuration.

**Comment by evilaliv3** [comment]
@JackBRN ?

**Comment by JackBRN** [comment]
It works fine - I didn't notice that value is not in the html, but it's provided by the script.

Thank you @evilaliv3. Closed.
