### ISSUE TITLE
Multiple report export not working

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3144]
**Describe the bug**
When selecting more than one report or all reports to export, only one (random) report is exported.

**Comment by evilaliv3** [comment]
Dear @elbill, thank you for your reporting.

I just tried to reproduce this issue by creating a setup, performing 2 submissions and trying to export them and it actually has worked for me.

When multiple exports are requested the system should offer multiple file download one after the other asking you the authorization to download the content.

Is it possible that when you tried you just stopped in front of the first download message and that due to this reason you did not notice that multiple file downloads where offered?

Would you please retry and eventually let me know which browser version/os are you using? this way i will try to reproduce this issue in your same scenario.

Thank you!

Giovanni Pellerano

**Comment by elbill** [comment]
Indeed my browser was blocking the multiple downloads. 
I remember that you changed the dowload mode from single file to multiple files (cant remember the reason).
The way it works now is not practical for high numbers of downloads (lets say you want to have the downloads of the whole month and they are 50). Is it impossible to get them all at once in one file or some other way?

**Comment by evilaliv3** [comment]
Thank you @elbill for your feedback. This implementation is made for simplicity reason in order to at least offer the feature of multiple export in the short term, but i do not exclude we could rework it to be based on a single file download but this will require some more important development that will come next.

**Comment by elbill** [comment]
Thanks. It used to download everything in one file. It is useful as it is anyway. It would be great to implement again something more convenient in terms of a large number of downloads like auto downloading the multiple files without user confirmation for each one! Some kind of optional zip encryption would be also useful (as discussed in #1581).

**Comment by evilaliv3** [comment]
@elbill: The main reason while currently the files are now downloaded separately is to implemen encryptiion by means of PGP.

If you already load a PGP key for your account the files will be now downloaded with PGP.

We may evaluate as well for the future to offer the possibility to provide a password to encrypt the downloaded file with 7zip when serving it as for the ticket that you refer.
