### ISSUE TITLE
Prevent reuse of tenant IDs upon tenant deletion

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3197]
From our experience, tenant IDs are reused. 
For example, if I delete a tenant with TID=10, next time a tenant is created it can get the same TID=10.

When it happens, it is possible to see audit logs from the previously deleted tenant.

**Comment by evilaliv3** [comment]
Thank you for reporting this @aetdr

Let me check on this issue and be back.

I expect that this could be due to how sqlite work.

The main issue that i see is that currently audit logs are not deleted when a tenant is deleted that is desirable; This is probably due to the fact that the system does not implement a foreign key on the AuditLog tid attribute.

I'm going to improve this aspect and include this patch in the next release.

**Comment by aetdr** [comment]
Hi @evilaliv3 

We would like to keep the auditlog entries after a tenant is deleted. For a while at least.
Otherwise, all the traces of the tenants existence are wiped out.

It should be possible it the TID is marked as autoincremented (two identical entries should not be possible with autoincremented columns)

**Comment by evilaliv3** [comment]
Nevermind my previous question @aetdr, i've just found the solution to implement it. Thank you.

**Comment by evilaliv3** [comment]
Implemented; the improvement will be included starting from release 4.9.0

Thank you @aetdr for your suggestion.
