### ISSUE TITLE
Possibility to restore "Allow recipients to change whistleblower privileges on specific reports" feature

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3213]
**Is your feature request related to a problem? Please describe.**

ON GL 4.8.0 the possibility to block/unblock the insertion of new comments and files by the whistleblower is no longer available to the recipients. I personally found this to be a pretty useful feature, to avoid the receivers to be spammed, also because right now is no longer possible to temporally limit the whistleblower's access to the report.

**Describe the solution you'd like**
Ask for restore the feature either in advanced settings (for all receivers) than with a per receiver fashion, with the aim that this possibility is for specific recipients only. Obviously when report is in closed state  everything will be disabled.

**Comment by evilaliv3** [comment]
Thank you for your question @larrykind.

In the recent version to enable this feature automatically when comments, messages or files are not enabled for the whistleblower.

In 4.9.0 we will be furtherly enabling the feature by automatically and with no configuration letting recipient to alway be able to disable this options to whistleblower and tracking recipient actions in the audit log to prevent abuses.

**Comment by evilaliv3** [comment]
@larrykind: Here is a preview of the interface that will be probably simplified in the future moving all the enablers in a dedicated section.

Every recipient will have always this interface and they may change the responsibly enable or disable permissions to whistleblowers and their operativity will be tracked.

![Screenshot 2022-03-24 at 19-11-37 GLOBALEAKS - Report](https://user-images.githubusercontent.com/217034/159982991-3c87d73f-abab-40c5-a8ff-d85723cf0091.png)

**Comment by larrykind** [comment]
@evilaliv3 thanks, just tested it. 
It works as you said, so funtionality is always there.
Anyway I just would to put in evidence that since the important "report sharing" functionality, It was introduced the possibility to create a de-facto receivers hierarchy. So in my opinion It should be given the possibility to follow this hierarchy by giving to  recivers the possibility to allow/deny whistleblowers to comment or attach files, in a per receiver way.

I come from a case in which whistleblowers spam specific receivers because of personal reasons or simply because they are scared of retailiations. In my experience identity leak is not a case for which to block attachments or comments.

Finally, the feature could be clearly used in the actual mode, but the old one seems to me to give a more specific receivers configuration: actual behaviour could be the default mode for the restored feature

**Comment by evilaliv3** [comment]
Thank you @larrykind, i really appreciate your feedback and we will surely consider this as we will move forward our research and development.

Our concern is that this feature that was designed for very advanced project where the recipient is an human rights activists trying to limit collection of information of sensible information, could be abused in the anticorruption context where the recipients could disable submissions because they do not want a specific whistleblower to talk.

This is a very risky condition in which the recipient could say: "i was receiving spam information, i closed the conversation". We prefer instead that to offer only the possibility to close the report up to the evaluation and responsibility to the recipient.
