### ISSUE TITLE
Send e-mail without server

### ISSUE THREAD

**Issue by serberci** [globaleaks/GlobaLeaks#3243]
Is there anyway to send notification e-mails without a SMTP server behind? I did not see any configuration to do it.

How can i edit the sender from e-mails? To use a noreply@company.com, for example.

Thanks!

**Comment by evilaliv3** [comment]
Dear @serberci ,

The current implementation requires a properly configured SMTP server to implement a reliable notification and avoid spam.

While technically possible, we have not considered sending email directly from the application because this would require end-users advanced knowledge to setup DNS records in relation to DKIM and SPF. Did you consider this for example while proposing this feature ?

**Comment by evilaliv3** [comment]
Using our default credentials you could only send email as notifications@globaleaks.org

This is due to the fact that our mail server is optimized for anti-spam, apply DKIM signatures and is rigorously hardened.
