### ISSUE TITLE
Permission denied on '/dev/shm/globaleaks'

### ISSUE THREAD

**Issue by agrr** [globaleaks/GlobaLeaks#3257]
On a Globaleaks installation performed 2 days ago from git master I've been getting this errors on the function `perform_secure_deletion_of-temporary_files`: 
`PermissionError: [Errno 13] Permission denied: '/dev/shm/globaleaks'`

Actually I verified that `/dev/shm/globaleaks` is a directory owned by root with 0700 permissions, when it should be owned by `globaleaks` user.

Digging deeper I found that the chown command introduced in the following commit is to blame for the error, I guess it should use the `$USERNAME` variable instead of `$user` ?: https://github.com/globaleaks/GlobaLeaks/commit/7d998141dde93976752c78794b536fb7cdeb2d1b

**Comment by evilaliv3** [comment]
Thank you @agrr for noticing and reporting this.

I'm proceeding applying this fix right away and release officially the 4.10.0.

The fix is in commit https://github.com/globaleaks/GlobaLeaks/commit/8a301b3e7672420fbbc43faa6db753fdf8dae84a

For a matter of curiosity may i ask you why you are running globaleaks directly from it's sources? are you developing a new feature? in this case please feel free to open a ticket to discuss it and propose it for integration.

**Comment by agrr** [comment]
Hello @evilaliv3 thank you for the quick response.
 
I already tested the 4.9.0 release, with the goal of eventually deploying it for my company. My general opinion on the platform is very good and it seems to be a good fit for us.

However I found some missing Portuguese translations which are possibly already fixed in recent commits so that's why I decided to try to build a new package from source. 
We may have some suggestions for improvement or new features but expect to hear from us next month as we'll all be back from holidays then.

Thank you again for this great project.
