### ISSUE TITLE
Increase password minimum length from 10  to 12 chars

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3311]
Hi @evilaliv3 

Curently, Globaleaks enforces password minimal length of 10 characters.
It is hardcoded and can not be controlled by admins.

We would like to increase this requirement to minimum 12 chars. Can it be done in a future version?

**Comment by evilaliv3** [comment]
Thank you for your question @aetdr 

Actually this could not be changed easily because the current users instructions refer to 10 characters.
What we could do it to change the password slightly to achieve the same result:

Let me explain:

The current instructions and their translation say: ```The chosen password is too weak. A valid password should be at least 10 characters long and contain a variety of characters including at least a lowercase character, a capital character, a number and a special character.```

The current implementation requires the user to:
- type at least 10 characters
- type at least a chartacter (UPPERCASE)
- type at least a character (lowercase)
- type at least a symbol

If the user follows these policy they get medium score if they typed at least 8 different characters and an high score if they typed at least 10 different characters.

I suggest we could tweak this implementation to assign a medium score only if users typed at least 10 different characters and high score if users typed at least 12 different characters.

What do you think?

**Comment by evilaliv3** [comment]
Closing this as implemented in current release 4.10.16
