### ISSUE TITLE
CSS not working on subsite

### ISSUE THREAD

**Issue by cdlh** [globaleaks/GlobaLeaks#3313]
**Describe the bug**
I try to design one subsite exactly as my main-site. But it seems that the uploaded .css-file is not working (same file as on the main-site)

**To Reproduce**
1. Design CSS-file for your mainsite and export it
2. Import that CSS-file to one of your subsites

**Expected behavior**
With the same CSS-files both sites should look identically?

**Desktop (please complete the following information):**
 - OS: Ubuntu
 -  Edge, Firefox

**Comment by evilaliv3** [comment]
Thank you @cdlh  for reporting this.

Actually we are not aware of issues of this kind and all works on the systems that we manage.

Which version of the software are you running?

There is only one condition in which the CSS is not loaded, that is when you access a tenant as super administrator by using the "Configure" link on the primary site. Maybe this is your situation?

**Comment by cdlh** [comment]
To be honest, i don't know what i've done wrong - now it works. 
Thank's for your - again - quick support!

**Comment by evilaliv3** [comment]
You are welcome, thank you for your feedback @cdlh

**Comment by cdlh** [comment]
So, just another question. I’ve got a javascript file which i try to upload (via files). The file itself seems not to be uploades, because it won’t show between the other files (like i. e. fonts). Any idea for that problem?
Am 19. Nov. 2022, 12:16 +0100 schrieb Giovanni Pellerano ***@***.***>:

**Comment by evilaliv3** [comment]
Hello @cdlh,

Thank you for the question, if you could please always use separated tickets by topic.

Actually we do not enable loading Javascript files via the web interface because of some security constraints.

If you want to load a javacript file for a tenant you should put it in the following path /var/globaleaks/scripts/$number
For example if you want to load a javascript customization for thr tenant 2, the file will need to be called simply "2"
