### ISSUE TITLE
DB insert fail in table "internaltip" caused by unique constraint

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3325]
Hi,
I noticed in my GL logs the following error, it looks like **internaltip** INSERT query was not successful, but I couldn't find the reason. Could you give an help please? No more cases like this anyway. I attach the log.
Thanks for the support
[db_insert_fail.txt](https://github.com/globaleaks/GlobaLeaks/files/10372859/db_insert_fail.txt)

**Comment by evilaliv3** [comment]
Thank you for your question.

This exception is probably related to a duplicated client request from of
completion of a submission probably scattered due to a button pressed twice
or two submissions happening on the very same time.
You could probably understand more if you combine the log with the access
log.

In both the two cases I would simply ignore the issue as long that it is
not repeating.

**Comment by larrykind** [comment]
Thank you for clarifying @evilaliv3, 
anyway I feel to suggest that buttons related to an insert query should not be pressed twice, to avoid future db errors on unique constraints on the same tenant
I was not able to replicate the issue, anyway I hope that a gui error will be shown when an exception like this is thrown, for example inviting the whistleblower to file the report again.
Thanks for the support. Ticket closed.
