### ISSUE TITLE
Make it possible to customize the "Request Support" feature.

### ISSUE THREAD

**Issue by pvigoseidor** [globaleaks/GlobaLeaks#3335]
Hello!

As a multitenant admin, I want to customize the Request Support Icon, actually it only allow to open a form to send an email to the admin.

It will be great if we have the possibility to customize:
- Set the email address, not only the admin email.
- Redirect to an external form (link).

Thank you.

**Comment by evilaliv3** [comment]
Thank you @pvigoseidor for your feedback.

As shared with you already offline we have already some ideas to edit this feature to prevent sending emails to the users but just send them a notification inviting them to check the support request on the platform.
We consider this would be optimal to reduce risks that sensitive information is shared via the support request and getting sure all is handled with the same security that the platform offers.
When this will be applied probably we will never share the content of the request to external users but only to admin users configured on the system; this putsome limits on your first suggestion "Set the email address, not only the admin email." but lets see .

For the second idea instead , i find vary valuable to offer a possibility to customize the feature to make it possible to configure an external form link and open a new tab redirecting the user to this page when the button Request Support is clicked. This would be very valuable when the administrators have already a professional support helpdesk system in place.

This said i find very helpful the

**Comment by pvigoseidor** [comment]
Thank Giovanni, 

In our case, we have already a professional support helpdesk system for admins, so redirect to our form will be perfect for us because we can manage better the support tickets.

Thank you.

**Comment by evilaliv3** [comment]
@pnellikkaparambil  I've merged this feature in the branch https://github.com/globaleaks/GlobaLeaks/tree/feature/custom_support_url

I will proceed finalizing the review by checking the browser tests that works but seems to cause failures to the other existing tests

After that i think we could proceed integrating it in the devel branch.

I'm still in doubt about the additional text "Custom Support URL that i proposed because is a very specific text that require a very specific translation. Maybe we would benefit of splitting it in "Custom URLS" + "Support" so that in the future we may eventually add "Forum" and "Chat" to let people personalize links to forum and chat.
This is part of the complexity of trying to understand the proper text to minimize the translation effort.

**Comment by evilaliv3** [comment]
Review completed, and code merged in the main branch already to celebrate your first contribution @pnellikkaparambil 

The patch will be included in our next minor release 4.10.19

Thank you!
