### ISSUE TITLE
Make it possible to visualize PDF files on the platform

### ISSUE THREAD

**Issue by pvigoseidor** [globaleaks/GlobaLeaks#3337]
As a recipient user it would be great to view the attachment text and PDF files without the necessity to download in a local device. 

Some organizations do not have an offline PC to view the attachment files and they are using the same PC connected to the Internet to save the attachment files, with the security problem that causes.

Globaleaks can embed a text/PDF viewer for view the attachment text files in the platform.

**Comment by evilaliv3** [comment]
Thank you @pvigoseidor 

This is an interesting proposal, partially discussed on ticket https://github.com/globaleaks/GlobaLeaks/issues/891 in relation to a more generic possibility to see files on the browser.

We always postponed the implementation because there are many open questions; the most important topic to be evaluated is which browser implement secure temporary files or even better avoid to store temporary file on the disk.
We expect that - most of the browsers implementations would probably store temporary files on the disk so vanishing the intent of not storing the file on the disk and offering a false sense of security.

With this regard it is interesting to explore what https://github.com/mozilla/pdf.js does and ask their team what they know about the behaviour of their libraries on Chrome, Safari and Firefox. Maybe we could identify that at least on some of these browsers we could implement this feature with reasonable security, and at least for small PDFs.

**Comment by evilaliv3** [comment]
@Snuffleupagus @timvandermeij do you have by any chance some suggestion in relation to comment https://github.com/globaleaks/GlobaLeaks/issues/3337#issuecomment-1408498373? 

@hackademix: have you ever evaluated these aspects on the different browsers implementations? is there any browser implementation that is vary tailored for security appliation and guarantee to never use file caching on Ajax requests and Blob objects?

Thank you so much if you could support us with your feedback.

**Comment by hackademix** [comment]
> @hackademix: have you ever evaluated these aspects on the different browsers implementations? is there any browser implementation that is vary tailored for security appliation and guarantee to never use file caching on Ajax requests and Blob objects?

Any "modern" web browser must honor the ["no-store" Cache-Control header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#no-store), which can be sent through a [handy shortcut in the Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache ), like:
```
await fetch("some.pdf", {cache: "no-store"})
```
As for blobs, they should be implemented as a RAM-only thing (of course some swapping can happen) and released either manually or automatically when the global (window|worker) creating it dies (hence the concerns about memory leak which make them unavailable in Service Workers).

At least in Firefox / Tor Browser this is [implemented as a hash table](https://searchfox.org/mozilla-central/source/dom/file/uri/BlobURLProtocolHandler.cpp#530). I guess something similar happens in Chromium-based browsers, but I'll leave that to you ;)

**Comment by evilaliv3** [comment]
Thank you for @hackademix for the great detail.

I wonder what they do when the blob / ajax response exceed the available RAM; i guess unfortunately they would  probably incurr in the operating system swapping on disk, and they would probably just delegate the problem to the operating system designers ....

I'm curios to check if any of the browser implementation has considered implementing a virtual encrypted layer to ensure this do not happen but i suspect not.

**Comment by evilaliv3** [comment]
@pvigoseidor @pnellikkaparambil: i was trying to see the libraries that we could integrate for this feature but i've still not a clear idea.

For sure in order to manage PDF files the proper and maintained library is https://github.com/mozilla/pdf.js 
To use it we could use it directly, or use an angularJS directive but as angularJS is now becoming outdated also the libraries built for it are (https://github.com/sayanee/angularjs-pdf, https://github.com/ekiziltas/angularjs-pdf-viewer, others)
For this reasons we have many alternatives and we should identify:
- Which was more maintained, developed and possibly optimized
- Which offer the capability that we need; to answer this question we need to understand well what we want  (do we want to be able to render txt files? do we want to play videos?)

I suggest we could start thinking to this, drafting some mockups and then selecting the components we need.

**Comment by evilaliv3** [comment]
I read a little bit more and checked the status of the main libraries (pdf.js and visualize.js) to see what the offer and their status of update. While pdf.js is well maintained by mozilla, other libraries like visualize.js are not so mainatined.

I think that for the moment, we could probably try to skip them both and just check what we could do by using simply the html5.

For example the following type of files can be rendered almost natively in all our supported browsers.

- pdf files can be embedded with:
```<embed src="file.pdf" type="application/pdf">```

- mp4 video files can be embedded with:
```<video controls><source src="file.pdf" type="video/mp4"></video>```

- mpeg audio files can be embedded with:
```<audio controls><source src="file.mpeg" type="audio/mpeg" /></audio>```

**Comment by evilaliv3** [comment]
Hello @pnellikkaparambil and @pvigoseidor

I just wanted to update you that i'm moving forward the analysis of the current state of the security of browsers on the matter of opening files and for the moment i concentrated my focus on PDF files

The browser that seems to implement the safest approach in handling PDF is Firefox, that has implemented pdf.js to handle visualization of PDF in javascript.

All the rest of the browsers seems to rely on other binary implementations, some embedded (Chrome and Edge and Safari) and some instead rely on the other possible applications installed on operating system.

Acrobat Reader that is the most widely used PDF lists a large set of vulnerabilities also in recent times: https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=adobe+reader

Based on just this brief evaluation i consider that the only safe way of implementing PDF file visualization would be to implement a visualizer of pdf based on PDF.js including this library and using it in all the circumstances.

I suggest that in our next development we could possibly try the library PDF.js and specifically just use their official viewer package

@pnellikkaparambil: Would you please give it a try?

The main reference is this: https://mozilla.github.io/pdf.js/
They develop a library able to implement custom viewers but they also develop a complete viewer. I suggest that it is very interesting to use the official complete viewer that is a safe option

Here is also their demo of their viewer: https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Priestch** [comment]
@evilaliv3 If you just want to use the default pdf.js features, give [document-viewer](https://github.com/Priestch/document-viewer) a try, it's easy to integrate into a project.

**Comment by evilaliv3** [comment]
Thank you @Priestch actually in the end at the moment we considered to implement a very minimal viewer using pdf.js and opening PDF files in a sandbox as canvas. Thank you anyway for the suggestion.

The conde is here: https://github.com/globaleaks/GlobaLeaks/tree/devel/client/app/viewer

I'm closing the ticket since the feature has been implemented and will be merged in release 4.11.0
