### ISSUE TITLE
Send an email acknowledgent to the whistleblower

### ISSUE THREAD

**Issue by zazzati** [globaleaks/GlobaLeaks#3414]
### Proposal

In this document

[https://www.forumpa.it/riforma-pa/whistleblowing-cosa-prevede-la-nuova-normativa-obblighi-adempimenti-e-sanzioni/](https://www.forumpa.it/riforma-pa/whistleblowing-cosa-prevede-la-nuova-normativa-obblighi-adempimenti-e-sanzioni/)

 is written:

" _**The procedural process following the report is defined:
within 7 days of submission, the person in charge must issue an acknowledgment of receipt to the reporting party and, where necessary, request additions; maintain interlocutions and diligently follow up**_ ";

It is possible to activate a feature that notifies to the whistleblower by email (if the whistleblower has entered a valid email)  changes in the status of the submitted questionnaire?

It doesn't seem possible to do that.

Actually we are working with GL 4.11.1.

thanks

### Motivation and context

Comply with the requests of the EU legislator

**Comment by evilaliv3** [comment]
Thank you @zazzati 

This topic is under analysis and two are  the aspects to consider that still miss any advice by the authorities.

1. would a receipt sent by email be compatible with the confidentiality principles of the directive?
2. in which whistleblowing systems is this receipt needed (post mail vs IT systems)

Let me examinate the two:

1.
When an email is sent, the email could be read by any e-mail relay server and by the destination e-mail server administrators. For this reason we consider inadequate to send the receipt via email because it would represent an evidence that the whistleblower identified by that email address has sent a report on a defined whistleblowing platform on a known date.

2.

Within our interpretation the directive, that is generically referring to every kind of media, is requesting this aspect for the medias that do not offer automatic receipts like for example IT systems do.

Because the directive for example enable to implement whistleblowing via email, the directive requires an acknoledgment by these kind of system and this acknowledgment that should happen within 7 days means that in 7 days since the reception the organization should reply "i've received it, we will process it from now on".

With this understanding, the current receipt implemented by the system is already fully compliant because it immediately confirm the user the reception of the report if the submission was successfully and the data has been stored.

**Comment by zazzati** [comment]
Dear [evilaliv3](https://github.com/evilaliv3)

We have a customer who made us this feature request.
The request also seemed to us to create problems for the anonymity of the whisthleblowers.
We agree with your answer and I'd say it's flawless

As usual, thank you for your precious time

**Comment by evilaliv3** [comment]
You are welcome @zazzati, thank you.

We will update you on the evaluations made about this ticket. I consider many may be questioning about this topic.

**Comment by evilaliv3** [comment]
Related to https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/898
