### ISSUE TITLE
Unable to visualize or download the case receipt

### ISSUE THREAD

**Issue by http-alba** [globaleaks/GlobaLeaks#3611]
### What version of GlobaLeaks are you using?

4.12.8

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

When a recipient tries to download the document attached to the case, gets this error:

![image](https://github.com/globaleaks/GlobaLeaks/assets/137271525/23a3e9d3-788a-467b-8479-8af743a171bd)

The visualizing option is not working either:

![Uploading image.png…]()

This only happens in a specific report, the rest are working just fine.

**Comment by evilaliv3** [comment]
Thank you @http-alba 

This is a bug affecting system started with a version <= 4.11 and upgraded to version < 4.13.3

The reason of the failure is described on https://github.com/globaleaks/GlobaLeaks/issues/3606

To resolve one would need a backup of the database before of the update. If the system where you are encountering the issue is a production just ensure to keep a backup and reach out to me for assistance
