### ISSUE TITLE
GlobaLeaks Client does not load over bad network conditions

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#363]
Improve loader of GlobaLeaks Client to work over bad network conditions

This ticket is to handle a retry of download of the elements required to have GLClient up and running.

The status of retry should be signed to the Comfort Loader.

/cc @hellais 
##

**Comment by evilaliv3** [comment]
Important optimizations have been impolemented since the ticket has been opened.

1) the application is minified to be served in few files.
2) quite all API resources are served in a single /public API including all images as base64 payloads

retry mechanism is already tracked by other tickets.

this ticket can be now closed and specific tickets could be eventually reopened.

**Comment by fpietrosanti** [comment]
@evilaliv3 which ticket track retries?
