### ISSUE TITLE
Tip closure motivation message is not shown - v4.15.4

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#4083]
### What version of GlobaLeaks are you using?

v4.15.4

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Hi @evilaliv3 

When closing a tip, it is possible to enter a closure motivation message.
Later on, this message is nowhere to be found. It is not in the WebUI nor in exported tip content.

**Comment by evilaliv3** [comment]
Thank you @aetdr 

This is the current situation since the feature has been implemented by the italian national authority for anticorruption but left incomplete.

We will evaluate if to remove it for the moment or to complete it trying collecting budget for it along with funding to support development of https://github.com/globaleaks/GlobaLeaks/issues/4085

Are you interested to contributing implementing these features?

**Comment by aetdr** [comment]
Hi @evilaliv3 

This is basen on feedback from users. 
The presence of this dialog creates the expectation that it can be used. And then they complain :)

**Comment by evilaliv3** [comment]
The feature will be removed in 4.15.6
