### ISSUE TITLE
Refactor the logging related code

### ISSUE THREAD

**Issue by hellais** [globaleaks/GlobaLeaks#622]
Currently the logging code is a bit sketchy and it could do with some love.

In particular calling flush every time could create some issues and it's also somewhat scary to have some cases where you do not write to the log.

The goal of this is to refactor the code inside the observer in globaleaks/utils.py.
##

**Comment by vecna** [comment]
To be addressed in this refactor: #782, #734

**Comment by vecna** [comment]
@evilaliv3 I'll switch here the conversation started in https://github.com/globaleaks/GlobaLeaks/commit/11b1bf7d219c1e1211d2b2f75d604b0bff039c3a#commitcomment-13338747

## New table proposed

  * id INT NOT NULL: Note, will be the first Incremental Numeric-only ID we put in the system. In addition, there are not reference. Looking inside, hopefully, will be a little faster.
  * code TEXT NOT NULL: This is the Log code, usable to associate a text (translated, too) to the log
  * args VARCHAR: optional args, is a JSON, the number of args are forced. so can be 0, 1, 2, ... 
  * log_date TEXT NOT NUL: This is the time when the event is happen (for example: "a new tip generated" or "a mail has not been delivered for a mailserver error" )
  * subject TEXT NOT NULL CHECK(type IN ('admin', 'receiver', 'itip')): Based on the kind of subject, we know who is going to see this log. Only three interface will be influenced by this log system:
      * The admin (that probably will have a dedicated page, plus, red balloon for warning, in the landing page)
      * The receiver, that will see in a dedicated page the last events associated, and red balloon for warning, in the landing page.
      * The internaltip, so, receiver(s) and WB, this will be display in a dedicated section of the tip page.
  * subject_id TEXT: the "_id" is not a reference because can contain different data, dependently from the **subject** above. so, if is a 'itip' subject, this will be an InternalTip.id, if is a 'receiver', is a Receiver.id, if is an Admin, at the moment is None, when multiple Admin shall be supported, an Admin.id (or User.id, we'll see) 
  * repeated INT: if a log get repeated, like, an email is gone badly delivered, and this happen for all the emails, then is pointless report 4 or 20 same event. this counter get incremented **every time the last event get repeated - only if the args are the same**, if the args differ, is reported a new entry. is like the syslogd optimization,
  * last_repetition_date TEXT: this is the date of the last repetition, if a log keep going repeated, you'll see "Xth of event" and the last at last_repetition_date (the first, as log_date)

**Comment by fpietrosanti** [comment]
Some comment:
A) i think we need integer to represent the category of log and another integer to represent the priority
B) i suggest to avoid the repeating-specific data structure at all, doing that specific improvement with log postprocessing (if needed)
C) Analyze The Windows EventLog data structure and get inspiration from here

Sent from mobile

>

**Comment by vecna** [comment]
Note: *repeated* related fields has been removed for KISS principle.

**Comment by vecna** [comment]
Last design tuning and pattern tuning are done.Tthe branch is https://github.com/globaleaks/GlobaLeaks/tree/log-refactor I need to know:

  * is available right now an angular-something that give us the time in relative way ? like "1 day ago" 
  * what I've to keep in mind before merge devel into ? (is still .108 version)
  * paging of logs still to be implemented

**Comment by evilaliv3** [comment]
@vecna can you document what done so far?
this would help in keeping documentation of it since the start and also for reporting (i'm preparing the OTF report and we could add details on the current status)

for your questions i would suggest first to end a full prototype in that branch withot not caring of refinements with the angular-relative library that is still to be evaluated/integrated.

and i would definitely not  integrate devel inside that branch (you can verify it but devel is really changed as a lot of code as been simplified/moved here and there, so that it is better if i will simply do it when reviewing your branch)

**Comment by vecna** [comment]
### Documentation

**what is this about**: logging of the event is happening in the software, and many different kind of event are reported. For example, a mail that is unable to be delivered, or the introduction of 20 wrong password  in the administrative login, are logged in the same way. was logged in the same way, before the changes documented below.

**how does it work**: instead of reporting the info written in text, every meaningful event in the system has a code associated, a text, and a certain number of argument(s). This can permit to associate to TIP_MESSAGE_1 something like "The receivers %s has postponed the expiration id of the Tip %s", and this can appears translated in the Tip history.

In order to do not overload DB activity, the new logs are flushed on the DB every 10 seconds, and in memory are kept the last 50 (but can grow at the moment) logs entry per user, in order to provide a fast answer.

The logs can have three kind of subject: admin, receiver and tip. the subject is also the only one seeing the message.

**Comment by evilaliv3** [comment]
Closing in favour of https://github.com/globaleaks/GlobaLeaks/issues/2579
