### ISSUE TITLE
Show limit upload

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#653]
Hi guys,
it would be greate to have, in the client side, close to the "add file" button the maximum limit in MB.
Clients don't know the limit (that is 30MB by default) and they may stock there waithing in vain.
Whit the phrase "30 MB max", that could help them organize the files they want to upload.

Anyway: you rock guys!

Opened originally on https://github.com/globaleaks/GLClient/issues/104
##

**Comment by evilaliv3** [comment]
The current interface does not show the limt to the user but simply give an error to the user as the user upload the file so that in the real the user does not have to wait the complete file upload but is simply alerted as the file is dropped in.

By design GlobaLeaks currently does not allow the configuration of a maximum size for each specific field of type file upload but has currently just a general setting.
Following the current design i suggest to not write the limit in the interface before the user try to load the file that is to say that i'm suggesting to keep the current interface.
in fact it will be simply annoying to see for each file upload this message; particularly when the limt is set high (1GB).


In the future could be valuable to move the file upload limit inside the fields configuration making it specific per field these way at upload time we could accept a file upload only if it declares to be attached to a file that accept that size.

on the same topic of validation right now the limit on the number of uploaded file (1, more than one) is currently only a fake feature implemeneted clientside, but a malicious user could upload how many files desires.

**Comment by evilaliv3** [comment]
The limit is currently shown only when triggered.

We should probably find ways to make users of what they could upload and what is limited.
