### ISSUE TITLE
If authenticated admin user goes on the login page he is asked for login/password

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#678]
If authenticated admin user goes on the login page (es: http://demo.globaleaks.org/#/login) he is asked for login/password.

This ticket is about fixing this behavior, so that the admin will be redirected to the main admin page if it's already authenticated.

Example screenshot below: 

![screen shot 2013-10-22 at 11 21 22 pm](https://f.cloud.github.com/assets/770363/1385537/2f08d8b0-3b60-11e3-8502-ed001833c1d5.png)

**Comment by vodkina** [comment]
It seems that the contribution from @ianribas it is of good quality. Do we have an estimate of its integration?

**Comment by evilaliv3** [comment]
Here we go @yvette!

@ianribas: I've integrated the patch.
thank you so much for your contribution!

I've decided to not integrate the tests; the reason is that it uses an addition framework (karma) that would require eventually to be properly evaluated among the most interesting in relation to angular-js compatibility and eventually be integrated first as a specific topic of javascript library retesting.

**Comment by ianribas** [comment]
I'll just note this here, until there is a specific topic for javascript client side unit testing (that I agree seems right).

I used karma for the tests just because I'm already used to it and it was simple. But I think it's such a pity to loose the tests that I made a new attempt at integrating them, now without karma, using directly the setup that was already in place for the "browserchecks":

https://github.com/globaleaks/GlobaLeaks/commit/e1180997f42daa8e7ea8c59cd45c78c0a3ce1f94

The test results can be seen on a browser opening `GlobaLeaks/client/tests/browserchecks/unittests.html` and on the command line using `grunt test-browserchecks`.

**Comment by evilaliv3** [comment]
Oooo! Great!

the browserchecks stuf was something written just in order to test few code on saucelabs for the browsers that were not supported in order to evaluate that at least it behavies as they are expected to behave (e.g. they show clear error messages).

by the way if you suggest to use them also for implementing the client test (javascript only) we can keep the concept and use the same libraries.

@ianribas: do you think that this is a good solution or have you already seen that for angularjs there is something better?

**Comment by vodkina** [comment]
great!
