### ISSUE TITLE
Delete files with a secure delete function

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#688]
Currently files are deleted with standard python delete.

This ticket is about implementing a secure delete facility to improve the security of the system when deleting files.

**Comment by vecna** [comment]
@evilaliv3 please review

**Comment by fpietrosanti** [comment]
We may consider also adding a secure delete for database data FYI https://www.sqlite.org/pragma.html#pragma_secure_delete

**Comment by evilaliv3** [comment]
Here we go!

this commit is addressed. 
by analysis of the main standards on the topic and state of the art implementations (https://en.wikipedia.org/wiki/Data_erasure) with @vecna we decided to implement a function that implement:
- a rewrite with all 0s
- a rewrite with all 1s
- a rewrite with random data

this cycle of three rewrites is repeated N iterations with N currently set to 1.

the overwrite process is executed in a deferred schedule executed once every hour so to avoid causing database lock issues or other blocking activities. the scheduler makes use of a new database table callsed SecureFileDelete that lists the files to be securely deleted so that the operation is resilient to interruptions due to application/system reboots without issues with leaked l.
