### ISSUE TITLE
Flood Resiliency: Delay over New Submission

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#796]
In relation to the GlobaLeaks Submission Flood Resiliency Project documented at https://docs.google.com/document/d/1P-uHM5K3Hhe_KD6YvARbRTuqjVOVj0VkI7qPO9aWFQw/edit?usp=sharing this ticket is to implement Delay over New Submission

**Comment by evilaliv3** [comment]
@vecna what is the update of this ticket? can you describ what you have currently addressed in the new branch you created few things ago. this things will be needed also to write the related section in the OTF montly repor.

**Comment by vecna** [comment]
I'll update ASAP, just I'm a little overbusy in those days, sorry.

**Comment by vecna** [comment]
Ok, implementation is done, at the moment token is part of the REST.

  * POST (SubmissionCreate) now is a DB-free operation, creating a token instead of the InternalTip.id = submission_id
  * PUT put the token in the URL, instead of the previous submission_id, the token is validated and submission accepted. 

In addition, context_id is part of the REST API, /submission/$context_id now is in use.
https://github.com/globaleaks/GlobaLeaks/commits/token-integration

**Comment by vecna** [comment]
Integrated, at the moment the values for submission duration are defined in globaleaks.utils.token, they are:

    SUBMISSION_MINIMUM_SECONDS = 15
    MAXIMUM_AVAILABILITY = 4 * SUBMISSION_MINIMUM_SECONDS
            # TODO talk in an issue
    MAXIMUM_FILE_PER_TOKEN = 20

of course the MAXIMUM_AVAILABILITY has not to be 60 seconds (at the moment, the good window of submission is 15 sec - 60 sec). Has to be the same of 'submission_timetolive'.

If GlobaLeaks is started with -z (development mode):

        # Remind: this is just for developer, because if a clean house
        # is a sign of a waste life, a Token object without shortcut
        # is a sign of a psyco life.
        if GLSetting.devel_mode:
            self.start_validity_secs = 0

so when we perform our test, we can submit without waiting.

I guess, in GLClient, has to be impemented a countdown displaying when the submission can be submitted ?

**Comment by vecna** [comment]
@evilaliv3 @hellais did you saw some angular module to implement a countdown ?

**Comment by hellais** [comment]
@vecna This directive seems aproapriate: https://github.com/siddii/angular-timer

**Comment by evilaliv3** [comment]
this is currently included in master but disabled by me with an enforced 0 delay.

what is still missin to consider this ticket closed:
1) implement clientside UI support for the delay
2) implement the function that depending on the conditions of the system increase the start_validity_time of the token up to the maximum; for the moment we can implement a simple dummy dunction that will return always the same value and then discuss it deeply.
3) export variable configurations in DB / GLClient (debatable)

**Comment by evilaliv3** [comment]
@vecna thanks to @EvanHahn and @siddi this two pull requests have been now integrated so that we won't face any of the issue you were having:
https://github.com/EvanHahn/HumanizeDuration.js/issues/54
https://github.com/siddii/angular-timer/pull/181

a different library but to be used for an aim similar to the one related to this ticket is: https://github.com/wildlyinaccurate/angular-relative-date

i will work a little bit in order to make the translation part become part of the library while now it's demandded to the adopter tu push the strings inside it.

@mapmeld any clue on this? how are you managing this part in your projects? https://github.com/wildlyinaccurate/angular-relative-date/issues/8

**Comment by fpietrosanti** [comment]
Please use the appropriate tickets for implementing the Countdown, requirement coming from Amnesty International #749

**Comment by evilaliv3** [comment]
let me say @fpietrosanti  that this or the other is the same as also the other is not related to countdown in general but to a specific feature. and @vecna is not implementing that feature right now but this one, so it's correct that he is writing things here.

**Comment by vecna** [comment]
I've updated on the branch the submission viz, now I'll address the DB update.

**Comment by evilaliv3** [comment]
ok!  :) let here the notes on the DB changes so that i will deal will the migration script when we will integrate it.

**Comment by vecna** [comment]
These are the new fields supported:

    submission_minimum_delay
    submission_maximum_ttl

**Comment by vecna** [comment]
This branch has been merged with #798 as intermediary merge. deleting this branch.

**Comment by vecna** [comment]
Based on the updates, the remaining section of this issue will be completed with the #800, closing this one.
