### ISSUE TITLE
Flood Resiliency: Delay between first access and submission

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#800]
In relation to the GlobaLeaks Submission Flood Resiliency Project documented at https://docs.google.com/document/d/1P-uHM5K3Hhe_KD6YvARbRTuqjVOVj0VkI7qPO9aWFQw/edit?usp=sharing this ticket is to implement Delay between first access and submission

**Comment by vecna** [comment]
Is implemented with the token alignment here: https://github.com/globaleaks/GlobaLeaks/commits/token-integration will be unit tested soon. plus, I will handle the -z option to reduce to 0 the time window required between Token-initial-request and submission.

**Comment by vecna** [comment]
Implemented, timings need to be fine tunes.

**Comment by evilaliv3** [comment]
ok this has been implemented by @vecna for the backend side and i've integrated it in the current release (2.60.64).

right now the submission slowdown is disabled (with a 0 delay setting) and in order to enable it we should first implement the clientside detection of the error and a proper handling.

to proceeed @fpietrosanti / @vecna now i've this doubt:
ok now we are able to delay the submission (that will be something like 20 seconds or more eventually convifurable) but no delay is applied to the usage of the token for the file upload (that should be done by the user starting soon, 1 second after getting the token?); should we have 2 different time settings for this two different operations? (submission_close, upload)

**Comment by fpietrosanti** [comment]
@evilaliv3 I think that only submission_close shall be tracked as operation regarding the timing measurement between user starting a submission a finalizing, because is the one that trigger backend operations/actions (tip creation, notifications, etc). 

A "file upload" on a new submission does not trigger backend operations/actions itself and is "part of the submission process", so i don't think it shall have a delay being mesured.

Regarding the GLC, it shall also know the timing required between first access and submission finalization in a stateful way, preventing the end-user from clicking "Submit" (that way this condition will trigger only with custom/modified submission client focused on flood but not on normal system) .

The amount of time between "start of submission" and "end of submission" shall be configurable from admin interface.

The event of a too fast action between start of submission and end of submission shall be:
- notified to the admin by email with diagnostic information to let him understand what's going on
- logged to filesystem log

**Comment by vecna** [comment]
To close this issue:

  * admin interface has to be modify with two values:
    * minimum amount of seconds required to end a submission (default, 120 ?)
    * maximum duration of a submission (default, 1800 ?)
  * creation of a new template for the admin in case a failure of this check happen = **unclear**, want is the information ? "*someone has make a GLClient bad and/or try-to-be malicious*" because is the only reason to see a submission rejected early **or** is "*someone has open a submission but has waited too much and when has click on submit the time was expired*" = in this case, is a software problem or a configuration problem. is that an ALERT ?
  * log.err (in future, refactored with all the logs)
  * submission button disabled + countdown as per #796

**Comment by evilaliv3** [comment]
i'm ok with all except a minor doubt on the default for the maximum duration. half an hour would limit a lot the file uploads size of a file uploaded over Tor. i'm not able to suggest a number that would be randomly chosen by me but i would say 7200. who offers more?

probably would be important to have them configurable on the advanced settings as for sure a lot of adopters will blame on the minimum time.

**Comment by vecna** [comment]
what about: ( 15 seconds * Number_of_fields_in_the_steps ) ?

maybe not 15, but probably is a value that has to be context dependent ( submission_timetolive was, and Token at the moment are associated to a context, too)

**Comment by evilaliv3** [comment]
i think that a fixed value of few let's say 15 seconds is ok for fighting dos attacks (1s would be enough in the real case, 15 seconds will fuck it up for sure).
making it dependend to the number of fields/staps will create funny not controllable situations (and wat about required/not required fields)

 KISS :)

**Comment by vecna** [comment]
Ok, Everything is done here. The only things unclear is the request of @fpietrosanti about the email template for the admin: to say what ? 

This branch is merged in #798 and already rebase to devel, in the PR #1277 Issue will be closed when merged.

**Comment by evilaliv3** [comment]
okay @vecna current backend implementation satisfy me. the clientside one was for me a little too complex from usability point of view an due to the fact that i was interested in integrating the functionality with a not invasive interface i've integrated all except the countdown widget but implemented the countdown on the button. tomorrow i will be out but returning i will properly finalize and reintegrate it but the feature is already in place an finalized.
the code removed is in https://github.com/globaleaks/GlobaLeaks/commit/44dac4fbcb54708f5b998cb8f2213ea91c6e7096

i've also currently removed angular-timer as we still were encountering issues and it seems that momentjs would be more stable, maintained and used; currently i've implemented all in simply usin angular $timeout.

the interface is now the following:
![screenshot from 2015-06-01 22 31 52](https://cloud.githubusercontent.com/assets/217034/7923374/db599070-08b2-11e5-8ae8-13f045c8a070.png)
![screenshot from 2015-06-01 22 31 54](https://cloud.githubusercontent.com/assets/217034/7923391/06643a9a-08b3-11e5-878f-aa00248e84b0.png)

**Comment by evilaliv3** [comment]
the current implementation satisfy the requirement of the deliverable. eventual UI improvals are postponed for later develpements.
