### ISSUE TITLE
Evaluate OpenSUSE Build Service (Ubuntu, Debian, Suse,Fedora) + DEB/RPM

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#851]
It should be evaluated and analyzed whenever it's useful to integrate into the globaleaks development process the automatic build made by OpenSuse Build Service: https://build.opensuse.org/

It does provide both Deb+RPM and support for Ubuntu, Debian, Fedora, Suse.

To be evaluated if it's a useful/nice platform to be used for our cross-platform packaging (once we have _all_ of the dependencies as a deb/rpm package)
##

**Comment by fpietrosanti** [comment]
Now support all Ubuntu and all Debian 
Ref: https://en.opensuse.org/openSUSE:Build_Service_Concept_SourceService
Ref for Github or Travis Hook: https://github.com/imatix/gsl/issues/154

Example how Oscomcom is using it: https://build.opensuse.org/project/monitor/network:osmocom:nightly


/cc @evilaliv3

**Comment by evilaliv3** [comment]
I think that probably we should consider this ticket sooner than later as an extension to what already do on Travis.

The reason is that:
- travis support only Ubuntu and actually every run runs on a Ubuntu Trusty
- on travis it is not clear which is the build environment and dependencies changes without us noticing it.

This would be particular important not just to be able to study and implement support for other Distributions (e.g. Centos/RedHat/Fedora) but also to be able to keep tested the support for different LTS Versions of Ubuntu and Debian.

In fact both for Ubuntu and Debian are now 3 (6 in total) the LTS versions that we support with a mixture of different dependencies versions.

**Comment by evilaliv3** [comment]
Closing this ticket postponing this topic for the moment.
