### ISSUE TITLE
When a submission is going to expire, the receivers involved must be notified

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#921]
It happened that some submission by IRPI has expired and the journalist didn't know about it.

After discussion with them, we identified that they would had been able to postpone the submission if they would had received a notification of "upcoming expiry" of the submission.

This ticket is to introduce functionality to notify the receiver when the tip are going to expire.

Those should be configurable based on the amount of "days" to be notified and should be exposed to the receiver settings.

That notification should be configurable from the receivers, if he want to receive it.

**Comment by fpietrosanti** [comment]
That's very similar to TI #748

**Comment by vecna** [comment]
the days number should be configurable by the journalist (because they known their times) or by the admin ?

**Comment by fpietrosanti** [comment]
@vecna Probably a node-wide settings that the receiver can override could be the best way to go.

**Comment by vecna** [comment]
At the moment I've hardcoded two days, to permit a flexible timing, we need a DB update. 
In the meantime, the translation of the new notification template may start.

In the commit, also a cleaning of the "cleaning" logic has been done, with the token the internaltip.mark == 'submission' do not exists anymore. That's why the branch as HEAD to token-integration.

At the moment we've a constrain: 

        mark VARCHAR NOT NULL CHECK (mark IN ('submission', 'finalize', 'first')),

'finalize' is used in the token-integration branch to mark all the submission
'first' is used when the ReceiverTip are created.

We need a marker to say "this submission has been already notified that is going to expire" otherwise, the notification is triggered every time cleaning sched run. now I'm using the marker 'submission', but I feel the naming has to be review in the next DB update.

In the next DB update, we can modify or that, or create new statuses in ReceiverTip (notification for receiver are based on that, but I preferred put the time-check in the same block of logic)

p.s. under which OTF sub-deliverable this feature is accounted ?  

### Note: to test it, use:

    bin/globaleaks -n -l DEBUG -d -z vecna --XXX 45000

and globaleaks run 45k seconds in the future, play with that based on your expiration policies.

**Comment by evilaliv3** [comment]
k if this is ready i will assign this to me for integration that i will do in march (probably the week of the 5th)

i don't like so much to reuse finalize, first with differnt meanings.
so can you please describe here the states you need? i will implement the right migration when integration.

i've also accumulated tons of other changes and additions that i would like to add to next db migration in order to ancitipate vaious features that origniante and i are working on. and some others related to notification config.

**Comment by vecna** [comment]
**Off Topic in the DB changes: ReceiverTip.assigned_label unicode to be added to ReceiverTip** 

The status used:

  * 'finalized' when WB complete the submission
  * 'first' when delivery make it switch and generate ReceiverTip (after 30 second smore or less)
  * after EXPIRATION DATE - ALERT TIME, receiver get notification, the status can be renamed 'alerted', now is used 'submission'.
  * if the receiver postpone the tip, the status comeback from 'alerted' to 'first'
  * when expire, will be probably in 'alerted'  
  * 'first' can be renamed, after this changes, in 'dispatched' because has been dispatch to the receivers.

**Comment by evilaliv3** [comment]
**concerning the Off Topic comment in the DB changes: ReceiverTip.assigned_label

are you talking of the single label that is sent in the email right? if yes i agree for this solution.
if you instead means the TAGS my suggestion for the future is that we add a Tags table:
(ID, object_type, TAG(nicode_internazionalized)) to be associated to various object_types (e.s rtips by reference or multiple reference)

** 

i will think a little to this status, thank for clarifying.

**Comment by evilaliv3** [comment]
i've temporary assigned it to me in order to remember me to push upstream the templates by review them, complete with @hellais and include in devel branch so to anticiapate translators.

**Comment by vecna** [comment]
About the OT: I was meaning #1156 (touch notification %TemplateKeywords% and a ReceiverTip field, Status page UI and TipList UI), not Tag. good idea about Tag, but I don't have yet an use case in my mind.

**Comment by evilaliv3** [comment]
I agree on postponing tags. In past you added this as simply pickle or
unicode. I changed this recently removing tag viable so I was simply
annotating the good way to reintroduce it eventually in the feature when
dealing with TI requirements.

**Comment by evilaliv3** [comment]
all the code related to this feature has been reviewd by me and integrated in devel branch. will be shipped in next release.

**Comment by fpietrosanti** [comment]
Is it configurable the amount of days to be alerted before the expiry?

**Comment by evilaliv3** [comment]
you are right, this is missing.

do we wanna offer this configuration possibilities per user or at server level?
i'm starting thiking that in general as for a lot of settings like this a global configuration variable is enough.

**Comment by fpietrosanti** [comment]
Default server-wide (globaleaks)
Receiver can override it

**Comment by evilaliv3** [comment]
this has been forget from from the current release (2.60.65); i will move this to next milestone so that we will remember to add the support for this.

**Comment by evilaliv3** [comment]
@vecna if i'm not wrong concerning this ticket no step forward has been don in the direction of what fabios was proposing right?

anyhow @fpietrosanti i would suggest for the moment to keep this only configurable by the admin in order to not introduce so much features for the receiver while we are still testing their usefulness

**Comment by fpietrosanti** [comment]
@evilaliv3 From the use-scenario described by amnesty receivers are likely to configure themselves the parameters (because they go on mission), while IRPI and TI-it probably do not need it because a 1-receiver leaksite where receiver=admin

**Comment by evilaliv3** [comment]
all that relates this ticket has been released starting from 2.60.76. time to close the ticket.
