### ISSUE TITLE
Integrate support for preprocessing selected files inside of Flow.js

### ISSUE THREAD

**Issue by hellais** [globaleaks/GlobaLeaks#930]
This is needed so that it is possible to apply encryption to selected files before they are sent via XHR to the backend. Such support needs to be added to jquery-file-uploader.

GLClient will then override this hook so that files are encrypted with the key(s) of the selected receiver(s).

**Comment by evilaliv3** [comment]
what is the status of this ticket? it's ok for you to restart working on the PGP related stuffs since january @hellais ?

**Comment by evilaliv3** [comment]
this ticket is now related to Flow.js instead of jquery-file-uploader

the support for this has been implemented by @hellais in https://github.com/flowjs/flow.js/pull/82, the code will be tested in our development branch for end2end encryption and integrated as soon that the patch will be inserted in flow.js

**Comment by hellais** [comment]
I believe no further code needs to be implemented to support this.

To have an idea of how to implement the hooks specific for openpgp.js see: https://github.com/hellais/pgp-file-upload/blob/master/app/scripts/controllers/main.js#L48

**Comment by evilaliv3** [comment]
This ticket can be finally closed as the support for flowjs for working in streaming has been finally integrated!

https://github.com/flowjs/flow.js/pull/111

allright!

**Comment by drzraf** [comment]
Coming from https://github.com/globaleaks/GlobaLeaks/issues/2839
Time to reopen?
